"""
add_docstrings.py - Add or improve module-level docstrings across the codebase.

Reads each target module, inserts a triple-quoted docstring before the first
import or code line. Uses Python binary mode to preserve line endings (CRLF/LF).
Touches NO code -- only adds or replaces the module docstring.

Run from the project directory:
    python add_docstrings.py          # preview mode (prints, doesn't write)
    python add_docstrings.py --write  # actually writes files

Module updated: April 2026 with Anthropic's Claude Opus 4.6
"""

import os
import sys
import re

# ============================================================
# DOCSTRINGS TO ADD
# ============================================================
# Key = module name (without .py)
# Value = docstring content (will be wrapped in triple quotes)
#
# Standard format:
#   Line 1: module_name.py - One-line purpose.
#   Lines 2+: 2-3 sentence explanation.
#   Key functions: top 3-5 (only for complex modules)
#   Credit line.

DOCSTRINGS = {

    # ============================================================
    # NO DOCSTRING GROUP (21 modules)
    # ============================================================

    'catalog_selection': (
        'catalog_selection.py - Unified star selection from Hipparcos and Gaia catalogs.\n'
        '\n'
        'Merges stars from both catalogs with consistent deduplication logic.\n'
        'Used by both magnitude-mode and distance-mode HR diagram pipelines.\n'
        'Returns combined astropy Table with star counts by source category.\n'
        '\n'
        'Key functions:\n'
        '    select_stars() - Select and merge stars by magnitude or distance limit\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'comet_visualization_shells': (
        'comet_visualization_shells.py - Comet visual components for 3D orrery plots.\n'
        '\n'
        'Builds nucleus, coma, ion tail, dust tail, and anti-tail traces for comets.\n'
        'Tail geometry is computed from Sun direction and heliocentric distance using\n'
        'activity factors that scale with solar proximity. Includes specialized traces\n'
        'for C/2026 A1 (MAPS): disintegration marker and ghost tail arc.\n'
        '\n'
        'Key functions:\n'
        '    create_comet_nucleus() - Scaled sphere marker at comet position\n'
        '    create_comet_ion_tail() - Straight anti-sunward ion tail\n'
        '    create_comet_dust_tail() - Curved dust tail with radiation pressure\n'
        '    create_maps_disintegration_marker() - Green diamond at 8.33 R_sun\n'
        '    create_maps_ghost_tail_trace() - Post-disintegration debris arc\n'
        '    add_comet_tails_to_figure() - Master dispatch: adds all tail traces to fig\n'
        '\n'
        'Consumed by: palomas_orrery.py (plot_objects, animate_objects)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'create_cache_backups': (
        'create_cache_backups.py - One-shot script to create timestamped backups of star data caches.\n'
        '\n'
        'Calls simbad_manager.protect_all_star_data() to back up SIMBAD query results\n'
        'and stellar property caches. Run manually before risky cache operations.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'earth_system_controller': (
        'earth_system_controller.py - KMZ layer selector for Google Earth Pro.\n'
        '\n'
        'Simple Tkinter GUI that lets users browse, select, and open KMZ climate\n'
        'data layers in Google Earth Pro. Layers are generated by\n'
        'earth_system_generator.py and stored in the data/ directory.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'earth_visualization_shells': (
        'earth_visualization_shells.py - Earth interior and orbital shell traces.\n'
        '\n'
        'Sphere shells for Earth\'s interior layers (inner core through crust),\n'
        'atmosphere, and upper atmosphere. Custom geometry for the magnetosphere,\n'
        'LEO altitude shell, and geostationary belt. Each function returns Plotly\n'
        'Scatter3d traces positioned relative to a center_position in AU.\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'eris_visualization_shells': (
        'eris_visualization_shells.py - Eris interior and boundary shell traces.\n'
        '\n'
        'Sphere shells for Eris: core, mantle, crust, tenuous atmosphere, and\n'
        'Hill sphere. Based on New Horizons flyby constraints and thermal models.\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'jupiter_visualization_shells': (
        'jupiter_visualization_shells.py - Jupiter interior, ring, and magnetosphere shell traces.\n'
        '\n'
        'Sphere shells for Jupiter\'s interior (core through cloud layer). Custom\n'
        'geometry for the ring system, Io plasma torus, radiation belts, and\n'
        'magnetosphere. Jupiter\'s magnetosphere is the largest structure in the\n'
        'solar system after the heliosphere.\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'mars_visualization_shells': (
        'mars_visualization_shells.py - Mars interior and remnant field shell traces.\n'
        '\n'
        'Sphere shells for Mars interior layers (inner core through crust),\n'
        'atmosphere, upper atmosphere, remnant magnetosphere, and Hill sphere.\n'
        'Mars lacks a global dipole field; its magnetosphere represents crustal\n'
        'magnetic anomalies.\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'mercury_visualization_shells': (
        'mercury_visualization_shells.py - Mercury interior, exosphere, and unique feature traces.\n'
        '\n'
        'Sphere shells for Mercury\'s large iron core (inner/outer), thin mantle and\n'
        'crust. Custom geometry for the sodium exosphere tail (anti-sunward),\n'
        'magnetosphere (compressed by solar wind), and Hill sphere. Mercury\'s core\n'
        'is proportionally the largest of any planet (~85%% of its radius).\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'moon_visualization_shells': (
        'moon_visualization_shells.py - Lunar interior and exosphere shell traces.\n'
        '\n'
        'Sphere shells for the Moon: inner core, outer core, mantle, crust,\n'
        'tenuous exosphere, and Hill sphere. All sphere-only -- no custom geometry.\n'
        'Candidate for full migration to shell_configs.py (no custom functions needed).\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'neptune_visualization_shells': (
        'neptune_visualization_shells.py - Neptune interior, ring, and magnetosphere shell traces.\n'
        '\n'
        'Sphere shells for Neptune\'s interior (core, mantle, clouds). Custom geometry\n'
        'for the ring system, tilted magnetosphere (47 degrees from rotation axis),\n'
        'magnetic field lines, and radiation belts. Neptune\'s offset dipole creates\n'
        'one of the most complex magnetospheres in the solar system.\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'orbital_param_viz': (
        'orbital_param_viz.py - Interactive orbital element visualization tool.\n'
        '\n'
        'Standalone Tkinter GUI that shows how the six Keplerian orbital elements\n'
        '(a, e, i, omega, Omega, M) transform a circle into a 3D orbit. Step-by-step\n'
        'construction with animated arcs, coordinate frames, and angle annotations.\n'
        'Educational companion to the main orrery -- helps users understand what\n'
        'osculating elements mean geometrically.\n'
        '\n'
        'Key functions:\n'
        '    create_orbital_transformation_viz() - Build the step-by-step 3D figure\n'
        '    create_eccentricity_demo_window() - Interactive e slider demonstration\n'
        '    create_orbital_viz_window() - Main GUI window with object selector\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'planet9_visualization_shells': (
        'planet9_visualization_shells.py - Hypothetical Planet 9 shell traces.\n'
        '\n'
        'Sphere shells for Planet 9: estimated surface and Hill sphere only.\n'
        'Based on Batygin & Brown (2016) orbital predictions. All sphere-only --\n'
        'fully archivable once shell_configs.py migration is complete.\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'plot_data_exchange': (
        'plot_data_exchange.py - JSON data exchange between subprocess scripts and GUI.\n'
        '\n'
        'Saves plot data (star counts, processing times, mode settings) to a JSON\n'
        'file that the main GUI reads to populate the report widget. Bridge between\n'
        'standalone HR diagram scripts (which run as subprocesses) and the star\n'
        'visualization GUI.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'plot_data_report_widget': (
        'plot_data_report_widget.py - Embedded report panel for star visualization results.\n'
        '\n'
        'Tkinter widget that displays star counts, magnitude distributions, spectral\n'
        'class breakdowns, and processing times after an HR diagram is generated.\n'
        'Reads data from plot_data_exchange.py. Includes object type analysis via\n'
        'ObjectTypeAnalyzer when available.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'pluto_visualization_shells': (
        'pluto_visualization_shells.py - Pluto interior and atmosphere shell traces.\n'
        '\n'
        'Sphere shells for Pluto: core, mantle, crust, haze layer, atmosphere,\n'
        'and Hill sphere. Based on New Horizons (2015) data. All sphere-only --\n'
        'fully archivable once shell_configs.py migration is complete.\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'saturn_visualization_shells': (
        'saturn_visualization_shells.py - Saturn interior, ring, and magnetosphere shell traces.\n'
        '\n'
        'Sphere shells for Saturn\'s interior (core through cloud layer). Custom\n'
        'geometry for the ring system (A, B, C, D, F, G, E rings with Cassini\n'
        'Division), Enceladus plasma torus, radiation belts, and magnetosphere.\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'solar_visualization_shells': (
        'solar_visualization_shells.py - Sun interior, corona, and heliosphere shell traces.\n'
        '\n'
        'The largest shell module: 14 sphere shells from core to gravitational\n'
        'influence boundary, plus custom geometry for Hills Cloud torus, Oort Cloud\n'
        'clumpy distribution, and galactic tide shell. Includes the v3.18 solar\n'
        'shell refactor: single-info-marker pattern, n_points=20/25, and the\n'
        'three inner corona shells (Streamer Belt, Roche Limit, Alfven Surface)\n'
        'added for the MAPS comet coronal journey.\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher),\n'
        '             palomas_orrery.py (hover_text_sun import)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'star_properties': (
        'star_properties.py - SIMBAD stellar property queries with local caching.\n'
        '\n'
        'Fetches detailed stellar properties (spectral type, magnitudes, identifiers)\n'
        'from SIMBAD for individual stars, caching results locally to avoid repeated\n'
        'queries. Handles both old and new SIMBAD API column name formats.\n'
        '\n'
        'Key functions:\n'
        '    query_simbad_for_star_properties() - Batch query with cache\n'
        '    load_existing_properties() - Load from local pickle cache\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'uranus_visualization_shells': (
        'uranus_visualization_shells.py - Uranus interior, ring, and magnetosphere shell traces.\n'
        '\n'
        'Sphere shells for Uranus interior (core, mantle, clouds). Custom geometry\n'
        'for the ring system, radiation belts, tilted magnetosphere (59 degrees\n'
        'from rotation axis), and Hill sphere. Uranus rotates nearly on its side,\n'
        'making its magnetosphere geometry unique.\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'venus_visualization_shells': (
        'venus_visualization_shells.py - Venus interior and atmosphere shell traces.\n'
        '\n'
        'Sphere shells for Venus: core, mantle, crust, dense atmosphere, upper\n'
        'atmosphere, induced magnetosphere, and Hill sphere. Venus has no intrinsic\n'
        'magnetic field; its induced magnetosphere results from solar wind\n'
        'interaction with the ionosphere.\n'
        '\n'
        'Consumed by: planet_visualization.py (routing dispatcher)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    # ============================================================
    # WEAK DOCSTRING GROUP (21 modules)
    # ============================================================

    'constants_new': (
        'constants_new.py - Central constants, parameters, and object catalogs for the orrery.\n'
        '\n'
        'The project\'s single source of truth for physical constants (KM_PER_AU,\n'
        'solar radii, planetary radii), object type mappings, color palettes, orbital\n'
        'period tables, spectral class data, and the master lists of planets, moons,\n'
        'comets, asteroids, and spacecraft with their Horizons IDs and orbital elements.\n'
        'Nearly every module in the project imports from this file.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'data_processing': (
        'data_processing.py - Star catalog data cleaning, merging, and analysis.\n'
        '\n'
        'Processes raw Hipparcos and Gaia catalog data: coordinate system alignment,\n'
        'magnitude estimation, distance calculation, deduplication, and outlier\n'
        'detection. Produces the cleaned combined tables used by HR diagram and\n'
        'planetarium visualization pipelines.\n'
        '\n'
        'Key functions:\n'
        '    calculate_distances() - Parallax to light-year conversion\n'
        '    align_coordinate_systems() - ICRS/Hipparcos frame alignment\n'
        '    select_stars_by_magnitude() - Apply magnitude/distance cuts\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'hr_diagram_apparent_magnitude': (
        'hr_diagram_apparent_magnitude.py - HR diagram pipeline for apparent magnitude queries.\n'
        '\n'
        'Standalone script (runs as subprocess from star_visualization_gui.py).\n'
        'Fetches stars from Hipparcos and Gaia by apparent magnitude limit,\n'
        'processes through data_processing.py, builds 2D HR diagram via\n'
        'visualization_2d.py. Results passed back via plot_data_exchange.py.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'hr_diagram_distance': (
        'hr_diagram_distance.py - HR diagram pipeline for distance-based queries.\n'
        '\n'
        'Standalone script (runs as subprocess from star_visualization_gui.py).\n'
        'Fetches stars from Hipparcos and Gaia within a distance limit in\n'
        'light-years, processes through data_processing.py, builds 2D HR diagram\n'
        'via visualization_2d.py. Results passed back via plot_data_exchange.py.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'idealized_orbits': (
        'idealized_orbits.py - Keplerian orbit ellipse construction and satellite orbit models.\n'
        '\n'
        'Computes and plots idealized (Keplerian) orbit paths from orbital elements,\n'
        'with osculating element support for high-accuracy visualization. Handles\n'
        'elliptical, parabolic, and hyperbolic orbits. Includes specialized models\n'
        'for planetary satellite systems (Mars, Jupiter, Saturn, Uranus, Neptune)\n'
        'with proper parent-body-relative coordinate transforms.\n'
        '\n'
        'The largest computation module (~6,100 lines). Consumed by palomas_orrery.py\n'
        'for both plot_objects and animate_objects orbit rendering.\n'
        '\n'
        'Key functions:\n'
        '    plot_idealized_orbits() - Master orbit renderer for all object types\n'
        '    add_mean_orbit_trace() - Simple Keplerian ellipse from mean elements\n'
        '    calculate_*_satellite_elements() - Per-system satellite orbit models\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'messier_catalog': (
        'messier_catalog.py - Static catalog of Messier objects and bright deep-sky objects.\n'
        '\n'
        'Dictionary-based catalogs of Messier objects (M1-M110), bright open clusters,\n'
        'bright planetary nebulae, and bright emission nebulae. Each entry includes\n'
        'name, type, visual magnitude, distance, coordinates, and observing notes.\n'
        'Data source for the star visualization 3D planetarium views.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'messier_object_data_handler': (
        'messier_object_data_handler.py - Messier object coordinate transforms and data preparation.\n'
        '\n'
        'Converts Messier catalog entries from RA/Dec to Cartesian coordinates for\n'
        '3D visualization. Handles both distance-based and magnitude-based queries.\n'
        'Adds hover text with observing notes from star_notes.py. Produces pandas\n'
        'DataFrames consumed by visualization_3d.py for planetarium rendering.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'palomas_orrery': (
        'palomas_orrery.py - Main GUI and plotting engine for Paloma\'s Orrery.\n'
        '\n'
        'The central application: Tkinter GUI with object selection, date controls,\n'
        'and two primary rendering pipelines -- plot_objects() for static 3D scenes\n'
        'and animate_objects() for animated sequences. Integrates JPL Horizons\n'
        'ephemeris data, osculating orbital elements, spacecraft encounters, comet\n'
        'tails, shell visualizations, and the celestial sphere into interactive\n'
        'Plotly figures.\n'
        '\n'
        'At ~8,600 lines this is the project monolith. Key internal functions:\n'
        '    plot_objects() - Static 3D solar system rendering (~line 3900)\n'
        '    animate_objects() - Animated rendering with frames (~line 5744)\n'
        '    fetch_position() - JPL Horizons position query (~line 1531)\n'
        '    calculate_axis_range_from_orbits() - Scale-aware axis fitting (~line 602)\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'palomas_orrery_helpers': (
        'palomas_orrery_helpers.py - Support functions extracted from the main orrery monolith.\n'
        '\n'
        'Trajectory fetching, orbit path backup/restore, URL button construction,\n'
        'camera presets, Planet 9 analytical position calculation, and the _info\n'
        'string imports for shell tooltip text. Originally created to reduce\n'
        'palomas_orrery.py file size.\n'
        '\n'
        'Key functions:\n'
        '    fetch_trajectory() - Multi-segment Horizons trajectory fetch\n'
        '    add_url_buttons() - Plotly updatemenus for JPL/NASA links\n'
        '    get_default_camera() - Standard camera position dict\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'planetarium_distance': (
        'planetarium_distance.py - 3D star field pipeline for distance-based queries.\n'
        '\n'
        'Standalone script (runs as subprocess from star_visualization_gui.py).\n'
        'Fetches stars within a distance limit, processes through data_processing.py,\n'
        'builds 3D stellar neighborhood visualization via visualization_3d.py.\n'
        'Results passed back via plot_data_exchange.py.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'shared_utilities': (
        'shared_utilities.py - Small shared helpers used across shell visualization modules.\n'
        '\n'
        'Currently contains create_sun_direction_indicator(), which adds a visual\n'
        'arrow showing the Sun\'s direction in body-centered plots. Used by most\n'
        'planetary shell modules when the center body is not the Sun.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'shutdown_handler': (
        'shutdown_handler.py - Graceful shutdown and safe figure display for Plotly.\n'
        '\n'
        'Manages thread cleanup on application exit and provides show_figure_safely(),\n'
        'which opens Plotly figures in the browser with proper temp file handling\n'
        'and optional save-to-file dialog. Wraps save_utils.show_and_save().\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'star_notes': (
        'star_notes.py - Curated hover text annotations for notable stars.\n'
        '\n'
        'Dictionary mapping SIMBAD identifiers to HTML-formatted descriptive text\n'
        'for ~200 notable stars. Includes historical names, physical properties,\n'
        'binary/multiple system notes, and cultural significance. Displayed as\n'
        'hover text in HR diagrams and 3D star visualizations.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'star_visualization_gui': (
        'star_visualization_gui.py - Stellar visualization GUI for Paloma\'s Orrery.\n'
        '\n'
        'Tkinter interface for HR diagrams (2D), 3D stellar neighborhoods, and\n'
        'planetarium views. Launches hr_diagram_*.py and planetarium_*.py as\n'
        'subprocesses, displays results via plot_data_report_widget.py. Supports\n'
        'magnitude-based and distance-based queries with lazy-loaded star property\n'
        'details.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'star_visualization_gui_before_pyinstaller_refactor': (
        'star_visualization_gui_before_pyinstaller_refactor.py - Pre-PyInstaller version of the star GUI.\n'
        '\n'
        'Archived copy of star_visualization_gui.py before the PyInstaller\n'
        'packaging refactor. Kept as reference. Use star_visualization_gui.py\n'
        'for active development.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'stellar_data_patches': (
        'stellar_data_patches.py - Manual corrections for stars with known bad catalog data.\n'
        '\n'
        'Small patch table mapping HIP numbers to corrected temperature, luminosity,\n'
        'and spectral type values. Applied after catalog processing to fix stars\n'
        'where automated pipelines produce incorrect results (e.g., Mizar).\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'stellar_parameters': (
        'stellar_parameters.py - Stellar temperature and parameter estimation from spectral types.\n'
        '\n'
        'Converts spectral type strings (e.g., "G2V", "M3III") to effective\n'
        'temperatures using lookup tables from constants_new.py. Handles B-V\n'
        'color index temperature estimation as fallback. Used by the HR diagram\n'
        'pipeline when catalog temperatures are missing.\n'
        '\n'
        'Key functions:\n'
        '    estimate_temperature_from_spectral_type() - Spectral type to Teff\n'
        '    calculate_bv_temperature() - B-V color to Teff fallback\n'
        '    select_best_temperature() - Pick best available Teff source\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'visualization_2d': (
        'visualization_2d.py - 2D HR diagram (color-magnitude) plot builder.\n'
        '\n'
        'Creates Hertzsprung-Russell diagrams from processed star data: temperature\n'
        'vs. luminosity scatter plots with spectral class coloring, hover text with\n'
        'stellar properties, and statistical annotation. The 2D counterpart to\n'
        'visualization_3d.py. Output displayed in browser via Plotly.\n'
        '\n'
        'Key functions:\n'
        '    create_hr_diagram() - Main HR diagram figure builder\n'
        '    prepare_2d_data() - Data preparation and filtering\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'visualization_3d': (
        'visualization_3d.py - 3D stellar neighborhood and planetarium plot builder.\n'
        '\n'
        'Creates 3D scatter plots of stars in Cartesian coordinates (light-years or\n'
        'parsecs) with spectral class coloring, Messier object overlays, and notable\n'
        'star annotations. Includes the Sun at origin. The 3D counterpart to\n'
        'visualization_2d.py.\n'
        '\n'
        'Key functions:\n'
        '    create_3d_visualization() - Main 3D star field figure builder\n'
        '    prepare_3d_data() - Coordinate transforms and data preparation\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'visualization_core': (
        'visualization_core.py - Shared data preparation and formatting for star visualizations.\n'
        '\n'
        'Common functions used by both visualization_2d.py and visualization_3d.py:\n'
        'temperature-to-color mapping, star count analysis, magnitude distribution\n'
        'statistics, and hover text formatting. Extracted to avoid duplication\n'
        'between the 2D and 3D pipelines.\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),

    'visualization_utils': (
        'visualization_utils.py - Shared Plotly utilities for orrery and star visualizations.\n'
        '\n'
        'Interactive figure controls used by both plot_objects and animate_objects:\n'
        'hover toggle buttons, camera center/look-at/fly-to buttons, and the\n'
        'format_detailed_hover_text() builder for orrery object hover strings.\n'
        'Also contains _calculate_grid_dtick() for scale-aware axis tick spacing.\n'
        '\n'
        'Key functions:\n'
        '    format_detailed_hover_text() - Full hover string for orrery objects\n'
        '    add_hover_toggle_buttons() - Show/hide hover text toggle\n'
        '    add_fly_to_object_buttons() - Camera fly-to dropdown\n'
        '    _calculate_grid_dtick() - Auto-dtick from axis span\n'
        '\n'
        'Module updated: April 2026 with Anthropic\'s Claude Opus 4.6'
    ),
}


# ============================================================
# INSERTION LOGIC
# ============================================================

def detect_line_ending(content_bytes):
    """Detect whether file uses CRLF or LF."""
    if b'\r\n' in content_bytes:
        return b'\r\n'
    return b'\n'


def has_existing_docstring(content_bytes):
    """Check if file starts with a docstring (triple quotes)."""
    text = content_bytes.lstrip()
    return text.startswith(b'"""') or text.startswith(b"'''")


def has_leading_comment(content_bytes):
    """Check if file starts with # comments (before imports)."""
    text = content_bytes.lstrip()
    return text.startswith(b'#')


def insert_docstring(content_bytes, docstring_text, line_ending):
    """Insert docstring at the top of a file, before any existing content."""
    nl = line_ending
    doc_bytes = ('"""\n' + docstring_text + '\n"""').encode('utf-8')
    # Normalize newlines in the docstring to match the file
    doc_bytes = doc_bytes.replace(b'\r\n', b'\n').replace(b'\n', nl)

    stripped = content_bytes.lstrip()

    if has_existing_docstring(content_bytes):
        # Replace existing docstring
        # Find the closing triple-quote
        if stripped.startswith(b'"""'):
            quote = b'"""'
        else:
            quote = b"'''"

        # Find opening quote position in original content
        start = content_bytes.index(quote)
        # Find closing quote (skip the opening one)
        end = content_bytes.index(quote, start + 3) + 3

        # Check if there's a newline after the closing quote
        rest_start = end
        if rest_start < len(content_bytes) and content_bytes[rest_start:rest_start+2] == b'\r\n':
            rest_start += 2
        elif rest_start < len(content_bytes) and content_bytes[rest_start:rest_start+1] == b'\n':
            rest_start += 1

        return doc_bytes + nl + content_bytes[rest_start:]

    else:
        # Insert before existing content
        return doc_bytes + nl + content_bytes


def process_module(project_dir, module_name, docstring_text, write=False):
    """Process a single module: read, insert docstring, optionally write."""
    filepath = os.path.join(project_dir, module_name + '.py')
    if not os.path.exists(filepath):
        print(f"  SKIP {module_name}.py -- file not found")
        return False

    with open(filepath, 'rb') as f:
        content = f.read()

    line_ending = detect_line_ending(content)
    new_content = insert_docstring(content, docstring_text, line_ending)

    if new_content == content:
        print(f"  SKIP {module_name}.py -- no change needed")
        return False

    if write:
        with open(filepath, 'wb') as f:
            f.write(new_content)
        print(f"  WROTE {module_name}.py")
    else:
        # Preview: show first 5 lines of docstring
        preview = docstring_text.split('\n')[0]
        print(f"  PREVIEW {module_name}.py -- {preview}")

    return True


# ============================================================
# MAIN
# ============================================================

def main():
    write_mode = '--write' in sys.argv
    project_dir = '.'

    # Check for directory argument
    for arg in sys.argv[1:]:
        if arg != '--write' and os.path.isdir(arg):
            project_dir = arg

    mode_label = "WRITING" if write_mode else "PREVIEW (use --write to apply)"
    print(f"\n{'='*60}")
    print(f"  Module Docstring Update -- {mode_label}")
    print(f"  Target: {os.path.abspath(project_dir)}")
    print(f"  Modules to update: {len(DOCSTRINGS)}")
    print(f"{'='*60}\n")

    updated = 0
    skipped = 0
    for module_name, docstring_text in sorted(DOCSTRINGS.items()):
        if process_module(project_dir, module_name, docstring_text, write=write_mode):
            updated += 1
        else:
            skipped += 1

    print(f"\n  {'Updated' if write_mode else 'Would update'}: {updated}")
    print(f"  Skipped: {skipped}")
    print()


if __name__ == '__main__':
    main()
