#!/usr/bin/env python3
"""doc_index.py -- regenerate README.md's key-documents table from the
documents themselves.

ORRERY repo tool. Run it, or let orrery_maintenance_run.py run it.

    python doc_index.py            regenerate the table in README.md
    python doc_index.py --check    report only; exit 1 on any problem

WHY THIS EXISTS (L-273)
-----------------------
README.md's key-documents table was hand-maintained, and a
hand-maintained list of what is in a directory is a copy that drifts
from the directory. That drift is L-270: the README described a gallery
that no longer existed, and nobody could see it from inside the README.

Tony's proposal, 2026-08-31, and it is the right shape: not a checker
that alarms on the copy, but an INDEXER that regenerates it -- the way
skills_index.py writes the manifest into PROJECT_INSTRUCTIONS.md and
ledger_index.py writes the INDEX into LEDGER_CONSOLIDATED.md. Fix the
producer, not the consumer.

THE DESIGN: EACH DOCUMENT DECLARES ITSELF
-----------------------------------------
The purpose text lives in the document it describes, not in this tool
and not in the README. That is deliberate, and it is copied from
skills_index.py: its editorial column lives in each skill's own
frontmatter, so Tony keeps control of the wording while the target file
stays generated. A dict of descriptions inside this script would be the
shadow store that module_atlas.py already deleted when ROLE_MAP became a
regenerated mirror.

    Markdown:  <!-- Doc-Kind: <kind> | <one-line purpose> -->
    Text:      # Doc-Kind: <kind> | <one-line purpose>

The tag may sit anywhere in the first 40 lines. In markdown it is an
HTML comment, so it is invisible when GitHub renders the page.

THREE KINDS, AND THE DISTINCTION IS THE POINT
---------------------------------------------
    generated       written entirely by a tool. Hand-editing it is an
                    error: the next run destroys the edit.
    zoned           hand-written prose around a marker zone a tool
                    regenerates. Edit the prose, never the zone.
    hand            hand-written throughout.

Nothing in either repository recorded that distinction before, and the
only warning against hand-editing a generated file lived inside the file.

MARKERS MUST ALREADY EXIST
--------------------------
If README.md has no marker zone this reports and exits WITHOUT writing.
That is skills_index.py's behaviour rather than ledger_index.py's
fallback insert, and on purpose: guessing where a table belongs in a
prose document is worse than not writing one.

UNTAGGED DOCUMENTS ARE REPORTED, NEVER DROPPED
----------------------------------------------
A document with no tag still appears in the table, marked untagged, and
is named in the summary. Silence about something unexamined is the
failure mode this project has a gate for; a tidy table that quietly
omits what it could not read would be exactly that.

Role: devtool
Domain: dev_tools

Module created: September 1, 2026 with Anthropic's Claude Opus 5.
"""

import re
import sys
from pathlib import Path

START = '<!-- DOC-INDEX:START (generated by doc_index.py -- do not edit this zone by hand) -->'
END = '<!-- DOC-INDEX:END -->'

TAG_RE = re.compile(
    r'^\s*(?:<!--|#)\s*Doc-Kind:\s*([a-z-]+)\s*\|\s*(.+?)\s*(?:-->)?\s*$',
    re.MULTILINE)

KIND_LABEL = {
    'generated': 'generated',
    'zoned': 'hand + generated zone',
    'hand': 'hand-written',
}

KIND_ORDER = {'zoned': 0, 'hand': 1, 'generated': 2, '?': 3}

SCAN_SUFFIXES = ('.md', '.txt')
TAG_SCAN_LINES = 40


def read_tag(path):
    """Return (kind, purpose) or (None, None). Reads the head only."""
    try:
        with open(path, 'r', encoding='utf-8', errors='replace') as fh:
            head = ''.join(fh.readline() for _ in range(TAG_SCAN_LINES))
    except OSError as e:
        return None, 'UNREADABLE: %s' % e
    m = TAG_RE.search(head)
    if not m:
        return None, None
    kind = m.group(1).strip()
    return (kind if kind in KIND_LABEL else '?'), m.group(2).strip()


def collect(root):
    docs = []
    for p in sorted(root.iterdir()):
        if not p.is_file() or p.suffix.lower() not in SCAN_SUFFIXES:
            continue
        kind, purpose = read_tag(p)
        docs.append((p.name, kind, purpose))
    return docs


def render(docs):
    rows = [
        '| Document | Kind | What it is for |',
        '|---|---|---|',
    ]
    for name, kind, purpose in sorted(
            docs, key=lambda d: (KIND_ORDER.get(d[1] or '?', 3), d[0].lower())):
        label = KIND_LABEL.get(kind, '**untagged**')
        text = purpose or '_no Doc-Kind tag; add one to describe it here_'
        rows.append('| [%s](%s) | %s | %s |' % (name, name, label, text))
    return '\n'.join(rows)


def main():
    check_only = '--check' in sys.argv[1:]
    root = Path(__file__).resolve().parent
    readme = root / 'README.md'

    if not readme.is_file():
        print('CANNOT RUN: README.md not found in %s' % root)
        return 2

    docs = collect(root)
    untagged = [n for n, k, p in docs if k is None]
    unknown = [(n, p) for n, k, p in docs if k == '?']

    text = readme.read_text(encoding='utf-8')
    if START not in text or END not in text:
        print('CANNOT RUN: README.md has no DOC-INDEX marker zone.')
        print('  Expected these two lines, in this order:')
        print('    %s' % START)
        print('    %s' % END)
        print('  Nothing was written. Guessing an insertion point in a prose')
        print('  document is worse than not writing one.')
        return 2

    table = render(docs)
    new_zone = START + '\n' + table + '\n' + END
    pattern = re.compile(re.escape(START) + r'.*?' + re.escape(END), re.DOTALL)
    updated = pattern.sub(lambda _m: new_zone, text, count=1)

    changed = updated != text
    if changed and not check_only:
        with open(readme, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(updated)

    # ---- report: names, not only counts (A Report Names Its Items) ----
    by_kind = {}
    for name, kind, _p in docs:
        by_kind.setdefault(kind or 'untagged', []).append(name)

    print('%d root document(s) indexed:' % len(docs))
    for kind in ('zoned', 'hand', 'generated', '?', 'untagged'):
        names = by_kind.get(kind)
        if names:
            print('  %-22s %d  %s'
                  % (KIND_LABEL.get(kind, kind), len(names), ', '.join(names)))

    problems = 0
    if unknown:
        problems += len(unknown)
        print('')
        print('UNRECOGNISED Doc-Kind value (%d):' % len(unknown))
        for n, _p in unknown:
            print('    %s' % n)
        print('  Valid kinds: %s' % ', '.join(sorted(KIND_LABEL)))

    if untagged:
        print('')
        print('NO Doc-Kind TAG (%d): %s' % (len(untagged), ', '.join(untagged)))
        print('  These appear in the table marked untagged rather than being')
        print('  dropped from it. A document a tool could not read is the')
        print('  thing most worth saying out loud.')

    print('')
    if check_only:
        if changed:
            problems += 1
            print('STALE: README.md\'s table does not match the documents.')
            print('  Run: python doc_index.py')
        else:
            print('OK: README.md\'s table matches the %d root document(s).'
                  % len(docs))
        return 1 if problems else 0

    if changed:
        print('Document index regenerated (%d documents) in README.md.' % len(docs))
    else:
        print('Document index already matched all %d document(s).' % len(docs))
    return 0


if __name__ == '__main__':
    sys.exit(main())
