"""
earth_system_controller.py - KMZ layer selector for Google Earth Pro.

Simple Tkinter GUI that lets users browse, select, and open KMZ climate
data layers in Google Earth Pro. Layers are generated by
earth_system_generator.py and stored in the data/ directory.

Module updated: April 2026 with Anthropic's Claude Opus 4.6
Module updated: June 2026 with Anthropic's Claude Opus 4.8 -- optional
"--preload <prefix>" auto-loads data/<prefix>_*_blockbuster.kmz (e.g.
food_insecurity) so the food family opens pre-selected. One picker, no
duplicate controller; no flag = generic empty-list behavior unchanged.
"""
import tkinter as tk
from tkinter import filedialog, messagebox
import os
import sys
import glob
import subprocess
import platform

class MissionControlApp:
    def __init__(self, root, preload=None):
        self.root = root
        self.layer_files = []

        # Define default data path (script-relative so it works regardless of cwd)
        self.data_dir = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), 'data')

        # Optional preload: title/header reflect the scoped family when present
        label_map = {"food_insecurity": "Food Insecurity Layers"}
        header_text = "Earth System Visualization"
        title = "Paloma's Orrery: Earth System Controller"
        if preload:
            header_text = label_map.get(preload, preload + " Layers")
            title = title + " -- " + header_text

        self.root.title(title)
        self.root.geometry("500x350")

        # Header
        header = tk.Label(root, text=header_text, font=("Helvetica", 16, "bold"))
        header.pack(pady=15)

        # Requirement note
        req_label = tk.Label(root, text="Requires: Google Earth Pro (free download)", 
                             font=("Helvetica", 9, "italic"), fg="gray")
        req_label.pack()

        # Listbox
        self.listbox = tk.Listbox(root, selectmode=tk.MULTIPLE, width=60, height=8)
        self.listbox.pack(pady=5)

        # Buttons
        btn_frame = tk.Frame(root)
        btn_frame.pack(pady=10)

        self.btn_add = tk.Button(btn_frame, text="Add KML Layers", command=self.add_files, bg="#dddddd")
        self.btn_add.pack(side=tk.LEFT, padx=10)

        self.btn_clear = tk.Button(btn_frame, text="Clear List", command=self.clear_list, bg="#dddddd")
        self.btn_clear.pack(side=tk.LEFT, padx=10)

        self.btn_launch = tk.Button(root, text="LAUNCH SELECTED LAYERS", 
                                    command=self.launch_layers, 
                                    bg="#ffcccc", fg="darkred", font=("Helvetica", 12, "bold"))
        self.btn_launch.pack(pady=15, fill=tk.X, padx=50)

        self.status = tk.Label(root, text="Ready.", bd=1, relief=tk.SUNKEN, anchor=tk.W)
        self.status.pack(side=tk.BOTTOM, fill=tk.X)

        # Optional preload: auto-load the scoped KMZ family (e.g. food_insecurity)
        if preload:
            self.preload_layers(preload)

    def preload_layers(self, prefix):
        """Auto-populate the listbox with data/<prefix>_*_blockbuster.kmz.

        Single source for the food-family glob: the GUI's
        launch_food_insecurity_layers() and the dashboard's Food Insecurity
        Controller both delegate here via --preload, so the
        food_insecurity_*_blockbuster.kmz contract lives in one place. The
        generic (no-preload) controller still opens with an empty list.
        """
        pattern = os.path.join(self.data_dir, "%s_*_blockbuster.kmz" % prefix)
        matches = sorted(glob.glob(pattern))
        for f in matches:
            if f not in self.layer_files:
                self.layer_files.append(f)
                self.listbox.insert(tk.END, os.path.basename(f))
        if matches:
            self.listbox.select_set(0, tk.END)
            self.status.config(
                text="%d %s layer(s) preloaded." % (len(matches), prefix))
        else:
            hint_map = {"food_insecurity":
                        " -- run food_insecurity_generator.py to build one"}
            self.status.config(
                text="No %s_*_blockbuster.kmz found in data/.%s"
                     % (prefix, hint_map.get(prefix, "")))

    def add_files(self):
        filenames = filedialog.askopenfilenames(
            title="Select KML Layers",
            initialdir=self.data_dir, 
            filetypes=[("Google Earth Files", "*.kml *.kmz")]
        )
        for f in filenames:
            if f not in self.layer_files:
                self.layer_files.append(f)
                self.listbox.insert(tk.END, os.path.basename(f))
        
        self.status.config(text=f"{len(self.layer_files)} layers ready.")

    def clear_list(self):
        self.layer_files = []
        self.listbox.delete(0, tk.END)
        self.status.config(text="List cleared.")

    def launch_layers(self):
        selected_indices = self.listbox.curselection()
        if not selected_indices:
            files_to_launch = self.layer_files
        else:
            files_to_launch = [self.layer_files[i] for i in selected_indices]

        if not files_to_launch:
            messagebox.showwarning("No Layers", "Please add KML files first.")
            return

        self.status.config(text=f"Launching {len(files_to_launch)} layers...")
        for filepath in files_to_launch:
            self.open_file(filepath)

    def open_file(self, filepath):
        if platform.system() == 'Darwin':       
            subprocess.call(('open', filepath))
        elif platform.system() == 'Windows':    
            os.startfile(filepath)
        else:                                   
            subprocess.call(('xdg-open', filepath))

if __name__ == "__main__":
    # Optional: --preload <prefix> auto-loads data/<prefix>_*_blockbuster.kmz
    # (e.g. --preload food_insecurity). No flag = generic empty-list controller.
    preload = None
    if "--preload" in sys.argv:
        idx = sys.argv.index("--preload")
        if idx + 1 < len(sys.argv):
            preload = sys.argv[idx + 1]
    root = tk.Tk()
    app = MissionControlApp(root, preload=preload)
    root.mainloop()
