#!/usr/bin/env python3
"""
ledger_index.py - Generate the at-a-glance INDEX for the consolidated ledger.

The DETAIL blocks are the single source of truth. Each block is headed by:

    #### [L-016 | #6] Archive dead shell functions
    <!-- L:016 status:OPEN upd:- section:D.Structural flag: -->
    <narrative, verbatim>
    **Gap:** ...
    **Ref:** ...

This tool scans every such block and rewrites the per-section index tables
between the INDEX:START / INDEX:END markers -- nothing else is touched, so it
is safe to re-run (module_atlas.py pattern). It also runs a consistency check:
every index row has a detail block and vice versa, no duplicate L-numbers, no
block missing its metadata line.

Usage:
    python3 ledger_index.py LEDGER_CONSOLIDATED.md          # rewrite in place
    python3 ledger_index.py LEDGER_CONSOLIDATED.md --check   # report only, exit 1 on problems

Module updated: June 2026 with Anthropic's Claude Opus 4.8 (ledger index/detail split).
"""
import re
import sys
import pathlib

HEAD_RE = re.compile(r'^####\s*\[L-(\d+)(?:\s*\|\s*#?([\w.\-/]+))?\]\s*(.+?)\s*$')
META_RE = re.compile(r'^<!--\s*L:(\d+)\s+status:(\S+)\s+upd:(\S+)\s+section:(\S+)(?:\s+flag:(\S*))?\s*-->\s*$')
START = '<!-- INDEX:START (generated by ledger_index.py -- do not edit this zone by hand) -->'
END = '<!-- INDEX:END -->'

# Disposition -> needs-attention (gets the leading '!')
GAP_STATUS = {'OPEN', 'BLOCKED', 'PENDING-GATE'}
# Section display order (sections not listed sort to the end, alphabetically)
SECTION_ORDER = ['A', 'PENDING', 'D.Movement', 'D.Priority', 'D.Structural',
                 'D.Cosmetic', 'D.Feature-A', 'D.Feature-B', 'D.Feature-C',
                 'D.Parked', 'D.LooseEnd', 'E', 'G', 'H']


def parse_blocks(lines):
    """Return list of dicts (one per L-block) and a list of parse problems."""
    blocks, problems = [], []
    for i, line in enumerate(lines):
        m = HEAD_RE.match(line)
        if not m:
            continue
        lnum, alias, title = m.group(1), m.group(2), m.group(3).strip()
        meta = META_RE.match(lines[i + 1]) if i + 1 < len(lines) else None
        if not meta:
            problems.append(f"L-{lnum} ('{title}'): missing/malformed metadata line below the header")
            continue
        if meta.group(1) != lnum:
            problems.append(f"L-{lnum}: metadata L:{meta.group(1)} disagrees with header L-{lnum}")
        blocks.append({
            'L': lnum, 'alias': alias, 'title': title,
            'status': meta.group(2), 'upd': meta.group(3),
            'section': meta.group(4), 'flag': (meta.group(5) or '').strip(),
        })
    return blocks, problems


def check(blocks, problems):
    seen = {}
    for b in blocks:
        seen.setdefault(b['L'], []).append(b['title'])
    for lnum, titles in sorted(seen.items()):
        if len(titles) > 1:
            problems.append(f"L-{lnum}: duplicate handle used by {len(titles)} blocks: {titles}")
    return problems


def cell(s):
    """Make a string safe for a markdown table cell (escape the pipe)."""
    return s.replace('|', r'\|')


def fmt_disposition(b):
    s = b['status']
    return f"{s} [{b['flag']}]" if b['flag'] else s


def fmt_id(b):
    # ASCII, and pipe-free so it cannot break the table column count.
    return f"L-{b['L']} (#{b['alias']})" if b['alias'] else f"L-{b['L']}"


def build_index(blocks):
    by_section = {}
    for b in blocks:
        by_section.setdefault(b['section'], []).append(b)

    def sec_key(s):
        return (SECTION_ORDER.index(s) if s in SECTION_ORDER else len(SECTION_ORDER), s)

    out = [START, '', '## INDEX (generated -- status board; edit DETAIL blocks, then re-run ledger_index.py)', '']
    total = sum(len(v) for v in by_section.values())
    gaps = sum(1 for b in blocks if b['status'] in GAP_STATUS)
    out.append(f"*{total} live items; {gaps} need attention (`!`). Find an `L-0NN` handle (Ctrl+F in VS Code) "
               "to jump to any item; search `| ! |` to list every gap. See \"Using and maintaining this "
               "ledger\" above for details.*")
    out.append('')
    for sec in sorted(by_section, key=sec_key):
        rows = sorted(by_section[sec], key=lambda b: int(b['L']))
        out.append(f"### {sec}")
        out.append('| Gap | L# | Item | Disposition | Updated |')
        out.append('|:---:|----|------|-------------|---------|')
        for b in rows:
            gap = '!' if b['status'] in GAP_STATUS else ''
            out.append(f"| {gap} | {cell(fmt_id(b))} | {cell(b['title'])} | "
                       f"{cell(fmt_disposition(b))} | {b['upd']} |")
        out.append('')
    out.append(END)
    return '\n'.join(out)

def main():
    # Default: LEDGER_CONSOLIDATED.md in the same folder as this script.
    if len(sys.argv) < 2:
        default = pathlib.Path(__file__).parent / 'LEDGER_CONSOLIDATED.md'
        if default.exists():
            path = str(default)
            check_only = False
        else:
            print(__doc__)
            sys.exit(2)
    else:
        path = sys.argv[1]
        check_only = '--check' in sys.argv[2:]
    with open(path, encoding='utf-8') as f:
        text = f.read()
    lines = text.split('\n')

    blocks, problems = parse_blocks(lines)
    problems = check(blocks, problems)

    if problems:
        print("CONSISTENCY PROBLEMS:")
        for p in problems:
            print(f"  - {p}")
    else:
        print(f"OK: {len(blocks)} L-blocks parsed, no consistency problems.")

    if check_only:
        sys.exit(1 if problems else 0)

    index = build_index(blocks)
    if START in text and END in text:
        new = re.sub(re.escape(START) + r'.*?' + re.escape(END), index, text, flags=re.DOTALL)
    else:
        # First run: insert the index zone right after the first '---' separator.
        sep = text.find('\n---\n')
        cut = sep + len('\n---\n') if sep != -1 else len(text)
        new = text[:cut] + '\n' + index + '\n' + text[cut:]
    with open(path, 'w', encoding='utf-8') as f:
        f.write(new)
    print(f"Index regenerated ({len(blocks)} items) in {path}.")
    sys.exit(1 if problems else 0)


if __name__ == '__main__':
    main()
