#!/usr/bin/env python3
"""
ledger_index.py - Generate the at-a-glance INDEX for the consolidated ledger.

The DETAIL blocks are the single source of truth. Each block is headed by:

    #### [L-016 | #6] Archive dead shell functions
    <!-- L:016 status:OPEN upd:- section:D.Structural flag: rice:2/1/80/1 -->
    <narrative, verbatim>
    **Gap:** ...
    **Ref:** ...

This tool scans every such block and rewrites the per-section index tables
between the INDEX:START / INDEX:END markers -- nothing else is touched, so it
is safe to re-run (module_atlas.py pattern). It also runs a consistency check:
every index row has a detail block and vice versa, no duplicate L-numbers, no
block missing its metadata line.

On each run the tool also migrates any DONE block whose body contains
    **Gap:** none -- move to section C
by physically moving it (in L-number order) to the end of section C, just
before the '---' separator that opens section D. The metadata line is updated
to section:C. This keeps the full narrative in the archive and the live
backlog clean.

RICE scoring (adapted for Paloma's Orrery):
    Metadata field: rice:R/I/C/E (e.g., rice:3/2/80/1)
    Omit or use rice:- for unscored items.

    R (Reach/Value)   - Educational/visual value
                        3 = core experience, 2 = gallery quality,
                        1 = internal hygiene
    I (Impact)        - Magnitude of improvement
                        3 = new capability, 2 = meaningful,
                        1 = polish, 0.5 = marginal
    C (Confidence %)  - Scope clarity
                        100 = ready to build, 80 = mostly scoped,
                        50 = needs design, 25 = speculative
    E (Effort)        - Sessions to complete
                        0.5 = quick fix, 1 = one session,
                        2 = two sessions, 3 = three+

    Score = R x I x (C / 100) / E

    Items with scores are sorted descending within each section;
    unscored items follow, sorted by L-number.

Usage:
    python3 ledger_index.py LEDGER_CONSOLIDATED.md          # rewrite in place
    python3 ledger_index.py LEDGER_CONSOLIDATED.md --check   # report only, exit 1 on problems

Module updated: June 2026 with Anthropic's Claude Opus 4.6 (RICE scoring).
"""
import re
import sys
import pathlib

HEAD_RE = re.compile(r'^####\s*\[L-(\d+)(?:\s*\|\s*#?([\w.\-/]+))?\]\s*(.+?)\s*$')
META_RE = re.compile(r'^<!--\s*L:(\d+)\s+status:(\S+)\s+upd:(\S+)\s+section:(\S+)(?:\s+flag:(\S*))?(?:\s+rice:(\S*))?\s*-->\s*$')
START = '<!-- INDEX:START (generated by ledger_index.py -- do not edit this zone by hand) -->'
END = '<!-- INDEX:END -->'

# Trigger phrase that marks a DONE block ready for migration to section C
MIGRATE_TRIGGER = '**Gap:** none -- move to section C'

# Disposition -> needs-attention (gets the leading '!')
GAP_STATUS = {'OPEN', 'BLOCKED', 'PENDING-GATE'}
# Section display order (sections not listed sort to the end, alphabetically).
# Section C (closed/done) sorts last so the live backlog reads first.
SECTION_ORDER = ['A', 'B', 'D.Movement', 'D.Priority', 'D.Structural',
                 'D.Cosmetic', 'D.Feature-A', 'D.Feature-B', 'D.Feature-C',
                 'D.Parked', 'D.LooseEnd', 'E', 'G', 'H',
                 'W.Prep', 'W.Active', 'W.Deferred', 'C']

# Tag aliases: normalize legacy/variant section tags to the canonical letter.
SECTION_ALIASES = {'PENDING': 'B'}

# Descriptive titles mirroring the DETAIL '##'/'###' headers, so the index
# reads as a structural map rather than a column of bare letters.
SECTION_TITLES = {
    'A': 'A. Active Separate Tracks',
    'B': 'B. Pending Action (Tony-side)',
    'C': 'C. Reconciled -- Done (closed; for the record)',
    'D.Movement': 'D.Movement -- Movement track',
    'D.Priority': 'D.Priority -- Real bugs',
    'D.Structural': 'D.Structural -- Dead code / honest shells',
    'D.Cosmetic': 'D.Cosmetic -- Polish',
    'D.Feature-A': 'D.Feature-A -- Bucket A (near-term)',
    'D.Feature-B': 'D.Feature-B -- Bucket B (editorial)',
    'D.Feature-C': 'D.Feature-C -- Bucket C (architecture)',
    'D.Parked': 'D.Parked (Tony calls)',
    'D.LooseEnd': 'D.Loose end to reconcile',
    'E': 'E. AU-Convention Compliance',
    'G': 'G. Open Questions / Tony Calls',
    'H': 'H. Gallery / Studio Track',
    'W.Prep': 'W.Prep -- Web Publication prep (before Phase 0)',
    'W.Active': 'W.Active -- Web Publication active phase',
    'W.Deferred': 'W.Deferred -- Web Publication deferred (captured)',
}

# Sections always rendered in the index even when they have no items
# (so the standing structure is visible -- e.g. B. Pending Action).
ALWAYS_SHOW = {'B'}

# Marker that separates section C from section D in the ledger
SEC_D_MARKER = '\n---\n\n## D. RECONCILED LEDGER -- OPEN'


def parse_rice(rice_str):
    """Parse a rice:R/I/C/E string into (reach, impact, confidence, effort) or None.

    Returns a tuple of floats if all four components are present and valid,
    or None if the field is missing, '-', or malformed.
    Separator is '/' to allow decimal values (e.g., rice:3/2/80/0.5).
    """
    if not rice_str or rice_str == '-':
        return None
    parts = rice_str.split('/')
    if len(parts) != 4:
        return None
    try:
        r, i, c, e = float(parts[0]), float(parts[1]), float(parts[2]), float(parts[3])
        if e <= 0:
            return None  # division by zero guard
        return (r, i, c, e)
    except ValueError:
        return None


def compute_score(rice_tuple):
    """Compute RICE score: R x I x (C / 100) / E.  Returns float or None."""
    if rice_tuple is None:
        return None
    r, i, c, e = rice_tuple
    return r * i * (c / 100.0) / e


def fmt_score(score):
    """Format a RICE score for the index table."""
    if score is None:
        return '--'
    return f'{score:.1f}'


def parse_blocks(lines):
    """Return list of dicts (one per L-block) and a list of parse problems."""
    blocks, problems = [], []
    for i, line in enumerate(lines):
        m = HEAD_RE.match(line)
        if not m:
            continue
        lnum, alias, title = m.group(1), m.group(2), m.group(3).strip()
        meta = META_RE.match(lines[i + 1]) if i + 1 < len(lines) else None
        if not meta:
            problems.append(f"L-{lnum} ('{title}'): missing/malformed metadata line below the header")
            continue
        if meta.group(1) != lnum:
            problems.append(f"L-{lnum}: metadata L:{meta.group(1)} disagrees with header L-{lnum}")
        blocks.append({
            'L': lnum, 'alias': alias, 'title': title,
            'status': meta.group(2), 'upd': meta.group(3),
            'section': meta.group(4), 'flag': (meta.group(5) or '').strip(),
            'rice': parse_rice((meta.group(6) or '').strip()),
            'line': i,  # line index of the #### header
        })
    return blocks, problems


def check(blocks, problems):
    seen = {}
    for b in blocks:
        seen.setdefault(b['L'], []).append(b['title'])
    for lnum, titles in sorted(seen.items()):
        if len(titles) > 1:
            problems.append(f"L-{lnum}: duplicate handle used by {len(titles)} blocks: {titles}")
    return problems


def cell(s):
    """Make a string safe for a markdown table cell (escape the pipe)."""
    return s.replace('|', r'\|')


def fmt_disposition(b):
    s = b['status']
    return f"{s} [{b['flag']}]" if b['flag'] else s


def fmt_id(b):
    # ASCII, and pipe-free so it cannot break the table column count.
    return f"L-{b['L']} (#{b['alias']})" if b['alias'] else f"L-{b['L']}"


def build_index(blocks):
    # Group ALL blocks (including section C) by their canonical section,
    # normalizing tag aliases (e.g. PENDING -> B).
    by_section = {}
    for b in blocks:
        sec = SECTION_ALIASES.get(b['section'], b['section'])
        by_section.setdefault(sec, []).append(b)

    def sec_key(s):
        return (SECTION_ORDER.index(s) if s in SECTION_ORDER else len(SECTION_ORDER), s)

    # Summary counts are for the LIVE backlog (everything except closed C).
    open_blocks = [b for b in blocks
                   if SECTION_ALIASES.get(b['section'], b['section']) != 'C']
    closed_n = len(blocks) - len(open_blocks)

    out = [START, '', '## INDEX (generated -- status board; edit DETAIL blocks, then re-run ledger_index.py)', '']
    total = len(open_blocks)
    gaps = sum(1 for b in open_blocks if b['status'] in GAP_STATUS)
    scored = sum(1 for b in open_blocks if compute_score(b['rice']) is not None)
    out.append(f"*{total} live items; {gaps} need attention (`!`); {scored} RICE-scored; "
               f"{closed_n} closed (section C, listed last). "
               "Find an `L-0NN` handle (Ctrl+F in VS Code) "
               "to jump to any item; search `| ! |` to list every gap. See \"Using and maintaining this "
               "ledger\" above for details.*")
    out.append('')

    # Display every section that has items, plus any always-show section.
    display_secs = set(by_section) | ALWAYS_SHOW
    for sec in sorted(display_secs, key=sec_key):
        out.append(f"### {SECTION_TITLES.get(sec, sec)}")
        rows = by_section.get(sec, [])
        if not rows:
            out.append('')
            out.append('*(none currently)*')
            out.append('')
            continue
        # Sort: scored items first (by score descending), then unscored (by L-number)
        def sort_key(b):
            s = compute_score(b['rice'])
            if s is not None:
                return (0, -s, int(b['L']))  # scored first, highest score first
            return (1, 0, int(b['L']))       # unscored after, by L-number
        rows = sorted(rows, key=sort_key)
        out.append('| Gap | L# | Item | Disposition | Score | Updated |')
        out.append('|:---:|----|------|-------------|:-----:|---------|')
        for b in rows:
            gap = '!' if b['status'] in GAP_STATUS else ''
            score = fmt_score(compute_score(b['rice']))
            out.append(f"| {gap} | {cell(fmt_id(b))} | {cell(b['title'])} | "
                       f"{cell(fmt_disposition(b))} | {score} | {b['upd']} |")
        out.append('')
    out.append(END)
    return '\n'.join(out)


def extract_block_text(lines, start_line):
    """
    Extract the full text of one L-block starting at start_line (the #### header).
    A block ends just before the next #### header at the same or higher level,
    or at a ## section header, or end of file.
    Returns the block text (with trailing newline stripped) and the
    exclusive end line index.
    """
    end = start_line + 1
    while end < len(lines):
        # Stop at any new #### L-block header or any ## section header
        if HEAD_RE.match(lines[end]):
            break
        if re.match(r'^#{1,3}\s', lines[end]):
            break
        end += 1
    # Trim trailing blank lines from the block body
    while end > start_line + 1 and lines[end - 1].strip() == '':
        end -= 1
    return '\n'.join(lines[start_line:end]), end


def migrate_to_section_c(text, blocks):
    """
    Find all DONE blocks with MIGRATE_TRIGGER in their body that are NOT
    already in section C. Move them (in L-number order) to just before the
    SEC_D_MARKER, updating their metadata section tag to 'C'.
    Returns (new_text, count_migrated).
    """
    lines = text.split('\n')

    # Identify candidates: DONE, trigger present, not already section:C
    candidates = []
    for b in sorted(blocks, key=lambda x: int(x['L'])):
        if b['status'] != 'DONE':
            continue
        if b['section'] == 'C':
            continue
        # Check if trigger appears in the block body
        block_text, _ = extract_block_text(lines, b['line'])
        if MIGRATE_TRIGGER in block_text:
            candidates.append(b)

    if not candidates:
        return text, 0

    # Work bottom-up: remove blocks from highest line to lowest so indices stay valid
    removed_blocks = []  # list of (lnum, block_text_with_updated_meta)
    lines = text.split('\n')  # re-split fresh each time we modify

    for b in sorted(candidates, key=lambda x: int(x['L']), reverse=True):
        # Re-parse lines each iteration since we modify in place
        # Re-find the block's current line by scanning
        current_line = None
        for i, line in enumerate(lines):
            m = HEAD_RE.match(line)
            if m and m.group(1) == b['L']:
                current_line = i
                break
        if current_line is None:
            continue

        block_text, end_line = extract_block_text(lines, current_line)

        # Update metadata: section -> C
        block_text = re.sub(
            r'(<!--\s*L:' + b['L'] + r'\s+status:\S+\s+upd:\S+\s+section:)\S+',
            r'\g<1>C',
            block_text
        )

        removed_blocks.append((int(b['L']), block_text))

        # Remove from current position (include one trailing blank line if present)
        remove_end = end_line
        if remove_end < len(lines) and lines[remove_end].strip() == '':
            remove_end += 1
        del lines[current_line:remove_end]

    # Sort removed blocks by L-number ascending for insertion
    removed_blocks.sort(key=lambda x: x[0])

    # Re-join and find the insertion point (just before SEC_D_MARKER)
    text = '\n'.join(lines)
    insert_marker = SEC_D_MARKER
    idx = text.find(insert_marker)
    if idx == -1:
        # Fallback: shouldn't happen, but don't lose data
        print("WARNING: Could not find section D marker; migrated blocks appended at end of section C.")
        idx = len(text)
        insert_marker = ''

    # Build the insertion: each block separated by a blank line
    insertion = '\n\n' + '\n\n'.join(block_text for _, block_text in removed_blocks)

    text = text[:idx] + insertion + text[idx:]
    return text, len(removed_blocks)


def main():
    # Default: LEDGER_CONSOLIDATED.md in the same folder as this script.
    if len(sys.argv) < 2:
        default = pathlib.Path(__file__).parent / 'LEDGER_CONSOLIDATED.md'
        if default.exists():
            path = str(default)
            check_only = False
        else:
            print(__doc__)
            sys.exit(2)
    else:
        path = sys.argv[1]
        check_only = '--check' in sys.argv[2:]

    with open(path, encoding='utf-8') as f:
        text = f.read()
    lines = text.split('\n')

    blocks, problems = parse_blocks(lines)
    problems = check(blocks, problems)

    if problems:
        print("CONSISTENCY PROBLEMS:")
        for p in problems:
            print(f"  - {p}")
    else:
        print(f"OK: {len(blocks)} L-blocks parsed, no consistency problems.")

    if check_only:
        sys.exit(1 if problems else 0)

    # Pass 1: migrate DONE blocks with the trigger phrase to section C
    text, migrated = migrate_to_section_c(text, blocks)
    if migrated:
        print(f"Migrated {migrated} block(s) to section C.")
        # Re-parse after migration so the index reflects updated sections
        lines = text.split('\n')
        blocks, _ = parse_blocks(lines)

    # Pass 2: regenerate the index
    index = build_index(blocks)
    if START in text and END in text:
        new = re.sub(re.escape(START) + r'.*?' + re.escape(END), index, text, flags=re.DOTALL)
    else:
        sep = text.find('\n---\n')
        cut = sep + len('\n---\n') if sep != -1 else len(text)
        new = text[:cut] + '\n' + index + '\n' + text[cut:]

    with open(path, 'w', encoding='utf-8') as f:
        f.write(new)

    live_count = sum(1 for b in blocks if b['section'] != 'C')
    print(f"Index regenerated ({live_count} live items) in {path}.")
    sys.exit(1 if problems else 0)


if __name__ == '__main__':
    main()
