"""patch_L274_4_close_and_amend.py -- close L-274 and L-272, amend L-273.

RUN COMMAND
-----------
Run this LAST, after patch_L273_1_doc_index.py has succeeded. Save into
the ORRERY repo root, open in VS Code, click Run.

    python patch_L274_4_close_and_amend.py

WHAT IT DOES
------------
Six edits to LEDGER_CONSOLIDATED.md, all-or-nothing:

  L-274  amended, then closed. The block as written names mtime as THE
         cause. It was half. Closing it on a diagnosis the evidence has
         moved past would leave a wrong record behind a green checkmark.
  L-272  closed. The gallery README is pushed and served.
  L-273  amended. Built and working for eight of thirteen documents;
         stays OPEN for the generator half.

Only DETAIL blocks are edited. The INDEX is regenerated by
ledger_index.py inside the maintenance run.

WHY THE GUARD IS THE POST-L273 FINGERPRINT
------------------------------------------
patch_L273_1_doc_index.py prepends a Doc-Kind tag to
LEDGER_CONSOLIDATED.md, so the ledger's bytes change. This patch is
built against the ledger AS IT IS AFTER that patch has run. If it
reports BASE MOVED, run patch_L273_1_doc_index.py first.

WHAT IS PERMANENT
-----------------
The ledger edits. This script is one-shot; archive it into
documentation/ once it has run.

NO BACKUP FILE
--------------
Per safe-file-editing 1.10.

Role: patch
Domain: dev_tools

Module created: September 1, 2026 with Anthropic's Claude Opus 5.
"""

import hashlib
import os
import sys

LEDGER = "LEDGER_CONSOLIDATED.md"
LEDGER_MD5 = "f3e22d65b3405ab6e9ce52f9422c429c"

EDITS = []

# ---- L-274: status -> DONE ----
EDITS.append((
    "L-274 status",
    "<!-- L:274 status:OPEN upd:2026-09-01 section:A flag: rice:3/3/95/2 -->",
    "<!-- L:274 status:DONE upd:2026-09-01 section:A flag: rice:3/3/95/2 -->",
))

# ---- L-274: the closing record ----
EDITS.append((
    "L-274 closing record",
    """  gallery-cache-builder skill 1.4, Sibling directory semantics.
""",
    """  gallery-cache-builder skill 1.4, Sibling directory semantics.
- **CLOSED 2026-09-01. It was TWO independent bugs stacked, not one
  cause with a symptom, and the block above says otherwise.** The
  amendment is recorded rather than the block rewritten, because how the
  diagnosis was wrong is the useful part. Bug one: the age test selected
  nothing, because mtime is meaningless here. Bug two, underneath it and
  invisible until the first was fixed: the deletion could never have
  worked either. Fixing either alone would have changed nothing on
  screen. That is why patch 1 appeared to make things WORSE -- 70
  directories suddenly reported as unremovable -- when it had in fact
  given a six-week silence its first voice.
- **The second bug: Windows refuses to DELETE a read-only directory and
  happily RENAMES one.** Every directory in the served tree carries
  FILE_ATTRIBUTE_READONLY, set by OneDrive -- the live one included. The
  builder RENAMES the live tree (os.replace, five sites) and DELETES the
  siblings (shutil.rmtree, three sites). Same attribute, opposite
  outcome. The files inside are not read-only; only the directories are,
  which is exactly why rmtree deleted the contents and died at the first
  rmdir, always at raw/elements.
- **A Claude error worth keeping, because it is this project's own
  failure mode.** The attribute diagnostic printed READONLY IS THE CAUSE
  while its own instruction -- compare the control row against the stale
  rows -- showed every row identical, live directory included. The
  READING section tested for the flag being PRESENT, not for what
  DIFFERED. A conclusion that fires on presence cannot fail. Shipping a
  fix on that verdict would have been a citation over recalled data: it
  would have looked like a diagnosis and been a guess. What actually
  settled it was reading the deletion sites against the rename sites.
- **The fix: `_rmtree_force`**, rmtree with a callback that clears the
  read-only bit on the refused entry and retries, wired into all three
  deletion sites. It RETURNS the number of entries it had to clear, and
  the count is reported -- because a clean reap list cannot distinguish
  the fix working from the attribute never having mattered.
- **Tony's run, 2026-09-01, and every predicted signal fired.**
  `[RECOVER] removed retained data\\solar-system.prev (cleared read-only
  on 6 entries)` -- a line that had read "could not remove" since July.
  70 siblings reaped and named. 394 entries needed the read-only clear,
  about 5.6 per directory, matching the six the recover line had just
  demonstrated. The confirming run reports 4 siblings, none stale.
- **The result nobody predicted, and it is the real one: no new
  quarantine was minted.** The prior run ended with `[SWAP] stale
  data\\solar-system.prev (suspected file lock) -> quarantining as ...`;
  this one goes straight from the sweep to done. The quarantine
  mechanism exists BECAUSE .prev could not be deleted at run start. It
  can now, so the swap has nothing to quarantine. This did not clean up
  70 directories -- it switched off the thing producing them. The four
  survivors are historical and age out on their own.
- **Testing note.** The retry path was proven live rather than assumed:
  os.rmdir was forced to refuse each directory once, the way
  RemoveDirectory refuses a read-only one. Four refusals, count returned
  4, tree gone; a clean tree returns 0. Two of the checks Claude wrote
  this session failed first on Claude's own arithmetic and miscounting,
  which is the only evidence either of them could fail at all.
""",
))

# ---- L-272: closed ----
EDITS.append((
    "L-272 status",
    "<!-- L:272 status:OPEN upd:2026-08-31 section:A flag: rice:3/2/95/1 -->",
    "<!-- L:272 status:DONE upd:2026-09-01 section:A flag: rice:3/2/95/1 -->",
))

EDITS.append((
    "L-272 closing record",
    """- **Ref:** L-270 (the same pass); L-262 (the gallery runner); Check All
  Parallel Pipelines, resident protocol Part 3.
""",
    """- **Ref:** L-270 (the same pass); L-262 (the gallery runner); Check All
  Parallel Pipelines, resident protocol Part 3.
- **CLOSED 2026-09-01.** Pushed and confirmed against the live remote;
  the gallery repo now has a README for the first time. The closing
  condition this block named -- Tony confirming the push, because the
  orrery repo cannot see the gallery one -- is met.
""",
))

# ---- L-273: amended, stays open ----
EDITS.append((
    "L-273 build record",
    """- **Not a gate on anything.** General correctness work beside the
  delivery work, not in front of it.
""",
    """- **BUILT 2026-09-01 by `patch_L273_1_doc_index.py`, and it works.**
  `doc_index.py` regenerates README.md's key-documents table from a
  one-line `Doc-Kind` tag each document carries, wired into
  `orrery_maintenance_run.py` as a fifth generator. Eight documents
  tagged; thirteen indexed; `--check` mode reports staleness without
  writing. The hand-maintained table is gone. STAYS OPEN for the
  generator half below.
- **A correction to this block: it is THREE kinds, not two.** The scope
  paragraph above says five generated against seven hand-written.
  Measured, there is a third kind the two-way split had no room for, and
  it is the one most likely to be mishandled -- ZONED: hand-written prose
  around a marker zone a tool rewrites. README.md, PROJECT_INSTRUCTIONS.md
  and LEDGER_CONSOLIDATED.md are all zoned. The prose is yours to edit
  and the zone is not, and nothing recorded that before.
- **Verified rather than assumed, because it would have failed
  quietly:** a leading HTML comment in LEDGER_CONSOLIDATED.md and
  PROJECT_INSTRUCTIONS.md survives `ledger_index.py` and
  `skills_index.py`. Both are tool-written, and a tag destroyed on the
  next run would have been worse than no tag.
- **WHAT REMAINS, and it is deliberately visible rather than silent.**
  The five GENERATED documents are not tagged, because a tag written
  into them by hand is destroyed on their generator's next run. They
  appear in the table marked untagged and `doc_index.py` NAMES them on
  every run: DATA_INVENTORY.md, MODULE_ATLAS.md, MODULE_INDEX.md,
  PROVENANCE_AUDIT.md, WORKSHEET_CHECK.md. Closing this item means one
  line in each of `module_atlas.py` (which writes two of the five),
  `data_inventory.py`, `provenance_scanner.py` and `worksheet_checker.py`
  to emit the tag. The GALLERY repo's README wants the same tool with a
  different scan root, and is part of this item too.
- **The blind spot announcing itself is the design, not a shortfall.**
  A table that quietly omitted the five documents it could not read
  would be exactly the failure A Check That Cannot Fail Is Not Passing
  exists to prevent.
- **Not a gate on anything.** General correctness work beside the
  delivery work, not in front of it.
""",
))

EDITS.append((
    "L-273 upd date",
    "<!-- L:273 status:OPEN upd:2026-08-31 section:A flag: rice:3/3/85/3 -->",
    "<!-- L:273 status:OPEN upd:2026-09-01 section:A flag: rice:3/3/85/3 -->",
))


def fail(msg):
    print("")
    print("FAILURE: " + msg)
    print("NOTHING was written.")
    print("Undo is Discard Changes in GitHub Desktop.")
    sys.exit(1)


def read_norm(path):
    with open(path, "rb") as fh:
        raw = fh.read()
    return raw.replace(b"\r\n", b"\n"), b"\r\n" in raw


def main():
    if not os.path.isfile("PROJECT_INSTRUCTIONS.md"):
        fail("run this from the ORRERY repo root (the folder holding "
             "PROJECT_INSTRUCTIONS.md). Current folder: " + os.getcwd())
    if not os.path.isfile(LEDGER):
        fail(LEDGER + " not found in " + os.getcwd())

    content, was_crlf = read_norm(LEDGER)
    actual = hashlib.md5(content).hexdigest()
    if actual != LEDGER_MD5:
        fail("BASE MOVED. " + LEDGER + " fingerprints " + actual +
             ", expected " + LEDGER_MD5 + ".\n"
             "  This patch runs AFTER patch_L273_1_doc_index.py, which\n"
             "  prepends a Doc-Kind tag to this file. If that has not run,\n"
             "  run it first.")
    print("ok  base fingerprint matches (post L-273-1)" +
          (" [CRLF, normalised]" if was_crlf else ""))

    text = content.decode("utf-8", "strict")

    if "CLOSED 2026-09-01. It was TWO independent bugs" in text:
        fail("this patch has already run.")

    for label, old, new in EDITS:
        n = text.count(old)
        if n != 1:
            fail("anchor for %s appears %d times, expected exactly 1."
                 % (label, n))
    print("ok  %d/%d anchors found, each exactly once" % (len(EDITS), len(EDITS)))

    for label, old, new in EDITS:
        text = text.replace(old, new, 1)

    out = text.encode("utf-8")
    if was_crlf:
        out = out.replace(b"\n", b"\r\n")
    with open(LEDGER, "wb") as fh:
        fh.write(out)
    print("ok  wrote %s (%d bytes)" % (LEDGER, len(out)))

    # ---- verification: read back from disk ----
    back, _ = read_norm(LEDGER)
    got = back.decode("utf-8", "replace")
    problems = []
    for probe, why in (
            ("<!-- L:274 status:DONE", "L-274 not marked DONE"),
            ("<!-- L:272 status:DONE", "L-272 not marked DONE"),
            ("<!-- L:273 status:OPEN upd:2026-09-01", "L-273 not re-dated, or wrongly closed"),
            ("It was TWO independent bugs stacked", "L-274 amendment missing"),
            ("quarantine was minted", "L-274 result record missing"),
            ("it is THREE kinds, not two", "L-273 correction missing"),
            ("BUILT 2026-09-01 by `patch_L273_1_doc_index.py`", "L-273 build record missing")):
        if probe not in got:
            problems.append(why)
    for handle in ("272", "273", "274"):
        if got.count("<!-- L:" + handle + " status:") != 1:
            problems.append("L-" + handle + " metadata line is not present exactly once")

    if problems:
        print("")
        print("VERIFICATION FAILED after writing:")
        for p in problems:
            print("  - " + p)
        print("Undo is Discard Changes in GitHub Desktop.")
        sys.exit(1)

    print("ok  verified: L-274 DONE, L-272 DONE, L-273 amended and still OPEN")
    print("")
    print("patch applied. Three blocks changed:")
    print("  L-274  OPEN -> DONE   two bugs stacked; amended, then closed")
    print("  L-272  OPEN -> DONE   gallery README pushed and served")
    print("  L-273  amended, still OPEN -- built for 8 of 13 documents;")
    print("                         the generator half remains")
    print("")
    print("NEXT STEPS")
    print("  1. Run: python orrery_maintenance_run.py")
    print("     ledger_index.py regenerates the INDEX and migrates L-274")
    print("     and L-272 into the closed section.")
    print("  2. Commit and push.")


if __name__ == "__main__":
    main()
