"""
patch_L314_days_envelope.py - L-314 gains the sampling decision.

Run it:
    Save this file into the ORRERY repo root (beside
    LEDGER_CONSOLIDATED.md), open it in VS Code and click Run.

What it does, in LEDGER_CONSOLIDATED.md and nowhere else:

  1. Adds three bullets to L-314, after "What it changes for the
     visitor" and before "What it must not do":
       - a nightly SPOT value is the wrong sampler; fetch the day's
         ENVELOPE;
       - what makes this worth a viewer's attention, with the numbers
         measured 2026-09-12 against Shue and Jelinek;
       - what it may NOT say, which is that a CME did it.
  2. Moves the metadata comment's upd: date to 2026-09-12.

It writes ONLY the detail block. The INDEX zone is untouched and is
regenerated by ledger_index.py afterwards.

The guard fingerprints the ledger's text OUTSIDE the INDEX zone, with
line endings normalised (L-315). A chain that runs the indexer between
patches refuses otherwise, and this patch is meant to run in a chain.

FAILURE: any assert below fires and NOTHING is written.
Undo is Discard Changes in GitHub Desktop.

Module created: September 2026 with Anthropic's Claude Opus 5.

Role: devtool
Domain: dev_tools
"""

import hashlib
import os
import sys

TARGET = "LEDGER_CONSOLIDATED.md"
BASE_FINGERPRINT = "dcf38a128e8d30a2dc7d4d55bcbce6b7"

META_OLD = "<!-- L:314 status:OPEN upd:2026-09-10 section:A flag: rice:3/3/60/4 -->"
META_NEW = "<!-- L:314 status:OPEN upd:2026-09-12 section:A flag: rice:3/3/60/4 -->"

VISITOR_BULLET = """- **What it changes for the visitor.** The two shells breathe day to
  day; each hover carries the measured p, Bz, v_sw AND their timestamp,
  replacing the "model condition" line. The i-panel gains one sentence
  saying the shells are drawn for the solar wind as measured at the
  build time named in the hover.
"""

NEW_BULLETS = """- **A nightly SPOT value is the wrong sampler; fetch the day's
  ENVELOPE.** Decided 2026-09-12. A shock passage compresses the
  magnetosphere for HOURS. A build sampling once a day is most likely
  to miss exactly the event worth showing, and the viewer then sees a
  quiet magnetosphere on the day of a severe storm -- which is worse
  than showing no weather at all, because it is confidently wrong.
  SWPC publishes at cadence, so the builder takes the last 24 hours
  and stores the minimum, maximum and mean of each input and of the two
  derived standoffs. The shells draw at the mean; the hover carries the
  band. Show the Envelope, and it costs nothing over a spot value
  because the same fetch returns the series. A rolling history of those
  daily bands is a second exhibit for almost no extra work, and is NOT
  part of this item.
- **What makes this worth a viewer's attention** [measured 2026-09-12
  by evaluating Shue eq. 10 and Jelinek eq. 14 at the coefficient rows
  L-305 stores; not a literature claim]. Geostationary orbit sits at
  6.6 R_E and Earth's exhibit already serves it (`earth_geostationary`).
  At Dp = 10 nPa with Bz = -20 nT the magnetopause stands off at
  6.32 R_E -- INSIDE the satellites. Pressure alone barely does it: the
  exponent is -1/6.6, so a tenfold pressure jump moves the nose only 29
  percent, and at Bz = 0 it takes 36.6 nPa to reach geostationary
  against 7.5 nPa at Bz = -20 nT. Southward field is what lets the
  boundary in, and that asymmetry is the thing a static figure cannot
  teach and two live numbers can.
- **What it may NOT say: that a CME did it.** Attributing a compression
  to a coronal mass ejection rather than to a corotating interaction
  region is an ANALYSIS, not a measurement, and asserting it is the
  unsourced-attribution class -- the same one L-305 removed from the
  bow shock hover on 2026-09-12. What is publishable is what is
  measured and published: the solar wind at L1, and SWPC's Kp and
  G-scale storm level. "G3, measured" is sourced; "a CME hit" is not,
  absent an event catalogue that says so and an access route for it.
"""


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, TARGET)
    if not os.path.exists(path):
        print("ERROR: %s is not beside this script. Put this file in the "
              "orrery repo root and run it there. NOTHING was written."
              % TARGET)
        return 1

    raw = open(path, "rb").read()
    was_crlf = b"\r\n" in raw
    text = raw.decode("utf-8").replace("\r\n", "\n")

    try:
        a = text.index("<!-- INDEX:START")
        b = text.index("<!-- INDEX:END -->") + len("<!-- INDEX:END -->")
    except ValueError:
        print("ERROR: could not find the INDEX zone markers in %s. NOTHING "
              "was written." % TARGET)
        return 1
    outside = text[:a] + text[b:]
    actual = hashlib.md5(outside.encode("utf-8")).hexdigest()
    if actual != BASE_FINGERPRINT:
        print("ERROR: base moved. The ledger's text outside the INDEX zone "
              "hashes to")
        print("       %s; this patch was built against" % actual)
        print("       %s. NOTHING was written." % BASE_FINGERPRINT)
        print("       Undo is Discard Changes in GitHub Desktop.")
        return 1
    print("ok   base fingerprint matches (text outside the INDEX zone)%s"
          % (" [CRLF]" if was_crlf else ""))

    out = text
    for label, old, new in (
            ("L-314 metadata upd: 2026-09-10 -> 2026-09-12",
             META_OLD, META_NEW),
            ("three bullets added to L-314",
             VISITOR_BULLET, VISITOR_BULLET + NEW_BULLETS)):
        n = out.count(old)
        if n != 1:
            print("ANCHOR FAIL: %s matched %d times, expected 1. NOTHING was "
                  "written." % (label, n))
            return 1
        out = out.replace(old, new)
        print("ok   %s" % label)

    try:
        out.encode("ascii")
    except UnicodeEncodeError:
        # The ledger is UTF-8 and carries non-ASCII elsewhere; only the
        # text this patch ADDS has to be ASCII.
        added = NEW_BULLETS + META_NEW
        try:
            added.encode("ascii")
        except UnicodeEncodeError as exc:
            print("ANCHOR FAIL: added text is not ASCII (%s). NOTHING was "
                  "written." % exc)
            return 1
    print("ok   encoding gate: added text is ASCII")

    final = out.encode("utf-8")
    if was_crlf:
        final = final.replace(b"\n", b"\r\n")
    with open(path, "wb") as handle:
        handle.write(final)
    print("patch applied (%d bytes, was %d)" % (len(final), len(raw)))
    print("")
    print("NEXT: run ledger_index.py (Run button). It rewrites only the")
    print("      INDEX zone, which this patch did not touch. Expect")
    print("      \"OK: 317 L-blocks parsed, no consistency problems.\"")
    print("      Then commit and push.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
