# save_utils.py

"""
save_utils.py - Unified save/export for all Plotly visualizations.

Provides consistent HTML and image saving across all orrery modules, with
CDN or offline Plotly.js options, save dialogs, temp-file browser preview,
and automatic Object Encyclopedia overlay injection. Every HTML output
includes interactive info cards for objects matching info_dictionary.INFO.

Key functions:
    save_visualization() - Unified save with dialog/direct/temp modes
    show_and_save() - Preview in browser then offer save dialog
    save_html() - Simple direct save for scripts

Consumed by: palomas_orrery.py, all visualization modules, gallery_studio.py

Author: Tony Quintanilla / Paloma's Orrery
Module updated: May 2026 with Anthropic's Claude Opus 4.6
"""

import tkinter as tk
from tkinter import filedialog, messagebox
import os
import sys
import json
import re
import tempfile
import webbrowser
import threading
import platform

# Module-level state for remembering last save directory within session
_last_save_directory = None


def _get_initial_directory():
    """Get the initial directory for file dialogs.
    
    Returns the last used directory if available, otherwise Documents folder.
    """
    global _last_save_directory
    
    if _last_save_directory and os.path.isdir(_last_save_directory):
        return _last_save_directory
    
    # Default to Documents folder
    if platform.system() == 'Windows':
        docs = os.path.join(os.path.expanduser('~'), 'Documents')
    elif platform.system() == 'Darwin':  # macOS
        docs = os.path.join(os.path.expanduser('~'), 'Documents')
    else:  # Linux
        docs = os.path.expanduser('~')
    
    if os.path.isdir(docs):
        return docs
    return os.getcwd()


def _update_last_directory(file_path):
    """Update the remembered directory based on a saved file path."""
    global _last_save_directory
    if file_path:
        _last_save_directory = os.path.dirname(file_path)


def _is_main_thread():
    """Check if we're running in the main thread."""
    return threading.current_thread() is threading.main_thread()


def _is_macos():
    """Check if we're running on macOS."""
    return platform.system() == 'Darwin'


# =============================================================================
# OBJECT ENCYCLOPEDIA OVERLAY
# Injects interactive encyclopedia cards into every orrery HTML output.
# When trace names match entries in info_dictionary.INFO, an "i" button
# appears on hover/click, opening a card with the object's reference text.
# Always-on: no toggle. No-op when no matching INFO entries exist.
#
# The same overlay is independently generated by gallery_studio.py for
# its own HTML export pipeline (Studio strips and rebuilds the HTML wrapper,
# so it cannot reuse the orrery's injection). Both pipelines use the same
# visual design and interaction model.
#
# Added: May 2026 with Anthropic's Claude Opus 4.6
# =============================================================================

def _load_info_dictionary():
    """Load the INFO dictionary from info_dictionary.py.
    
    Returns:
        dict: The INFO dictionary, or empty dict if unavailable.
    """
    try:
        from info_dictionary import INFO
        return INFO
    except ImportError:
        try:
            _here = os.path.dirname(os.path.abspath(__file__))
            _candidates = [
                _here,
                os.path.join(_here, '..'),
                os.path.join(_here, '..', 'orrery'),
            ]
            for _cand in _candidates:
                _cand = os.path.normpath(_cand)
                if os.path.isfile(os.path.join(_cand, 'info_dictionary.py')):
                    if _cand not in sys.path:
                        sys.path.insert(0, _cand)
                    break
            from info_dictionary import INFO
            return INFO
        except ImportError:
            return {}


def _strip_plotting_suggestions(text):
    """Remove ***ALL CAPS*** plotting suggestion lines from INFO text.
    
    These lines (e.g. ***SET MANUAL SCALE TO 170 AU...***) are useful
    in the desktop GUI but not in exported HTML.
    
    Parameters:
        text: Raw INFO text string
    
    Returns:
        str: Text with plotting suggestions removed
    """
    lines = text.split('\n')
    filtered = []
    for line in lines:
        stripped = line.strip()
        # Match ***ALL CAPS + punctuation*** pattern
        if re.match(r'^\*\*\*[^a-z]+\*\*\*$', stripped):
            continue
        filtered.append(line)
    
    # Remove leading empty lines left after stripping
    while filtered and not filtered[0].strip():
        filtered.pop(0)
    
    return '\n'.join(filtered)


def _extract_encyclopedia(fig):
    """Extract encyclopedia entries for objects present in a Plotly figure.
    
    Scans trace names in the figure, matches against the INFO dictionary
    from info_dictionary.py, strips plotting suggestions, and returns a
    dict mapping object names to their encyclopedia text.
    
    Parameters:
        fig: Plotly figure object (or dict with 'data' key)
    
    Returns:
        dict: {object_name: filtered_info_text} for objects found in INFO
    """
    INFO = _load_info_dictionary()
    if not INFO:
        return {}
    
    # Handle both figure objects and dicts
    if hasattr(fig, 'data'):
        traces = fig.data
    else:
        traces = fig.get('data', [])
    
    # Collect all trace names
    trace_names = set()
    for trace in traces:
        if hasattr(trace, 'name'):
            name = trace.name
        else:
            name = trace.get('name', '')
        if name:
            trace_names.add(name)
    
    # Match against INFO keys
    encyclopedia = {}
    for name in trace_names:
        if name in INFO:
            raw = INFO[name]
            cleaned = _strip_plotting_suggestions(raw)
            if cleaned.strip():
                encyclopedia[name] = cleaned
    
    return encyclopedia


def _build_encyclopedia_overlay(encyclopedia):
    """Build HTML/CSS/JS for the encyclopedia card overlay.
    
    Generates a self-contained overlay with:
      - An "i" button that appears when an object is hovered/clicked
      - A card overlay showing the object's encyclopedia text
      - Keyboard dismiss (Escape) and click-outside dismiss
    
    Parameters:
        encyclopedia: dict {object_name: info_text} from _extract_encyclopedia
    
    Returns:
        str: Complete HTML block (style + elements + script) for injection,
             or empty string if encyclopedia is empty
    """
    if not encyclopedia:
        return ''
    
    # Serialize encyclopedia for embedding in JS
    enc_json = json.dumps(encyclopedia, separators=(',', ':'))
    
    return f"""
<!-- ===== OBJECT ENCYCLOPEDIA (injected by save_utils.py) ===== -->
<style>
  .enc-btn {{
    position: absolute;
    top: 12px;
    left: 12px;
    width: 32px;
    height: 32px;
    border-radius: 50%;
    border: 2px solid #475569;
    background: rgba(15, 23, 42, 0.85);
    color: #94a3b8;
    font-size: 18px;
    font-weight: 700;
    font-style: italic;
    font-family: Georgia, 'Times New Roman', serif;
    cursor: pointer;
    display: none;
    align-items: center;
    justify-content: center;
    z-index: 200;
    transition: all 0.2s ease;
    line-height: 1;
    padding: 0 0 2px 0;
  }}
  .enc-btn:hover {{
    border-color: #c9a84c;
    color: #c9a84c;
    background: rgba(15, 23, 42, 0.95);
  }}
  .enc-btn.visible {{ display: flex; }}

  .enc-overlay {{
    position: absolute;
    top: 0; left: 0; right: 0; bottom: 0;
    background: rgba(0, 0, 0, 0.6);
    z-index: 300;
    display: none;
    align-items: center;
    justify-content: center;
    padding: 20px;
  }}
  .enc-overlay.open {{ display: flex; }}

  .enc-card {{
    background: #0f172a;
    border: 1px solid #334155;
    border-radius: 12px;
    max-width: 560px;
    width: 100%;
    max-height: 80vh;
    display: flex;
    flex-direction: column;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.5);
  }}

  .enc-card-header {{
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 16px 20px 12px 20px;
    border-bottom: 1px solid #1e293b;
    flex-shrink: 0;
  }}

  .enc-card-title {{
    font-size: 20px;
    font-weight: 700;
    color: #f8fafc;
    letter-spacing: 0.5px;
  }}

  .enc-card-close {{
    width: 28px;
    height: 28px;
    border-radius: 6px;
    border: 1px solid #334155;
    background: transparent;
    color: #64748b;
    font-size: 16px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.15s;
    padding: 0;
  }}
  .enc-card-close:hover {{
    color: #f8fafc;
    border-color: #64748b;
  }}

  .enc-card-body {{
    padding: 16px 20px 20px 20px;
    overflow-y: auto;
    font-size: 14px;
    line-height: 1.65;
    color: #cbd5e1;
    white-space: pre-wrap;
    word-wrap: break-word;
    scrollbar-width: thin;
    scrollbar-color: #334155 transparent;
  }}
  .enc-card-body::-webkit-scrollbar {{ width: 5px; }}
  .enc-card-body::-webkit-scrollbar-track {{ background: transparent; }}
  .enc-card-body::-webkit-scrollbar-thumb {{
    background: #334155; border-radius: 3px;
  }}
</style>

<button class="enc-btn" id="enc-btn" title="Object encyclopedia">i</button>
<div class="enc-overlay" id="enc-overlay">
  <div class="enc-card">
    <div class="enc-card-header">
      <div class="enc-card-title" id="enc-title"></div>
      <button class="enc-card-close" id="enc-close">&#10005;</button>
    </div>
    <div class="enc-card-body" id="enc-body"></div>
  </div>
</div>

<script>
// ===== ENCYCLOPEDIA CARD =====
var _encData = {enc_json};
var _encCurrentName = null;
var _encLocked = false;

function encShowButton(name) {{
  var btn = document.getElementById('enc-btn');
  if (!btn) return;
  if (name && _encData[name]) {{
    _encCurrentName = name;
    btn.classList.add('visible');
  }} else {{
    if (!_encLocked) {{
      _encCurrentName = null;
      btn.classList.remove('visible');
    }}
  }}
}}

function encLock(name) {{
  var btn = document.getElementById('enc-btn');
  if (!btn) return;
  if (name && _encData[name]) {{
    _encCurrentName = name;
    _encLocked = true;
    btn.classList.add('visible');
  }} else {{
    _encLocked = false;
    _encCurrentName = null;
    btn.classList.remove('visible');
  }}
}}

function encHide() {{
  if (_encLocked) return;
  var btn = document.getElementById('enc-btn');
  if (btn) btn.classList.remove('visible');
}}

function encOpenCard() {{
  if (!_encCurrentName || !_encData[_encCurrentName]) return;
  document.getElementById('enc-title').textContent = _encCurrentName;
  document.getElementById('enc-body').textContent = _encData[_encCurrentName];
  document.getElementById('enc-overlay').classList.add('open');
}}

function encCloseCard() {{
  document.getElementById('enc-overlay').classList.remove('open');
}}

// Wire up button and overlay events (DOM-only, immediate)
document.addEventListener('DOMContentLoaded', function() {{
  var btn = document.getElementById('enc-btn');
  if (btn) btn.addEventListener('click', encOpenCard);

  var closeBtn = document.getElementById('enc-close');
  if (closeBtn) closeBtn.addEventListener('click', encCloseCard);

  var overlay = document.getElementById('enc-overlay');
  if (overlay) {{
    overlay.addEventListener('click', function(e) {{
      if (e.target === overlay) encCloseCard();
    }});
  }}

  document.addEventListener('keydown', function(e) {{
    if (e.key === 'Escape') encCloseCard();
  }});
}});

// Wire to Plotly events -- poll until Plotly finishes rendering
// (DOMContentLoaded fires before Plotly.newPlot completes, so
// the graph div exists but lacks the .on() method at that point)
(function _encWaitForPlotly() {{
  var plotDiv = document.querySelector('.plotly-graph-div');
  if (plotDiv && typeof plotDiv.on === 'function') {{
    plotDiv.on('plotly_click', function(data) {{
      var pt = data.points[0];
      var name = pt.data ? pt.data.name : '';
      encLock(name);
    }});
    plotDiv.on('plotly_hover', function(data) {{
      var pt = data.points[0];
      var name = pt.data ? pt.data.name : '';
      encShowButton(name);
    }});
    plotDiv.on('plotly_unhover', function() {{
      encHide();
    }});
  }} else {{
    setTimeout(_encWaitForPlotly, 100);
  }}
}})();
</script>
<!-- ===== END ENCYCLOPEDIA ===== -->
"""


def _inject_encyclopedia(fig, html_str):
    """Inject the encyclopedia overlay into a Plotly HTML string.
    
    Extracts encyclopedia entries matching trace names against INFO,
    builds the overlay HTML block, and injects it before </body>.
    Returns the HTML unchanged if no entries match.
    
    Parameters:
        fig: Plotly figure object (for trace name extraction)
        html_str: Complete HTML string from fig.to_html()
    
    Returns:
        str: HTML string with encyclopedia overlay injected (or unchanged)
    """
    encyclopedia = _extract_encyclopedia(fig)
    if not encyclopedia:
        return html_str
    
    overlay_block = _build_encyclopedia_overlay(encyclopedia)
    if not overlay_block:
        return html_str
    
    # Inject before </body>
    return html_str.replace('</body>', overlay_block + '\n</body>')


def _write_html(fig, file_path, offline=False, auto_play=False):
    """Write HTML file with appropriate settings and encyclopedia overlay.
    
    Generates the HTML string via fig.to_html(), injects the Object
    Encyclopedia overlay (if INFO entries match trace names), and writes
    the result to file. The encyclopedia is always-on -- no toggle needed.
    If no matching INFO entries exist, the output is identical to plain
    fig.write_html().
    
    Parameters:
        fig: Plotly figure object
        file_path: Output file path
        offline: If True, embed Plotly.js (~5MB + plot data). If False, use CDN (~10KB)
        auto_play: If True, start animations automatically
    """
    include_plotlyjs = True if offline else 'cdn'
    
    # Generate HTML string instead of writing directly
    html_str = fig.to_html(
        include_plotlyjs=include_plotlyjs,
        auto_play=auto_play,
        full_html=True,
        config={'displayModeBar': True}
    )
    
    # Inject encyclopedia overlay if INFO entries match trace names
    html_str = _inject_encyclopedia(fig, html_str)
    
    # Write with binary mode to preserve encoding
    with open(file_path, 'wb') as f:
        f.write(html_str.encode('utf-8'))


def save_visualization(fig, default_name, mode='dialog', output_path=None,
                       offline=False, auto_play=False, open_browser=False):
    """
    Unified save function for all Plotly visualizations.
    
    Parameters:
        fig: Plotly figure object
        default_name: Default filename without extension
        mode: Save mode
            - 'dialog': Show save dialog with format choice (default)
            - 'direct': Save directly to output_path, no dialog
            - 'temp': Save to temp file and open in browser (no permanent save)
        output_path: For 'direct' mode, the output file path
        offline: For 'direct' mode, whether to embed Plotly.js
        auto_play: Whether to auto-play animations
        open_browser: Whether to open the saved file in browser
    
    Returns:
        str or None: Path to saved file, or None if cancelled/failed
    """
    if mode == 'temp':
        return _save_temp_and_open(fig, auto_play)
    elif mode == 'direct':
        return _save_direct(fig, output_path, offline, auto_play, open_browser)
    else:  # mode == 'dialog'
        return _save_with_dialog(fig, default_name, auto_play, open_browser)


def _save_temp_and_open(fig, auto_play=False):
    """Save to temporary file and open in browser."""
    try:
        with tempfile.NamedTemporaryFile(suffix='.html', delete=False, mode='w') as tmp:
            temp_path = tmp.name
        
        # Use CDN for temp files (faster to create)
        _write_html(fig, temp_path, offline=False, auto_play=auto_play)
        webbrowser.open(f'file://{os.path.abspath(temp_path)}')
        print(f"Visualization opened in browser: {temp_path}")
        
        # Schedule cleanup after delay
        def cleanup():
            try:
                if os.path.exists(temp_path):
                    os.unlink(temp_path)
            except Exception as e:
                print(f"Note: Could not clean up temp file: {e}")
        
        timer = threading.Timer(30.0, cleanup)
        timer.daemon = True
        timer.start()
        
        return temp_path
        
    except Exception as e:
        print(f"Error creating temporary visualization: {e}")
        return None


def _save_direct(fig, output_path, offline=False, auto_play=False, open_browser=False):
    """Save directly to specified path without dialog."""
    if not output_path:
        print("Error: output_path required for direct mode")
        return None
    
    try:
        # Determine format from extension
        ext = os.path.splitext(output_path)[1].lower()
        
        if ext == '.html':
            _write_html(fig, output_path, offline=offline, auto_play=auto_play)
            print(f"Saved HTML to: {output_path}")
        elif ext in ['.png', '.jpg', '.jpeg', '.svg', '.pdf']:
            fig.write_image(output_path)
            print(f"Saved image to: {output_path}")
        else:
            # Default to HTML
            if not output_path.endswith('.html'):
                output_path += '.html'
            _write_html(fig, output_path, offline=offline, auto_play=auto_play)
            print(f"Saved HTML to: {output_path}")
        
        if open_browser and ext == '.html':
            webbrowser.open(f'file://{os.path.abspath(output_path)}')
        
        return output_path
        
    except ImportError:
        print("Error: kaleido package required for image export.")
        print("Install with: pip install kaleido")
        return None
    except Exception as e:
        print(f"Error saving visualization: {e}")
        return None


def _save_with_dialog(fig, default_name, auto_play=False, open_browser=False):
    """Save with interactive dialog for format selection."""
    
    # Check for macOS thread safety issue
    if _is_macos() and not _is_main_thread():
        print("Save dialog skipped (macOS thread safety)")
        print("Use File > Save As in your browser to save the visualization")
        return _save_temp_and_open(fig, auto_play)
    
    root = None
    saved_path = None
    
    try:
        # Create root window for dialogs
        root = tk.Tk()
        root.withdraw()
        root.attributes('-topmost', True)
        
        # Ask if user wants to save
        save_response = messagebox.askyesno(
            "Save Visualization",
            "Would you like to save this visualization?",
            parent=root
        )
        
        if not save_response:
            print("User chose not to save")
            return None
        
        # Format selection dialog
        format_window = tk.Toplevel(root)
        format_window.title("Save Format")
        format_window.attributes('-topmost', True)
        format_window.grab_set()
        
        # Center the window
        format_window.geometry("350x230")
        format_window.resizable(False, False)
        
        # Variable to store selection
        format_var = tk.StringVar(master=format_window, value="html_cdn")
        
        tk.Label(format_window, text="Choose save format:", 
                 font=('TkDefaultFont', 10, 'bold')).pack(pady=(15, 10))
        
        tk.Radiobutton(format_window, text="Interactive HTML - Standard (~10 KB + plot data, needs internet)",
                       variable=format_var, value="html_cdn", wraplength=280).pack(anchor='w', padx=20)
        tk.Radiobutton(format_window, text="Interactive HTML - Offline (~5 MB + plot data, works anywhere)",
                       variable=format_var, value="html_offline", wraplength=280).pack(anchor='w', padx=20)
        tk.Radiobutton(format_window, text="Static PNG image",
                       variable=format_var, value="png").pack(anchor='w', padx=20)
        
        # Result holder
        result = {'confirmed': False}
        
        def on_ok():
            result['confirmed'] = True
            format_window.destroy()
        
        def on_cancel():
            format_window.destroy()
        
        button_frame = tk.Frame(format_window)
        button_frame.pack(pady=20)
        tk.Button(button_frame, text="OK", command=on_ok, width=10).pack(side='left', padx=5)
        tk.Button(button_frame, text="Cancel", command=on_cancel, width=10).pack(side='left', padx=5)
        
        # Wait for dialog
        format_window.wait_window()
        
        if not result['confirmed']:
            print("User cancelled format selection")
            return None
        
        format_choice = format_var.get()
        initial_dir = _get_initial_directory()
        
        # File save dialog based on format
        if format_choice == "png":
            file_path = filedialog.asksaveasfilename(
                parent=root,
                initialdir=initial_dir,
                initialfile=f"{default_name}.png",
                defaultextension=".png",
                filetypes=[("PNG files", "*.png")]
            )
            if file_path:
                try:
                    print(f"Saving PNG to {file_path}...")
                    fig.write_image(file_path)
                    print("PNG saved successfully.")
                    _update_last_directory(file_path)
                    saved_path = file_path
                except ImportError:
                    messagebox.showerror(
                        "Missing Dependency",
                        "The kaleido package is required for PNG export.\n"
                        "Install with: pip install kaleido",
                        parent=root
                    )
                except Exception as e:
                    messagebox.showerror("Save Error", f"Error saving PNG:\n{str(e)}", parent=root)
        
        else:  # HTML (CDN or offline)
            offline = (format_choice == "html_offline")
            size_note = "~5 MB + plot data, works offline" if offline else "~10 KB + plot data, needs internet"
            
            file_path = filedialog.asksaveasfilename(
                parent=root,
                initialdir=initial_dir,
                initialfile=f"{default_name}.html",
                defaultextension=".html",
                filetypes=[("HTML files", "*.html")]
            )
            if file_path:
                try:
                    print(f"Saving HTML ({size_note}) to {file_path}...")
                    _write_html(fig, file_path, offline=offline, auto_play=auto_play)
                    print("HTML saved successfully.")
                    _update_last_directory(file_path)
                    saved_path = file_path
                    
                    if open_browser:
                        webbrowser.open(f'file://{os.path.abspath(file_path)}')
                        
                except Exception as e:
                    messagebox.showerror("Save Error", f"Error saving HTML:\n{str(e)}", parent=root)
        
        return saved_path
        
    except Exception as e:
        print(f"Error during save operation: {e}")
        if root:
            try:
                messagebox.showerror("Save Error", f"An error occurred:\n{str(e)}", parent=root)
            except:
                pass
        return None
    
    finally:
        try:
            if root:
                root.destroy()
        except:
            pass


def show_and_save(fig, default_name, auto_play=False):
    """
    Show visualization in browser, then offer save dialog.
    
    This is the recommended function for GUI applications that want to
    display the visualization immediately and optionally save it.
    
    Parameters:
        fig: Plotly figure object
        default_name: Default filename without extension
        auto_play: Whether to auto-play animations
    
    Returns:
        str or None: Path to saved file, or None if not saved
    """
    # Check for macOS thread safety issue
    if _is_macos() and not _is_main_thread():
        print("Opening in browser (save dialog skipped for macOS thread safety)")
        print("Use File > Save As in your browser to save")
        return _save_temp_and_open(fig, auto_play)
    
    temp_path = None
    root = None
    
    try:
        # First, create and display temp file
        with tempfile.NamedTemporaryFile(suffix='.html', delete=False, mode='w') as tmp:
            temp_path = tmp.name
        
        _write_html(fig, temp_path, offline=False, auto_play=auto_play)
        webbrowser.open(f'file://{os.path.abspath(temp_path)}')
        print("Visualization opened in browser")
        
        # Now offer save dialog
        saved_path = _save_with_dialog(fig, default_name, auto_play, open_browser=False)
        
        return saved_path
        
    except Exception as e:
        print(f"Error during show_and_save: {e}")
        import traceback
        traceback.print_exc()
        return None
    
    finally:
        # Schedule cleanup of temp file
        if temp_path:
            def cleanup():
                try:
                    if os.path.exists(temp_path):
                        os.unlink(temp_path)
                except:
                    pass
            
            timer = threading.Timer(30.0, cleanup)
            timer.daemon = True
            timer.start()


# =============================================================================
# LEGACY COMPATIBILITY FUNCTIONS
# These maintain backward compatibility with existing code
# =============================================================================

def save_plot(fig, default_name):
    """
    Legacy function for backward compatibility.
    
    Equivalent to save_visualization(fig, default_name, mode='dialog')
    
    Parameters:
        fig: Plotly figure object
        default_name: Default filename without extension
    
    Returns:
        bool: True if save was successful or user declined, False on error
    """
    result = save_visualization(fig, default_name, mode='dialog')
    # Return True if saved or user cancelled (not an error), False on error
    return result is not None or result is None  # Always True for backward compat


def handle_save(fig, default_name):
    """
    Legacy function for backward compatibility.
    
    Note: This function is deprecated. Use save_visualization() instead.
    """
    save_visualization(fig, default_name, mode='dialog')


# =============================================================================
# ANIMATION-SPECIFIC FUNCTION
# =============================================================================

def show_animation_safely(fig, default_name):
    """
    Show and optionally save an animation.
    
    This is a convenience wrapper for animations that sets auto_play=False
    (letting the user control playback) and handles the show+save flow.
    
    Parameters:
        fig: Plotly figure object with animation
        default_name: Default filename without extension
    
    Returns:
        str or None: Path to saved file, or None if not saved
    """
    return show_and_save(fig, default_name, auto_play=False)


# =============================================================================
# DIRECT SAVE HELPER (for scripts like Sgr A* modules)
# =============================================================================

def save_html(fig, filename, offline=False, open_browser=True):
    """
    Simple direct save for scripts that don't need dialogs.
    
    Parameters:
        fig: Plotly figure object
        filename: Output filename (will add .html if missing)
        offline: If True, embed Plotly.js for offline viewing
        open_browser: If True, open the file in browser after saving
    
    Returns:
        str: Path to saved file
    
    Example:
        from save_utils import save_html
        fig = create_my_figure()
        save_html(fig, "my_output", open_browser=True)
    """
    if not filename.endswith('.html'):
        filename += '.html'
    
    return save_visualization(
        fig, 
        os.path.splitext(filename)[0],
        mode='direct',
        output_path=filename,
        offline=offline,
        open_browser=open_browser
    )
