#!/usr/bin/env python3
"""
skills_index.py - Generate the Skill Manifest table in the project
instructions from the SKILL.md files in skills/.

The SKILL.md files are the single source of truth. Each one carries:

    ---
    name: agentic-pre-test
    description: Pre-delivery runtime test protocol for ...
    fires_when: BEFORE delivering complete files/agentic code; after ...
    ---
    ...
    Skill version: 1.0 | Cut from palomas_orrery @ b29ad3f8 | July 1, 2026

This tool scans every skills/*/SKILL.md, validates it, and rewrites the
manifest table between the SKILL-MANIFEST:START / SKILL-MANIFEST:END
markers in the protocol file -- nothing else is touched, so it is safe
to re-run (ledger_index.py / module_atlas.py pattern). It also runs a
consistency check: folder name matches frontmatter name, a version line
exists, no duplicate names, and every skill has a fires_when field
(missing fires_when falls back to the first sentence of description,
truncated, and is reported as a warning).

The fires_when frontmatter field is the editorial "Fires when" column of
the manifest: short trigger phrases, hand-tuned. It is ignored by the
Claude skill loader (which reads name/description) but read by this tool,
so Tony keeps editorial control of the manifest without hand-editing the
protocol file.

Target file resolution: with no argument, the tool targets
PROJECT_INSTRUCTIONS.md next to this script -- the single, standard-named
file that is always the current, live protocol. Versioned archival copies
(documentation/project_instructions_v3_31.md, ...) are historical record
only; this tool never reads or writes them by default. Pass a path to
target something else.

The manifest zone markers must already exist in the protocol file:

    <!-- SKILL-MANIFEST:START (generated by skills_index.py -- do not edit this zone by hand) -->
    <!-- SKILL-MANIFEST:END -->

If they are absent the tool reports and exits WITHOUT writing -- a wrong
guess at an insertion point in the protocol is worse than no write.
(Deliberate divergence from ledger_index.py, which has a fallback insert.)

Output format matches the hand-written v3.30 manifest exactly: ASCII,
fixed-width plain-text table, name column 29 chars, "Fires when" text at
column 34, wrapped at 79 with a 34-space continuation indent. Written
with LF line endings explicitly (newline='\\n') so a Windows run does not
CRLF-convert the protocol file -- a second deliberate divergence from the
recipe, noted here so it is not "fixed" away.

Usage:
    python3 skills_index.py                              # PROJECT_INSTRUCTIONS.md, rewrite in place
    python3 skills_index.py documentation/project_instructions_v3_31.md
    python3 skills_index.py --check                      # report only, exit 1 on problems, no write

Module created: July 2026 with Anthropic's Claude Fable 5 (L-097,
collegial relay; spec by Claude Opus 4.6, integrated by Tony).
"""
import re
import sys
import pathlib
import textwrap

SKILLS_DIRNAME = 'skills'
START = ('<!-- SKILL-MANIFEST:START '
         '(generated by skills_index.py -- do not edit this zone by hand) -->')
END = '<!-- SKILL-MANIFEST:END -->'

VERSION_RE = re.compile(r'^Skill version:\s*([0-9][0-9.]*)\b')
PROTOCOL_DEFAULT_NAME = 'PROJECT_INSTRUCTIONS.md'

# Manifest display order (mirrors SECTION_ORDER in ledger_index.py):
# the v3.30 manifest reads in workflow order, not alphabetical order.
# Skills not listed here sort after these, alphabetically -- so a brand-new
# skill still appears (loudly, at the bottom) before this list is updated.
SKILL_ORDER = [
    'orrery-coding-conventions',
    'safe-file-editing',
    'agentic-pre-test',
    'horizons-orbital-mechanics',
    'provenance-discipline',
    'earth-system-pipeline',
    'gallery-pipeline',
    'ledger-and-session-records',
]

# Table geometry, measured from the hand-written v3.30 manifest.
NAME_COL_WIDTH = 29   # name field, space-padded ("orrery-coding-conventions    ")
VER_COL_WIDTH = 5     # version field ("1.0  ")
TEXT_COL = NAME_COL_WIDTH + VER_COL_WIDTH   # fires-when text starts at col 34
WRAP_WIDTH = 79
FALLBACK_TRUNC = 60   # chars of description used when fires_when is absent


def parse_frontmatter(lines):
    """Parse simple 'key: value' YAML frontmatter between the first two
    '---' lines. Multi-line values continue on indented lines (the style
    used by the installed skills). Returns (dict, body_start_index) or
    (None, 0) if no frontmatter found.
    """
    if not lines or lines[0].strip() != '---':
        return None, 0
    fields = {}
    key = None
    for i in range(1, len(lines)):
        line = lines[i]
        if line.strip() == '---':
            return fields, i + 1
        m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$', line)
        if m:
            key = m.group(1)
            fields[key] = m.group(2).strip()
        elif key is not None and line.strip():
            # continuation line of the previous value
            fields[key] = (fields[key] + ' ' + line.strip()).strip()
    return None, 0  # never saw the closing '---'


def first_sentence(text, limit=FALLBACK_TRUNC):
    """First sentence of a description, truncated to ~limit chars (option
    (b) fallback when fires_when is absent)."""
    m = re.match(r'(.+?[.!?])(\s|$)', text)
    s = m.group(1) if m else text
    if len(s) > limit:
        s = s[:limit].rsplit(' ', 1)[0] + '...'
    return s


def parse_skill(skill_dir):
    """Parse one skills/<name>/SKILL.md.
    Returns (record_dict_or_None, [problems], [warnings])."""
    problems, warnings = [], []
    path = skill_dir / 'SKILL.md'
    if not path.is_file():
        return None, [f"{skill_dir.name}: no SKILL.md in folder"], warnings

    text = path.read_text(encoding='utf-8')
    lines = text.split('\n')
    fm, body_start = parse_frontmatter(lines)
    if fm is None:
        return None, [f"{skill_dir.name}: missing/unterminated frontmatter"], warnings

    name = fm.get('name', '').strip()
    if not name:
        problems.append(f"{skill_dir.name}: frontmatter has no 'name' field")
        name = skill_dir.name
    elif name != skill_dir.name:
        problems.append(f"{skill_dir.name}: frontmatter name '{name}' "
                        f"disagrees with folder name")

    version = None
    for line in lines[body_start:]:
        m = VERSION_RE.match(line)
        if m:
            version = m.group(1)
            break
    if version is None:
        problems.append(f"{name}: no 'Skill version: X.X | ...' line in body")
        version = '?'

    fires = fm.get('fires_when', '').strip()
    if not fires:
        desc = fm.get('description', '').strip()
        if desc:
            fires = first_sentence(desc)
            warnings.append(f"{name}: no fires_when field; falling back to "
                            f"truncated description (add fires_when: to the "
                            f"frontmatter for editorial control)")
        else:
            problems.append(f"{name}: no fires_when and no description")
            fires = '(no description)'

    if len(name) > NAME_COL_WIDTH - 1:
        warnings.append(f"{name}: name is {len(name)} chars; wider than the "
                        f"{NAME_COL_WIDTH - 1}-char name column, table will "
                        f"mis-align")

    return {'name': name, 'version': version, 'fires_when': fires}, problems, warnings


def check(records, problems):
    seen = {}
    for r in records:
        seen.setdefault(r['name'], 0)
        seen[r['name']] += 1
    for name, n in sorted(seen.items()):
        if n > 1:
            problems.append(f"{name}: duplicate skill name used by {n} folders")
    return problems


def sort_key(record):
    name = record['name']
    if name in SKILL_ORDER:
        return (0, SKILL_ORDER.index(name), name)
    return (1, 0, name)  # unknown skills after, alphabetically


def format_row(record):
    """One manifest row: name/version on the first line, fires_when wrapped
    at WRAP_WIDTH with continuation lines indented to TEXT_COL."""
    prefix = record['name'].ljust(NAME_COL_WIDTH) + record['version'].ljust(VER_COL_WIDTH)
    wrapped = textwrap.wrap(record['fires_when'],
                            width=WRAP_WIDTH - TEXT_COL,
                            break_long_words=False,
                            break_on_hyphens=False) or ['']
    out = [prefix + wrapped[0]]
    indent = ' ' * TEXT_COL
    out.extend(indent + w for w in wrapped[1:])
    return out


def build_manifest(records):
    out = [START,
           'Skill'.ljust(NAME_COL_WIDTH) + 'Ver'.ljust(VER_COL_WIDTH) + 'Fires when']
    for r in sorted(records, key=sort_key):
        out.extend(format_row(r))
    out.append(END)
    return '\n'.join(out)


def find_default_protocol(folder):
    """The standard-named, currently-live protocol file next to this
    script. Versioned archival copies (documentation/project_instructions_
    v3_31.md, ...) are historical record only -- this tool never targets
    them by default; pass one explicitly if you ever need to regenerate
    an archived copy's manifest for some reason."""
    candidate = folder / PROTOCOL_DEFAULT_NAME
    return candidate if candidate.is_file() else None


def main():
    here = pathlib.Path(__file__).parent
    args = [a for a in sys.argv[1:] if a != '--check']
    check_only = '--check' in sys.argv[1:]

    if args:
        target = pathlib.Path(args[0])
    else:
        target = find_default_protocol(here)
        if target is None:
            print(f"ERROR: {PROTOCOL_DEFAULT_NAME} not found next to "
                  "skills_index.py; pass the protocol file path explicitly.")
            sys.exit(2)

    skills_dir = here / SKILLS_DIRNAME
    if not skills_dir.is_dir():
        print(f"ERROR: {skills_dir} not found; run from the repo root.")
        sys.exit(2)

    records, problems, warnings = [], [], []
    for skill_dir in sorted(p for p in skills_dir.iterdir() if p.is_dir()):
        rec, probs, warns = parse_skill(skill_dir)
        problems.extend(probs)
        warnings.extend(warns)
        if rec:
            records.append(rec)
    problems = check(records, problems)

    if problems:
        print("CONSISTENCY PROBLEMS:")
        for p in problems:
            print(f"  - {p}")
    else:
        print(f"OK: {len(records)} skills parsed, no consistency problems.")
    for w in warnings:
        print(f"  WARNING: {w}")

    if check_only:
        # Also verify the target zone exists, since a missing zone blocks writes.
        text = target.read_text(encoding='utf-8')
        if START not in text or END not in text:
            print(f"  - {target.name}: SKILL-MANIFEST markers not found "
                  "(add them around the manifest table before first run)")
            problems.append('markers missing')
        sys.exit(1 if problems else 0)

    text = target.read_text(encoding='utf-8')
    if START not in text or END not in text:
        print(f"ERROR: SKILL-MANIFEST markers not found in {target.name}; "
              "not writing. Add these two lines around the manifest table:")
        print(f"  {START}")
        print(f"  {END}")
        sys.exit(2)

    manifest = build_manifest(records)
    new = re.sub(re.escape(START) + r'.*?' + re.escape(END),
                 lambda _m: manifest, text, flags=re.DOTALL)

    # LF enforced: the protocol file is LF in the repo; a Windows text-mode
    # write would CRLF-convert every line. newline='' preserves our '\n'.
    with open(target, 'w', encoding='utf-8', newline='') as f:
        f.write(new)

    print(f"Skill Manifest regenerated ({len(records)} skills) in {target.name}.")
    sys.exit(1 if problems else 0)


if __name__ == '__main__':
    main()
