#!/usr/bin/env python3
"""
skills_index.py - Generate the Skill Manifest table in the project
instructions from the SKILL.md files in skills/.

The SKILL.md files are the single source of truth. Each one carries:

    ---
    name: agentic-pre-test
    description: Pre-delivery runtime test protocol for ...
    fires_when: BEFORE delivering complete files/agentic code; after ...
    ---
    ...
    Skill version: 1.0 | Cut from palomas_orrery @ b29ad3f8 | July 1, 2026

This tool scans every skills/*/SKILL.md, validates it, and rewrites the
manifest table between the SKILL-MANIFEST:START / SKILL-MANIFEST:END
markers in the protocol file -- nothing else is touched, so it is safe
to re-run (ledger_index.py / module_atlas.py pattern). It also runs a
consistency check: folder name matches frontmatter name, a version line
exists, no duplicate names, and every skill has a fires_when field
(missing fires_when falls back to the first sentence of description,
truncated, and is reported as a warning). It also holds every header to
Anthropic's documented limits -- a name of at most 64 characters, only
lowercase letters, numbers and hyphens, never "anthropic" or "claude";
a description of at most 1024 characters; no XML tag in either -- and
warns on a body over Anthropic's 500-line guideline (L-417; the pages
and the date they were read are beside the constants below).
A skill over that guideline must open with a '## Contents' list of its
headings, and any skill's list must match its headings exactly (L-418).

The fires_when frontmatter field is the editorial "Fires when" column of
the manifest: short trigger phrases, hand-tuned. It is ignored by the
Claude skill loader (which reads name/description) but read by this tool,
so Tony keeps editorial control of the manifest without hand-editing the
protocol file.

Target file resolution: with no argument, the tool targets
PROJECT_INSTRUCTIONS.md next to this script -- the single, standard-named
file that is always the current, live protocol. Versioned archival copies
(documentation/project_instructions_v3_31.md, ...) are historical record
only; this tool never reads or writes them by default. Pass a path to
target something else.

The manifest zone markers must already exist in the protocol file:

    <!-- SKILL-MANIFEST:START (generated by skills_index.py -- do not edit this zone by hand) -->
    <!-- SKILL-MANIFEST:END -->

If they are absent the tool reports and exits WITHOUT writing -- a wrong
guess at an insertion point in the protocol is worse than no write.
(Deliberate divergence from ledger_index.py, which has a fallback insert.)

Output format matches the hand-written v3.30 manifest exactly: ASCII,
fixed-width plain-text table, name column 29 chars, "Fires when" text at
column 34, wrapped at 79 with a 34-space continuation indent. Written
with LF line endings explicitly (newline='\\n') so a Windows run does not
CRLF-convert the protocol file -- a second deliberate divergence from the
recipe, noted here so it is not "fixed" away.

Usage:
    python3 skills_index.py                              # PROJECT_INSTRUCTIONS.md, rewrite in place
    python3 skills_index.py documentation/project_instructions_v3_31.md
    python3 skills_index.py --check                      # report only, exit 1 on problems, no write

Module created: July 2026 with Anthropic's Claude Fable 5 (L-097,
collegial relay; spec by Claude Opus 4.6, integrated by Tony).

Module updated: October 2, 2026 with Anthropic's Claude Opus 5.5
(L-407: each skill's header is now also read as YAML, the way the
Settings uploader reads it, and a header YAML refuses -- or one with no
name or description as text -- is a CONSISTENCY PROBLEM naming the
skill. On 2026-10-02 Settings refused interactive-exhibit 1.10 for
"malformed YAML frontmatter" while this tool, reading the header by its
own looser rules, built the manifest from it without complaint. PyYAML
does the reading where it is installed; otherwise built-in rules check
the faults that occur in these headers -- a bare second line, ": " or
" #" inside an unquoted value, a value opening with a YAML indicator, an
unclosed quote -- and the output says which of the two read them.
orrery_maintenance_run.py runs this tool with --check as a checker, so
a bad header fails the run.)

Module updated: October 5, 2026 with Anthropic's Claude Opus 5.5
(L-417: Anthropic's documented header limits, read that day from the
Skills overview and the authoring best practices, are checked -- name
length, characters and reserved words, description length, no XML tag
-- and each one broken is a CONSISTENCY PROBLEM, so --check exits 1 and
the maintenance run's Skill headers row fails. A body over the 500-line
guideline is a warning. The description is measured as YAML reads it,
without a quoted value's quote marks. From a Claude Sonnet 5.5 session's
check of the same day, rebuilt to this project's patch rules and
without its near-the-limit warning, which rested on a chosen number.)

Module updated: October 5, 2026 with Anthropic's Claude Opus 5.5
(L-418: the contents check. A plain read of a long file shows its
start and end and leaves out its middle, so a long skill opens with a
list of its headings, and this compares the list with the headings item
by item, skipping fenced code. Six skills gained one the same day.)

Module updated: October 8, 2026 with Anthropic's Claude Opus 5.5
(L-418, the provenance-discipline split: two new checks and the read
plan. A skill folder may now hold reference files in references/,
opened only when the skill says to. Every file a SKILL.md names under
references/ must exist, and every file in the folder must be named by
it; nothing else may sit in a skill folder. A long file -- a SKILL.md or
a reference file over one read -- carries a READ PLAN as its first line
after the title, "Read this file in N parts: lines a-b, c-d, ...",
which this tool writes: run it after putting the seed line "Read this
file in parts." where the plan goes. --check fails on a part over one
read, on a line no part covers, on a seed not yet filled, and on a long
file with no plan unless its skill is on the named PLAN_NOT_YET list.
In write mode the tool rewrites every plan it finds before reading the
skills, and names each one it changed. Annotation examples are now also
read from reference files. A SKILL.md must not write another skill's
references/ path, because the check would read it as its own.)

Role: devtool
Domain: dev_tools
"""
import re
import sys
import pathlib
import textwrap

SKILLS_DIRNAME = 'skills'
START = ('<!-- SKILL-MANIFEST:START '
         '(generated by skills_index.py -- do not edit this zone by hand) -->')
END = '<!-- SKILL-MANIFEST:END -->'

VERSION_RE = re.compile(r'^Skill version:\s*([0-9][0-9.]*)\b')
PROTOCOL_DEFAULT_NAME = 'PROJECT_INSTRUCTIONS.md'

# Manifest display order (mirrors SECTION_ORDER in ledger_index.py):
# the v3.30 manifest reads in workflow order, not alphabetical order.
# Skills not listed here sort after these, alphabetically -- so a brand-new
# skill still appears (loudly, at the bottom) before this list is updated.
SKILL_ORDER = [
    'orrery-coding-conventions',
    'safe-file-editing',
    'agentic-pre-test',
    'horizons-orbital-mechanics',
    'provenance-discipline',
    'provenance-cross-check',
    'earth-system-pipeline',
    'gallery-pipeline',
    'ledger-and-session-records',
]

# Table geometry, measured from the hand-written v3.30 manifest.
NAME_COL_WIDTH = 29   # name field, space-padded ("orrery-coding-conventions    ")
VER_COL_WIDTH = 5     # version field ("1.0  ")
TEXT_COL = NAME_COL_WIDTH + VER_COL_WIDTH   # fires-when text starts at col 34
WRAP_WIDTH = 79
FALLBACK_TRUNC = 60   # chars of description used when fires_when is absent

# Anthropic's documented limits for a skill's header (L-417), read on
# 2026-10-05 from two pages: the Skills overview, section "Skill
# structure", and the authoring best practices, sections "YAML
# frontmatter requirements" and "Token budgets".
#   https://platform.claude.com/docs/en/agents-and-tools/agent-skills/overview
#   https://platform.claude.com/docs/en/agents-and-tools/agent-skills/best-practices
# The first four are rules, so breaking one is a CONSISTENCY PROBLEM and
# --check exits 1. The body length is guidance ("Keep SKILL.md body under
# 500 lines for optimal performance"), so it is a warning.
NAME_MAX_CHARS = 64
NAME_CHARS_RE = re.compile(r'[a-z0-9-]+')     # lowercase letters, numbers, hyphens
NAME_RESERVED_WORDS = ('anthropic', 'claude')
DESCRIPTION_MAX_CHARS = 1024
XML_TAG_RE = re.compile(r'<[A-Za-z/][^>]*>')  # neither field may hold an XML tag
BODY_GUIDELINE_LINES = 500

# One read of a file, measured (L-418). Two readers have been measured,
# and a read plan's parts must fit the smaller of each:
#   2026-10-06, the design session's file viewer: 16,000 characters,
#     taken from the start and the end, the middle cut silently.
#   2026-10-08, this build session's Read tool: the first 25,000 tokens
#     and no more, with a notice saying so. On provenance-discipline
#     2.26 that was lines 1 to 1,106, 55,748 characters. Its documented
#     line limit is 2,000 lines.
# So a part is at most 16,000 characters and at most 2,000 lines.
# Characters are counted with each line's newline.
READ_PART_MAX_CHARS = 16000
READ_PART_MAX_LINES = 2000
PLAN_SEED = 'Read this file in parts.'
PLAN_RE = re.compile(r'^Read this file in (\d+) parts?: lines (.+)\.$')
PLAN_ANY_RE = re.compile(r'^Read this file in ')
REFERENCES_DIRNAME = 'references'
REFERENCE_NAME_RE = re.compile(r'references/([A-Za-z0-9_.-]+\.md)')

# Long skills that have no read plan yet and get one at their next
# version, so that adding the line costs no extra reinstall now. Each is
# named in the --check output every run, so the list cannot be forgotten.
# A skill not on this list fails --check when it is long and has no plan.
PLAN_NOT_YET = [
    # Tony, 2026-10-08: these get their plans at their next version.
    # Each was under one read of the reader measured that day (about
    # 55,000 characters), so none is cut today.
    # gallery-cache-builder left on 2026-10-10 with its 1.8 (L-216).
    # interactive-exhibit left on 2026-10-10 with its 1.13 (L-429).
    'orrery-coding-conventions',
    'safe-file-editing',
]


def parse_frontmatter(lines):
    """Parse simple 'key: value' YAML frontmatter between the first two
    '---' lines. Multi-line values continue on indented lines (the style
    used by the installed skills). Returns (dict, body_start_index) or
    (None, 0) if no frontmatter found.
    """
    if not lines or lines[0].strip() != '---':
        return None, 0
    fields = {}
    key = None
    for i in range(1, len(lines)):
        line = lines[i]
        if line.strip() == '---':
            return fields, i + 1
        m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$', line)
        if m:
            key = m.group(1)
            fields[key] = m.group(2).strip()
        elif key is not None and line.strip():
            # continuation line of the previous value
            fields[key] = (fields[key] + ' ' + line.strip()).strip()
    return None, 0  # never saw the closing '---'


def check_header(lines, label, loose=None):
    """Read a skill's header the way the Settings uploader does: as YAML.

    Returns ([problems], how), how naming what read it. PyYAML reads it
    where it is installed. Without PyYAML, built-in rules check the
    faults these headers have actually had; they are narrower than YAML,
    and the report says so by naming them. L-407, 2026-10-02.
    """
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == '---':
            end = i
            break
    if end is None:
        return [f"{label}: header has no closing '---'"], 'no header'
    raw = lines[1:end]
    try:
        import yaml
    except ImportError:
        yaml = None
    if yaml is not None:
        try:
            data = yaml.safe_load('\n'.join(raw))
        except yaml.YAMLError as exc:
            first = ' '.join(str(exc).split())[:120]
            return [f"{label}: header is not valid YAML, so Settings will "
                    f"refuse the file ({first})"], 'PyYAML'
        problems = []
        if not isinstance(data, dict):
            problems.append(f"{label}: header is YAML but not a set of "
                            f"'key: value' lines")
        else:
            for key in ('name', 'description'):
                value = data.get(key)
                if not isinstance(value, str) or not value.strip():
                    problems.append(f"{label}: header has no {key} that "
                                    f"YAML reads as text")
            # A header can be valid YAML and still lose words: " #" in an
            # unquoted value starts a comment, and the rest of the line is
            # dropped without an error. provenance-discipline's
            # description was read as its first 200 characters that way
            # until 2026-10-02 (L-407).
            for key, raw_value in (loose or {}).items():
                value = data.get(key)
                if (isinstance(value, str) and raw_value[:1] not in ('"', "'")
                        and ' '.join(value.split()) != ' '.join(raw_value.split())):
                    problems.append(f"{label}: YAML reads {key} as only its "
                                    f"first {len(value)} characters of "
                                    f"{len(raw_value)} -- ' #' starts a "
                                    f"comment; quote the value")
        return problems, 'PyYAML'
    problems, entries = [], []
    for n, line in enumerate(raw, 2):
        if not line.strip():
            continue
        if line[0] in ' \t':
            if entries:
                entries[-1][1] += ' ' + line.strip()
            else:
                problems.append(f"{label}: header line {n} is indented "
                                f"with no key above it")
            continue
        m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*):(?: (.*))?$', line)
        if not m:
            problems.append(f"{label}: header line {n} is neither "
                            f"'key: value' nor indented, so YAML reads it "
                            f"as a broken key")
            continue
        entries.append([m.group(1), (m.group(2) or '').strip()])
    for key, value in entries:
        if value[:1] in ('"', "'"):
            if len(value) < 2 or value[-1] != value[0]:
                problems.append(f"{label}: {key} opens a quote it does not "
                                f"close")
            continue
        bad = None
        if ' #' in value:
            bad = ("' #' inside an unquoted value, which YAML reads as the "
                   "start of a comment")
        elif ': ' in value or value.endswith(':'):
            bad = "': ' inside an unquoted value"
        elif value[:1] and value[:1] in '[]{},&*!|>%@`#':
            bad = "an unquoted value starting with %r" % value[:1]
        elif value[:2] in ('- ', '? '):
            bad = "an unquoted value starting with %r" % value[:2]
        if bad:
            problems.append(f"{label}: {key} has {bad}; quote the value")
    keys = [e[0] for e in entries]
    for key in ('name', 'description'):
        if key not in keys:
            problems.append(f"{label}: header has no {key}")
    return problems, 'built-in rules (PyYAML is not installed)'


def first_sentence(text, limit=FALLBACK_TRUNC):
    """First sentence of a description, truncated to ~limit chars (option
    (b) fallback when fires_when is absent)."""
    m = re.match(r'(.+?[.!?])(\s|$)', text)
    s = m.group(1) if m else text
    if len(s) > limit:
        s = s[:limit].rsplit(' ', 1)[0] + '...'
    return s


def description_value(lines, body_start, loose):
    """The description as the Settings uploader reads it: the YAML value.

    The loose reader keeps a quoted value's quote marks, which would count
    two characters too many against the limit (provenance-discipline and
    earth-system-pipeline are quoted since L-407). PyYAML gives the value
    itself where it is installed; otherwise one pair of outer quotes is
    removed, and a double-quoted value's escaped quotes and backslashes
    are read as single characters, which covers how these headers quote.
    """
    try:
        import yaml
        data = yaml.safe_load('\n'.join(lines[1:body_start - 1]))
        value = data.get('description') if isinstance(data, dict) else None
        if isinstance(value, str):
            return value.strip()
    except Exception:
        pass
    raw = loose.get('description', '').strip()
    if len(raw) >= 2 and raw[0] == raw[-1] == '"':
        return raw[1:-1].replace('\\"', '"').replace('\\\\', '\\')
    if len(raw) >= 2 and raw[0] == raw[-1] == "'":
        return raw[1:-1].replace("''", "'")
    return raw


def skill_headings(lines, start):
    """(level, text) of every ## and ### heading from `start` on, skipping
    anything inside a fenced code block, where a '## ' line is an example
    and not a heading."""
    found, fence = [], False
    for line in lines[start:]:
        if line.lstrip().startswith('```'):
            fence = not fence
            continue
        if fence:
            continue
        m = re.match(r'^(##|###) (.+?)\s*$', line)
        if m:
            found.append((len(m.group(1)), m.group(2)))
    return found


def check_contents(lines, body_start, label, body_lines, problems):
    """A long skill opens with a contents list, and the list is true (L-418).

    A plain read of a long file shows its start and end and leaves out its
    middle, so the start is the one part every session sees. The contents
    list puts every section's name there. It is a copy of the headings,
    and a copy drifts, so this compares the two item by item: a skill over
    the 500-line guideline with no list, or any list that disagrees with
    the headings, is a CONSISTENCY PROBLEM. The list is the '## Contents'
    section: one '- ' line per ## heading and '  - ' per ### heading,
    worded exactly as the heading, in the same order.
    """
    heads = skill_headings(lines, body_start)
    has = (2, 'Contents') in heads
    if not has:
        if body_lines > BODY_GUIDELINE_LINES:
            problems.append(f"{label}: {body_lines} lines and no '## Contents' "
                            f"list; a skill over {BODY_GUIDELINE_LINES} lines "
                            f"opens with one (L-418)")
        return
    listed, inside, fence = [], False, False
    for line in lines[body_start:]:
        if line.lstrip().startswith('```'):
            fence = not fence
        if fence:
            continue
        if line.rstrip() == '## Contents':
            inside = True
            continue
        if inside and re.match(r'^##+ ', line):
            break
        if inside:
            m = re.match(r'^(  )?- (.+?)\s*$', line)
            if m:
                listed.append((3 if m.group(1) else 2, m.group(2)))
    actual = [h for h in heads if h != (2, 'Contents')]
    if listed == actual:
        return
    for n, (a, b) in enumerate(zip(listed, actual), 1):
        if a != b:
            problems.append(f"{label}: contents item {n} reads {a[1]!r}; the "
                            f"heading there is {b[1]!r}")
            return
    problems.append(f"{label}: the contents list has {len(listed)} items and "
                    f"the file {len(actual)} headings")


def file_lines(text):
    """A file's lines as a reader numbers them: a final newline does not
    make an empty last line."""
    lines = text.split('\n')
    if text.endswith('\n'):
        lines = lines[:-1]
    return lines


def size_of(lines):
    """Characters, each line counted with its newline."""
    return sum(len(line) + 1 for line in lines)


def is_long(lines):
    return (size_of(lines) > READ_PART_MAX_CHARS
            or len(lines) > READ_PART_MAX_LINES)


def plan_line_index(lines):
    """Index of the read plan line, or its seed, or None. Only the first
    twenty lines are looked at: a plan is only any use at the top, inside
    the part every read shows."""
    for i, line in enumerate(lines[:20]):
        if PLAN_ANY_RE.match(line):
            return i
    return None


def compute_parts(lines):
    """Split a file into parts that each fit one read (L-418).

    Each part is at most READ_PART_MAX_CHARS characters and
    READ_PART_MAX_LINES lines. It ends just before a heading where one
    falls inside it, else just before a blank line, else where the limit
    falls; never inside fenced code unless no other place exists.
    Returns [(first, last)], 1-based and inclusive.
    """
    headings, blanks, fence = set(), set(), False
    for i, line in enumerate(lines):
        if line.lstrip().startswith('```'):
            fence = not fence
            continue
        if fence:
            continue
        if re.match(r'^#{1,4} ', line):
            headings.add(i)
        elif not line.strip():
            blanks.add(i)
    parts, start, n = [], 0, len(lines)
    while start < n:
        chars, end = 0, start
        while (end < n and end - start < READ_PART_MAX_LINES
               and chars + len(lines[end]) + 1 <= READ_PART_MAX_CHARS):
            chars += len(lines[end]) + 1
            end += 1
        if end >= n:
            parts.append((start + 1, n))
            break
        if end == start:          # one line longer than a read; the check names it
            end = start + 1
        # A heading is the best place to end a part, but not at the cost
        # of a part less than half full: then a blank line is used.
        half = start + (end - start) // 2
        cut = max((c for c in headings if half < c <= end), default=None)
        if cut is None:
            cut = max((c for c in blanks if start < c <= end), default=None)
        if cut is None:
            cut = end
        parts.append((start + 1, cut))
        start = cut
    return parts


def plan_text(parts):
    spans = ', '.join('%d-%d' % p for p in parts)
    word = 'part' if len(parts) == 1 else 'parts'
    return f"Read this file in {len(parts)} {word}: lines {spans}."


def write_read_plan(path):
    """Rewrite the read plan in a file that has one (or its seed). The
    plan is one line, so writing it moves no other line; it is computed
    again until it no longer changes, since its own length counts in the
    first part. Returns the plan written, or None when nothing changed
    or the file has no plan line."""
    text = path.read_text(encoding='utf-8')
    lines = file_lines(text)
    i = plan_line_index(lines)
    if i is None:
        return None
    for _ in range(5):
        new = plan_text(compute_parts(lines))
        if lines[i] == new:
            break
        lines[i] = new
    out = '\n'.join(lines) + ('\n' if text.endswith('\n') else '')
    if out == text:
        return None
    with open(path, 'w', encoding='utf-8', newline='') as f:
        f.write(out)
    return lines[i]


def read_plan_problems(lines, label, required):
    """Check one file's read plan (L-418). Returns ([problems], summary).

    A plan must name parts that start at line 1, follow on with no gap
    and no overlap, end at the file's last line, and each fit one read.
    A seed not yet filled fails. A long file with no plan fails when
    `required`. summary is the text --check prints for a file that passes,
    so a pass carries what was compared.
    """
    problems = []
    i = plan_line_index(lines)
    if i is None:
        if is_long(lines) and required:
            problems.append(
                f"{label}: {size_of(lines):,} characters in {len(lines)} lines "
                f"and no read plan; a file longer than one read "
                f"({READ_PART_MAX_CHARS:,} characters or "
                f"{READ_PART_MAX_LINES:,} lines) opens with one (L-418)")
        return problems, None
    line = lines[i]
    if line == PLAN_SEED:
        return [f"{label}: the read plan is still the seed; run "
                f"skills_index.py to write it"], None
    m = PLAN_RE.match(line)
    if not m:
        return [f"{label}: read plan line does not parse: {line!r}"], None
    spans = []
    for item in m.group(2).split(','):
        sm = re.fullmatch(r'\s*(\d+)-(\d+)\s*', item)
        if not sm:
            return [f"{label}: read plan part {item.strip()!r} is not "
                    f"'first-last'"], None
        spans.append((int(sm.group(1)), int(sm.group(2))))
    if int(m.group(1)) != len(spans):
        problems.append(f"{label}: read plan says {m.group(1)} parts and "
                        f"lists {len(spans)}")
    expected, n = 1, len(lines)
    for k, (a, b) in enumerate(spans, 1):
        if a > expected:
            problems.append(f"{label}: lines {expected}-{a - 1} are in no "
                            f"part of the read plan")
        elif a < expected:
            problems.append(f"{label}: read plan part {k} starts at line {a}, "
                            f"inside the part before it")
        if b < a:
            problems.append(f"{label}: read plan part {k} ends before it "
                            f"starts ({a}-{b})")
        if b > n:
            problems.append(f"{label}: read plan part {k} ends at line {b}; "
                            f"the file has {n}")
        chunk = lines[a - 1:min(b, n)]
        if size_of(chunk) > READ_PART_MAX_CHARS or len(chunk) > READ_PART_MAX_LINES:
            problems.append(f"{label}: read plan part {k} (lines {a}-{b}) is "
                            f"{size_of(chunk):,} characters in {len(chunk)} "
                            f"lines; one read is {READ_PART_MAX_CHARS:,} "
                            f"characters and {READ_PART_MAX_LINES:,} lines")
        expected = max(expected, b + 1)
    if expected <= n:
        problems.append(f"{label}: lines {expected}-{n} are in no part of "
                        f"the read plan")
    return problems, f"{label} {len(spans)} part{'' if len(spans) == 1 else 's'}"


def check_references(skill_dir, text, problems):
    """Every reference file named and present, and nothing else in the
    folder (L-418). Today a pointer to a missing file would pass silently,
    because only SKILL.md was read. Returns the reference files present."""
    label = skill_dir.name
    named = set(REFERENCE_NAME_RE.findall(text))
    present = []
    for p in sorted(skill_dir.iterdir()):
        if p.name == 'SKILL.md':
            continue
        if p.is_dir() and p.name == REFERENCES_DIRNAME:
            for q in sorted(p.iterdir()):
                if q.is_file() and q.suffix == '.md':
                    present.append(q)
                else:
                    problems.append(f"{label}: {REFERENCES_DIRNAME}/{q.name} "
                                    f"is not a .md file")
            continue
        problems.append(f"{label}: {p.name} sits in the skill folder; only "
                        f"SKILL.md and {REFERENCES_DIRNAME}/ may")
    names = {q.name for q in present}
    for n in sorted(named - names):
        problems.append(f"{label}: SKILL.md names {REFERENCES_DIRNAME}/{n}, "
                        f"which is not in the folder")
    for n in sorted(names - named):
        problems.append(f"{label}: {REFERENCES_DIRNAME}/{n} is in the folder "
                        f"and SKILL.md never names it")
    return present


def check_install_limits(name, desc, label, body_lines, problems, warnings):
    """Anthropic's documented header limits (L-417), checked here so that a
    skill which breaks one fails the maintenance run before it is pushed or
    reinstalled, instead of being refused by Settings afterwards. The
    limits and where they were read are the constants above.
    """
    if len(name) > NAME_MAX_CHARS:
        problems.append(f"{label}: name is {len(name)} characters; Anthropic's "
                        f"limit is {NAME_MAX_CHARS}")
    if not NAME_CHARS_RE.fullmatch(name):
        problems.append(f"{label}: name '{name}' may hold only lowercase "
                        f"letters, numbers and hyphens")
    for word in NAME_RESERVED_WORDS:
        if word in name:
            problems.append(f"{label}: name contains '{word}', a word "
                            f"Anthropic reserves")
    if len(desc) > DESCRIPTION_MAX_CHARS:
        problems.append(f"{label}: description is {len(desc)} characters; "
                        f"Anthropic's limit is {DESCRIPTION_MAX_CHARS}")
    for field, value in (('name', name), ('description', desc)):
        tag = XML_TAG_RE.search(value)
        if tag:
            problems.append(f"{label}: {field} holds an XML tag, "
                            f"{tag.group(0)!r}, which Anthropic disallows")
    if body_lines > BODY_GUIDELINE_LINES:
        warnings.append(f"{label}: SKILL.md body is {body_lines} lines; "
                        f"Anthropic's guideline is under "
                        f"{BODY_GUIDELINE_LINES}")


def parse_skill(skill_dir):
    """Parse one skills/<name>/SKILL.md.
    Returns (record_dict_or_None, [problems], [warnings])."""
    problems, warnings = [], []
    path = skill_dir / 'SKILL.md'
    if not path.is_file():
        return None, [f"{skill_dir.name}: no SKILL.md in folder"], warnings

    text = path.read_text(encoding='utf-8')
    lines = text.split('\n')
    fm, body_start = parse_frontmatter(lines)
    if fm is None:
        return None, [f"{skill_dir.name}: missing/unterminated frontmatter"], warnings
    header_problems, header_how = check_header(lines, skill_dir.name, fm)
    problems.extend(header_problems)

    name = fm.get('name', '').strip()
    if not name:
        problems.append(f"{skill_dir.name}: frontmatter has no 'name' field")
        name = skill_dir.name
    elif name != skill_dir.name:
        problems.append(f"{skill_dir.name}: frontmatter name '{name}' "
                        f"disagrees with folder name")

    # L-417: Anthropic's documented limits on the header, and the body's
    # length against its guideline. A file ending in a newline splits to
    # one empty last item, which is not a line.
    body_lines = len(lines) - body_start - (1 if text.endswith('\n') else 0)
    check_install_limits(name, description_value(lines, body_start, fm),
                         skill_dir.name, body_lines, problems, warnings)
    check_contents(lines, body_start, skill_dir.name, body_lines, problems)

    # L-418: reference files, and a read plan on every long file.
    plans = []
    on_list = skill_dir.name in PLAN_NOT_YET
    probs, summary = read_plan_problems(file_lines(text),
                                        f"{skill_dir.name}/SKILL.md",
                                        required=not on_list)
    problems.extend(probs)
    if summary:
        plans.append(summary)
        if on_list:
            problems.append(f"{skill_dir.name}: has a read plan and is still "
                            f"on PLAN_NOT_YET; take it off the list")
    elif on_list and is_long(file_lines(text)):
        warnings.append(f"{skill_dir.name}: long and no read plan yet; on "
                        f"PLAN_NOT_YET, so it gets one at its next version")
    for ref in check_references(skill_dir, text, problems):
        ref_lines = file_lines(ref.read_text(encoding='utf-8'))
        probs, summary = read_plan_problems(
            ref_lines, f"{skill_dir.name}/{REFERENCES_DIRNAME}/{ref.name}",
            required=True)
        problems.extend(probs)
        if summary:
            plans.append(summary)

    version = None
    for line in lines[body_start:]:
        m = VERSION_RE.match(line)
        if m:
            version = m.group(1)
            break
    if version is None:
        problems.append(f"{name}: no 'Skill version: X.X | ...' line in body")
        version = '?'

    fires = fm.get('fires_when', '').strip()
    if not fires:
        desc = fm.get('description', '').strip()
        if desc:
            fires = first_sentence(desc)
            warnings.append(f"{name}: no fires_when field; falling back to "
                            f"truncated description (add fires_when: to the "
                            f"frontmatter for editorial control)")
        else:
            problems.append(f"{name}: no fires_when and no description")
            fires = '(no description)'

    if len(name) > NAME_COL_WIDTH - 1:
        warnings.append(f"{name}: name is {len(name)} chars; wider than the "
                        f"{NAME_COL_WIDTH - 1}-char name column, table will "
                        f"mis-align")

    return ({'name': name, 'version': version, 'fires_when': fires,
             'header_how': header_how, 'plans': plans}, problems, warnings)


def check(records, problems):
    seen = {}
    for r in records:
        seen.setdefault(r['name'], 0)
        seen[r['name']] += 1
    for name, n in sorted(seen.items()):
        if n > 1:
            problems.append(f"{name}: duplicate skill name used by {n} folders")
    return problems


def check_annotation_examples(skills_dir, problems):
    """Every annotation example in a skill must parse as the parser reads it.

    This is the store-binding check, and it lives here rather than in a
    test file for a practical reason: this tool is the one that runs at
    the moment a skill changes, which is the moment the drift gets
    introduced. A check nobody runs is not a check -- which is the exact
    defect it exists to catch.

    What it caught (L-186, 2026-08-12): provenance-discipline taught an
    annotation format whose own worked example provenance_scanner.py
    could not read. The skill said the ISO date was the check date; the
    parser took the first four-digit year, which in that example was the
    SOURCE's publication year. Two annotations by two different models
    read as one checker written twice, and 19 completed cross-checks
    were scored and reported as half-done for a week. Nothing reported
    the disagreement, because nothing compared the two stores.

    Lines carrying angle brackets are grammar templates, not examples,
    and are skipped.
    """
    try:
        from provenance_scanner import parse_cross_checks, parse_resolved
    except ImportError:
        problems.append(
            'annotation examples not checked: provenance_scanner.py not '
            'importable from this folder')
        return problems

    for skill_dir in sorted(p for p in skills_dir.iterdir() if p.is_dir()):
        # L-418: reference files are read too. A rule that moved out of
        # SKILL.md must not take its examples out of the check with it.
        paths = [skill_dir / 'SKILL.md']
        ref_dir = skill_dir / REFERENCES_DIRNAME
        if ref_dir.is_dir():
            paths.extend(sorted(ref_dir.glob('*.md')))
        for path in paths:
            if not path.is_file():
                continue
            label = skill_dir.name
            if path.name != 'SKILL.md':
                label += f"/{REFERENCES_DIRNAME}/{path.name}"
            text = path.read_text(encoding='utf-8', errors='replace')
            for line in text.splitlines():
                stripped = line.strip()
                if not stripped.startswith('# Cross-checked:') or '<' in stripped:
                    continue
                records, issues = parse_cross_checks(stripped)
                if len(records) != 1:
                    problems.append(
                        f"{label}: annotation example does not parse "
                        f"({issues or 'no record'}): {stripped}")
                    continue
                identity = records[0][0]
                runs = ''.join(c if c.isdigit() else ' ' for c in identity).split()
                if any(len(run) >= 4 for run in runs):
                    problems.append(
                        f"{label}: annotation example's checker carries "
                        f"a year, so the date was parsed from the source: "
                        f"{stripped}")

            # The Resolved leg (L-200) is checked the same way and for the
            # same reason. A skill that teaches a leg the parser refuses is
            # the L-186 defect in a second grammar.
            for line in text.splitlines():
                stripped = line.strip()
                if not stripped.startswith('# Resolved:') or '<' in stripped:
                    continue
                records, issues = parse_resolved(stripped)
                if len(records) != 1:
                    problems.append(
                        f"{label}: Resolved example does not parse "
                        f"({issues or 'no record'}): {stripped}")
    return problems


def sort_key(record):
    name = record['name']
    if name in SKILL_ORDER:
        return (0, SKILL_ORDER.index(name), name)
    return (1, 0, name)  # unknown skills after, alphabetically


def format_row(record):
    """One manifest row: name/version on the first line, fires_when wrapped
    at WRAP_WIDTH with continuation lines indented to TEXT_COL."""
    prefix = record['name'].ljust(NAME_COL_WIDTH) + record['version'].ljust(VER_COL_WIDTH)
    wrapped = textwrap.wrap(record['fires_when'],
                            width=WRAP_WIDTH - TEXT_COL,
                            break_long_words=False,
                            break_on_hyphens=False) or ['']
    out = [prefix + wrapped[0]]
    indent = ' ' * TEXT_COL
    out.extend(indent + w for w in wrapped[1:])
    return out


def build_manifest(records):
    out = [START,
           'Skill'.ljust(NAME_COL_WIDTH) + 'Ver'.ljust(VER_COL_WIDTH) + 'Fires when']
    for r in sorted(records, key=sort_key):
        out.extend(format_row(r))
    out.append(END)
    return '\n'.join(out)


def find_default_protocol(folder):
    """The standard-named, currently-live protocol file next to this
    script. Versioned archival copies (documentation/project_instructions_
    v3_31.md, ...) are historical record only -- this tool never targets
    them by default; pass one explicitly if you ever need to regenerate
    an archived copy's manifest for some reason."""
    candidate = folder / PROTOCOL_DEFAULT_NAME
    return candidate if candidate.is_file() else None


def main():
    here = pathlib.Path(__file__).parent
    args = [a for a in sys.argv[1:] if a != '--check']
    check_only = '--check' in sys.argv[1:]

    if args:
        target = pathlib.Path(args[0])
    else:
        target = find_default_protocol(here)
        if target is None:
            print(f"ERROR: {PROTOCOL_DEFAULT_NAME} not found next to "
                  "skills_index.py; pass the protocol file path explicitly.")
            sys.exit(2)

    skills_dir = here / SKILLS_DIRNAME
    if not skills_dir.is_dir():
        print(f"ERROR: {skills_dir} not found; run from the repo root.")
        sys.exit(2)

    # L-418: in write mode, rewrite every read plan before the skills are
    # read, so the check below reads what was written. Each change is
    # named; a plan already right is left alone.
    if not check_only:
        for skill_dir in sorted(p for p in skills_dir.iterdir() if p.is_dir()):
            paths = [skill_dir / 'SKILL.md']
            ref_dir = skill_dir / REFERENCES_DIRNAME
            if ref_dir.is_dir():
                paths.extend(sorted(ref_dir.glob('*.md')))
            for path in paths:
                if path.is_file():
                    written = write_read_plan(path)
                    if written:
                        rel = path.relative_to(skills_dir).as_posix()
                        print(f"Read plan written: {rel}: {written}")

    records, problems, warnings = [], [], []
    for skill_dir in sorted(p for p in skills_dir.iterdir() if p.is_dir()):
        rec, probs, warns = parse_skill(skill_dir)
        problems.extend(probs)
        warnings.extend(warns)
        if rec:
            records.append(rec)
    problems = check(records, problems)
    problems = check_annotation_examples(skills_dir, problems)

    hows = sorted(set(r.get('header_how', '?') for r in records))
    print(f"Headers: {len(records)} read as YAML by {', '.join(hows)}.")
    if problems:
        print("CONSISTENCY PROBLEMS:")
        for p in problems:
            print(f"  - {p}")
    else:
        print(f"OK: {len(records)} skills parsed, no consistency problems.")
    plans = [p for r in records for p in r.get('plans', [])]
    print(f"Read plans checked ({len(plans)}): "
          f"{', '.join(plans) if plans else 'none'}.")
    if PLAN_NOT_YET:
        print(f"Long skills with no read plan yet, by PLAN_NOT_YET "
              f"({len(PLAN_NOT_YET)}): {', '.join(PLAN_NOT_YET)}.")
    for w in warnings:
        print(f"  WARNING: {w}")

    if check_only:
        # Also verify the target zone exists, since a missing zone blocks writes.
        text = target.read_text(encoding='utf-8')
        if START not in text or END not in text:
            print(f"  - {target.name}: SKILL-MANIFEST markers not found "
                  "(add them around the manifest table before first run)")
            problems.append('markers missing')
        sys.exit(1 if problems else 0)

    text = target.read_text(encoding='utf-8')
    if START not in text or END not in text:
        print(f"ERROR: SKILL-MANIFEST markers not found in {target.name}; "
              "not writing. Add these two lines around the manifest table:")
        print(f"  {START}")
        print(f"  {END}")
        sys.exit(2)

    manifest = build_manifest(records)

    # Drift report (August 2026): name what the manifest was advertising
    # BEFORE overwriting it. Regenerating silently is how three weeks of
    # stale versions went unnoticed -- running the tool made the evidence
    # disappear at the same moment it fixed the problem.
    old_zone = re.search(re.escape(START) + r'(.*?)' + re.escape(END),
                         text, flags=re.DOTALL)
    if old_zone:
        was = dict(re.findall(r'^([a-z0-9][a-z0-9-]*)\s+(\S+)\s',
                              old_zone.group(1), flags=re.M))
        drift = [(r['name'], was[r['name']], r['version'])
                 for r in records
                 if r['name'] in was and was[r['name']] != r['version']]
        missing = [r['name'] for r in records if r['name'] not in was]
        dropped = [n for n in was if n not in {r['name'] for r in records}]
        if drift or missing or dropped:
            print("MANIFEST WAS STALE -- corrected below:")
            for name, old_v, new_v in drift:
                print(f"  - {name}: manifest said {old_v}, SKILL.md says {new_v}")
            for name in missing:
                print(f"  - {name}: missing from the manifest entirely")
            for name in dropped:
                print(f"  - {name}: in the manifest but no longer a skill folder")
            print("  Commit the protocol copies together with the SKILL.md")
            print("  change -- see the binding rule in ledger-and-session-records.")
        else:
            print(f"Manifest already matched all {len(records)} skills.")

    new = re.sub(re.escape(START) + r'.*?' + re.escape(END),
                 lambda _m: manifest, text, flags=re.DOTALL)

    # LF enforced: the protocol file is LF in the repo; a Windows text-mode
    # write would CRLF-convert every line. newline='' preserves our '\n'.
    with open(target, 'w', encoding='utf-8', newline='') as f:
        f.write(new)

    print(f"Skill Manifest regenerated ({len(records)} skills) in {target.name}.")
    sys.exit(1 if problems else 0)


if __name__ == '__main__':
    main()
