"""patch_L270_2_ledger_close_and_open.py -- close L-270, open L-272 and L-273.

RUN COMMAND
-----------
Run this AFTER patch_L270_1_readme_rewrite.py has succeeded. Save it into
the ORRERY repo root, open it in VS Code, and click Run.

    python patch_L270_2_ledger_close_and_open.py

WHAT IT DOES
------------
Three edits to LEDGER_CONSOLIDATED.md, all-or-nothing:

  1. L-270 -> DONE, with a closing record of what the rewrite actually
     changed and what it deliberately did not.
  2. L-272 opened -- the gallery repo's first README.
  3. L-273 opened -- doc_index.py, the document indexer, with the scope
     measured during the design conversation rather than guessed.

Only DETAIL blocks are edited. The INDEX at the top of the ledger is
regenerated by ledger_index.py, which orrery_maintenance_run.py runs as
a generator, so it is not touched here. Setting L-270's status to DONE
also triggers that tool's automatic section migration on the next run.

THE PRECONDITION IS CHECKED, NOT ASSUMED
----------------------------------------
Closing L-270 is a claim that the README rewrite landed. This script
verifies that claim against the disk before writing: README.md must
fingerprint as the rewritten version, and the archived prior version
must exist. If patch_L270_1 has not run, this aborts.

WHAT IT CANNOT CHECK
--------------------
L-272 is closed by a patch that runs in the OTHER repository, and
nothing here can see that repo. So L-272 is written as OPEN with its
closing condition stated, not as DONE. Close it once the gallery push
is confirmed.

WHAT IS PERMANENT
-----------------
The three ledger blocks. This script is one-shot; archive it into
documentation/ once it has run.

NO BACKUP FILE
--------------
Per safe-file-editing 1.10. The fingerprint guard means git holds the
pre-patch file; Discard Changes in GitHub Desktop restores it.

Role: patch
Domain: dev_tools

Module created: August 31, 2026 with Anthropic's Claude Opus 5.
"""

import hashlib
import os
import sys

LEDGER = "LEDGER_CONSOLIDATED.md"
README = "README.md"
ARCHIVE = os.path.join("documentation", "README_archived_20260831.md")

LEDGER_MD5 = "b84d9b07315564bf6cd82c8559c2c11d"
README_NEW_MD5 = "a20a51b97f93a484a06cdc58629641d0"
README_OLD_MD5 = "9bc1eb7853dad1b8056d7fa7ef0520e8"

# ---- edit 1: L-270 status line ----
OLD_270_META = (
    "<!-- L:270 status:OPEN upd:2026-08-30 section:A flag: rice:4/3/95/2 -->"
)
NEW_270_META = (
    "<!-- L:270 status:DONE upd:2026-08-31 section:A flag: rice:4/3/95/2 -->"
)

# ---- edit 2: closing record appended to L-270, and the two new blocks ----
OLD_TAIL = """- **Ref:** L-269 (which surfaced it and removed the gate's dependency
  on it); L-237 (the other stale-record item); The Correction Does Not
  Travel, safe-file-editing 1.9; A Report Names Its Items, resident
  protocol Part 3.

#### [L-271] Patch scripts wrote backups nothing ever removed"""

NEW_TAIL = """- **Ref:** L-269 (which surfaced it and removed the gate's dependency
  on it); L-237 (the other stale-record item); The Correction Does Not
  Travel, safe-file-editing 1.9; A Report Names Its Items, resident
  protocol Part 3.
- **CLOSED 2026-08-31 by `patch_L270_1_readme_rewrite.py`.** The prior
  version is archived at `documentation/README_archived_20260831.md`.
  It was a rewrite, not a repair: the fix list below was the occasion,
  not the scope.
- **Tony's ruling on purpose, 2026-08-31, and it is what reshaped the
  file.** The README's original job -- describe the project and how to
  access the Python -- is largely moot now that the galleries carry the
  work to everyone who is not the developer. Two purposes replace it:
  (1) what Paloma's Orrery is and where to find the documents that
  describe it, and (2) how the codebase is kept correct and the data
  verified. The file is now organised as those two parts. The feature
  catalogue, about fifty lines of bullets, collapsed to one paragraph
  of prose ending in a pointer to MODULE_INDEX.md -- Tony's call, taking
  the middle option against cutting it entirely.
- **The five gaps Tony named, all now filled, and one of them was not
  actually missing.** Provenance discipline (present but a single
  paragraph, and its push gate stated GLOBALLY when the real gate is
  Tier-1 = 0 on the active build path -- a reader taking it literally
  would conclude the project can never push). The protocol and skills
  layer (present as folders, absent as discipline; PROJECT_INSTRUCTIONS.md
  was not linked from the README at all, nor was PROJECT_ORIGIN.md).
  The interactive gallery and the cache transport (wholly absent). The
  commit and push discipline (wholly absent; the only git content was
  consumer-facing `git pull`). The maintenance runners (wholly absent,
  both of them).
- **A sixth section, and it is Tony's, 2026-08-31: what you can reach
  from where.** Four contexts, each adding to the one above --
  palomasorrery.com in a browser, github.com in a browser, a local
  clone with Python, and a Claude session in the Anthropic project. The
  load-bearing part is the last row: the protocol and the skills are
  ordinary files anyone can read on GitHub, but their INSTALLED form --
  the copy a session actually loads -- lives in the account and is
  invisible to everyone, including the running session using it. That
  is the three-store problem stated where a newcomer meets it, and it
  is why Stale Skill = Stop compares against the manifest and why a
  mid-session bump is carried forward in writing rather than cleared.
- **Two defects found by checking rather than by reading.** The single
  link to the gallery repo was misspelled `tonyquintanilla` for
  `tonylquintanilla` and returned 404 -- every other GitHub link in the
  file had the `l`. And the README claimed `tools/gallery_studio.py`
  imports `social_media_export.py` and `constants_new.py` from this
  repo; it does not. It walks up looking for a folder CONTAINING
  `constants_new.py`, uses that as a marker, and imports
  `info_dictionary` for the Object Encyclopedia, degrading quietly to
  no encyclopedia if it finds none. Both corrected in the rewrite.
- **Every hardcoded count is gone, and that is the durable half of this
  item.** There were sixteen, and two already disagreed with each other
  (`star_data/` at ~300 MB in one place and ~330 MB in another). The
  file now names the generated store that owns each number instead of
  restating it -- the same fix-the-producer rule the project applies to
  code. The manual "Last Updated" stamp, which had failed, is gone with
  them. What can still go stale is the architecture and workflow
  description, and the file says so.
- **Gap:** the key-documents table is still hand-maintained, which is
  this same failure in miniature. L-273 replaces it with a generated
  marker zone.

#### [L-272] The gallery repo had no README
<!-- L:272 status:OPEN upd:2026-08-31 section:A flag: rice:3/2/95/1 -->
- **Found 2026-08-31 while rewriting the orrery's README.** Two public
  repositories, and `tonyquintanilla.github.io` had no README at all.
  Someone arriving from palomasorrery.com or from a link in the orrery
  repo saw a file listing and nothing else.
- **It is not a summary of the orrery's README.** It describes only
  what is in that repository and points at the orrery for the project
  itself: the two galleries and why both are wanted, the
  objects_config -> cache builder -> served cache -> assembler ->
  renderer chain, `gallery_maintenance_run.py` and its UNREACHABLE
  state, the `.nojekyll` requirement, and the layout. It carries a
  three-row version of the reach-from-where table, noting that the
  protocol and skills govern work there but have no copy in that repo
  to find.
- **It states the transport gap plainly rather than describing the
  path as automatic.** `data/objects_config.json` is maintained by
  hand, the cache builder has never read `constants_new.py`, and the
  site once served a superseded number for hours after the correction
  was pushed here. A README describing that path as automatic would be
  a false claim about the thing most likely to produce a wrong number
  on the public site.
- **It also names the two position consumers that live in that repo**
  (`tools/gallery_studio.py`, `tools/json_converter.py`), because a
  reader following Check All Parallel Pipelines from the orrery side
  and grepping one repository finds three of five.
- **Delivered as `patch_L272_1_gallery_readme.py`**, run from the
  gallery repo root. It refuses to overwrite an existing README.
- **CLOSING CONDITION:** the gallery push is confirmed. This block is
  written from the orrery repo, which cannot see that one, so it stays
  OPEN until Tony confirms rather than being closed on the strength of
  a patch having been written.
- **Claude:** RICE 3/2/95/1 -> 5.7 proposed, not confirmed. Reach 3
  because it is a front door with real traffic from the site; Effort 1
  because the file is written and the patch is tested.
- **Ref:** L-270 (the same pass); L-262 (the gallery runner); Check All
  Parallel Pipelines, resident protocol Part 3.

#### [L-273] A document indexer, so the README's document table stops being hand-maintained
<!-- L:273 status:OPEN upd:2026-08-31 section:A flag: rice:3/3/85/3 -->
- **Tony's proposal, 2026-08-31, and it is better than what Claude
  recommended.** Claude had offered two shapes for keeping the root
  document set honest: a generator writing a separate DOCUMENT_INDEX.md,
  or a checker that fails when the README's table and the root document
  set disagree. Claude recommended the checker. Tony proposed a third:
  an INDEXER writing into the README in place, the way
  `skills_index.py` writes the manifest into the protocol and
  `ledger_index.py` writes the INDEX into this file.
- **It dissolves Claude's own objection.** The argument against the
  generator was two hops -- a reader wanting to know what
  LEDGER_CONSOLIDATED.md is would land on the README and be sent
  elsewhere. A marker zone inside the README removes that entirely. And
  the argument against the checker was this project's own rule: fix the
  producer rather than alarm on the copy. The indexer fixes the
  producer; the checker only made the duplication loud. Recorded as a
  Claude error rather than smoothed over, because the recommendation
  was argued and wrong.
- **`skills_index.py` is the model, not `ledger_index.py`.** Two
  mechanics to copy deliberately. Its editorial column (`fires_when`)
  is hand-tuned but lives in each SKILL's own frontmatter, not in the
  tool and not in the protocol -- so Tony keeps editorial control of the
  wording while the target file stays generated. And if the markers are
  absent it reports and exits WITHOUT writing, because a wrong guess at
  an insertion point is worse than no write. It also writes LF
  explicitly so a Windows run does not CRLF-convert the target.
- **The design: each document declares itself.** A `Kind` and `Purpose`
  tag in the document's own header; `doc_index.py` reads the
  declarations and writes the table into README.md between markers. Same
  shape as the atlas's `Role:`/`Domain:` docstring tags, and for the
  same reason -- a hand-maintained dict inside the tool is the shadow
  store this project already deleted from `module_atlas.py` when
  ROLE_MAP became a regenerated mirror. An untagged document appears in
  the table as untagged rather than being silently dropped.
- **The distinction the table should carry, which nothing currently
  records:** five root documents are GENERATED and must not be
  hand-edited -- MODULE_ATLAS.md, MODULE_INDEX.md, PROVENANCE_AUDIT.md,
  DATA_INVENTORY.md, WORKSHEET_CHECK.md -- against seven written by
  hand: README.md, PROJECT_INSTRUCTIONS.md, PROJECT_ORIGIN.md,
  LEDGER_CONSOLIDATED.md, ADDING_OBJECTS_GUIDE.md, LICENSE.md,
  RUNNING_A_PATCH_FILE.md. Hand-editing one of the first five is a real
  error class and the only warning against it currently lives inside
  the files themselves.
- **SCOPE, measured rather than guessed, and it is bigger than it
  looks.** The seven hand-written documents need a tag added once. The
  five generated ones cannot be tagged by hand -- the tag is destroyed on
  the next run -- so four GENERATORS must emit it: `module_atlas.py`
  (which writes two of the five), `provenance_scanner.py`,
  `data_inventory.py`, `worksheet_checker.py`. One line each in their
  header emitters. Then `requirements.txt` is `.txt`, so the tag reader
  needs a `#` syntax as well as an HTML comment. Then it all applies
  twice, because the gallery now has a README and its own runner, and
  its atlas copy already uses different SCAN_PATHS.
- **Ruled OUT: extending module_atlas.py to markdown.** Tony asked
  whether root `.md` and `.txt` files should be parsed by the atlas and
  carry a Role. Three reasons against, and the third decides it. The
  atlas's value is the Python structure -- import graph, consumers,
  public functions -- and a document has none, so most columns would be
  empty. Its role vocabulary (`gui`, `pipeline`, `rendering/shells`)
  describes no document, so a parallel vocabulary would live in the same
  ROLE_MAP mirror meaning something else. And it would change what the
  COUNTS mean: the README now says the atlas counts are the canonical
  measure of scale, and PROVENANCE_AUDIT.md's run history has a Files
  column going back weeks. Folding twelve markdown files in would make
  every prior row measure something different, silently.
- **Sequencing, Tony's call 2026-08-31:** run the README patches now and
  build the indexer separately, rather than holding the rewrite to ship
  one clean pass. The rewrite is wrong today in ~600 lines that do not
  touch the table, a marker zone is designed to be dropped into a file
  that already exists, and by The Braid the indexer must not become a
  gate on the README shipping. The accepted cost is editing README.md
  twice in two days, the second edit replacing a section the first one
  wrote.
- **Not a gate on anything.** General correctness work beside the
  delivery work, not in front of it.
- **Claude:** RICE 3/3/85/3 -> 2.6 proposed, not confirmed. Confidence
  85 rather than 95 because the generator-side tag emission is designed
  but not built; Effort 3 for the multi-file scope above.
- **Ref:** L-270 (the Gap that raised it); `skills_index.py` and
  `ledger_index.py` as the two working precedents; A Report Names Its
  Items, resident protocol Part 3 -- the indexer's summary names what
  moved rather than printing a count.

#### [L-271] Patch scripts wrote backups nothing ever removed"""


def fail(msg):
    print("")
    print("FAILURE: " + msg)
    print("NOTHING was written.")
    print("Undo is Discard Changes in GitHub Desktop.")
    sys.exit(1)


def read_norm(path):
    with open(path, "rb") as fh:
        raw = fh.read()
    return raw, raw.replace(b"\r\n", b"\n"), b"\r\n" in raw


def main():
    if not os.path.isfile("PROJECT_INSTRUCTIONS.md"):
        fail("run this from the ORRERY repo root (the folder holding "
             "PROJECT_INSTRUCTIONS.md). Current folder: " + os.getcwd())

    for p in (LEDGER, README):
        if not os.path.isfile(p):
            fail(p + " not found in " + os.getcwd())

    # ---- precondition: the README rewrite actually landed ----
    _, readme_norm, _ = read_norm(README)
    readme_md5 = hashlib.md5(readme_norm).hexdigest()
    if readme_md5 != README_NEW_MD5:
        if readme_md5 == README_OLD_MD5:
            fail("patch_L270_1_readme_rewrite.py has NOT run yet -- README.md\n"
                 "  is still the prior version. Run that patch first; closing\n"
                 "  L-270 before the rewrite lands would record a claim that\n"
                 "  is not true.")
        fail("README.md fingerprints " + readme_md5 + ", which is neither the\n"
             "  prior version nor the rewritten one. Establish what it is\n"
             "  before closing L-270 against it.")
    print("ok  precondition: README.md is the rewritten version")

    if not os.path.exists(ARCHIVE):
        fail(ARCHIVE + " is missing. The rewrite patch writes it, so its\n"
             "  absence means the tree is not in the state this patch\n"
             "  expects.")
    _, arch_norm, _ = read_norm(ARCHIVE)
    if hashlib.md5(arch_norm).hexdigest() != README_OLD_MD5:
        fail("the archived README does not match the version it should have\n"
             "  preserved.")
    print("ok  precondition: prior README archived and intact")

    # ---- guard: the ledger is what this was built against ----
    raw, content, was_crlf = read_norm(LEDGER)
    actual = hashlib.md5(content).hexdigest()
    if actual != LEDGER_MD5:
        fail("BASE MOVED. " + LEDGER + " fingerprints " + actual +
             ", expected " + LEDGER_MD5 + ".\n"
             "  Establish WHAT differs before assuming an edit was made: a\n"
             "  size delta of about one byte per line means line endings,\n"
             "  not content.")
    print("ok  base fingerprint matches" +
          (" [CRLF working copy, matched after normalising]" if was_crlf else ""))

    text = content.decode("ascii", "strict")

    # ---- anchors verified BEFORE any write ----
    for label, anchor in (("L-270 status line", OLD_270_META),
                          ("L-270 tail / L-271 header", OLD_TAIL)):
        n = text.count(anchor)
        if n != 1:
            fail("anchor for %s appears %d times, expected exactly 1."
                 % (label, n))
    print("ok  2/2 anchors found, each exactly once")

    new_text = text.replace(OLD_270_META, NEW_270_META, 1)
    new_text = new_text.replace(OLD_TAIL, NEW_TAIL, 1)

    out = new_text.encode("ascii")
    nonascii = [b for b in out if b > 127]
    if nonascii:
        fail("result holds %d non-ASCII byte(s)." % len(nonascii))

    if was_crlf:
        out = out.replace(b"\n", b"\r\n")

    with open(LEDGER, "wb") as fh:
        fh.write(out)
    print("ok  wrote " + LEDGER + " (%d bytes)" % len(out))

    # ---- verification: read back from disk ----
    _, back, _ = read_norm(LEDGER)
    got = back.decode("ascii", "replace")
    problems = []

    if "<!-- L:270 status:DONE" not in got:
        problems.append("L-270 is not marked DONE")
    for handle, header in (("L-272", "#### [L-272] The gallery repo had no README"),
                           ("L-273", "#### [L-273] A document indexer")):
        if header not in got:
            problems.append(handle + " detail block missing")
        if got.count("<!-- L:" + handle[2:] + " status:") != 1:
            problems.append(handle + " metadata line not present exactly once")
    if got.count("#### [L-271] Patch scripts wrote backups") != 1:
        problems.append("L-271's block was disturbed")

    if problems:
        print("")
        print("VERIFICATION FAILED after writing:")
        for p in problems:
            print("  - " + p)
        print("Undo is Discard Changes in GitHub Desktop.")
        sys.exit(1)

    print("ok  verified: L-270 DONE, L-272 and L-273 present, L-271 intact")
    print("")
    print("patch applied. Three blocks changed:")
    print("  L-270  OPEN -> DONE   README rewritten; closing record added")
    print("  L-272  new, OPEN      gallery repo README")
    print("  L-273  new, OPEN      doc_index.py document indexer")
    print("")
    print("NEXT STEPS")
    print("  1. Run: python orrery_maintenance_run.py")
    print("     ledger_index.py regenerates the INDEX and migrates L-270")
    print("     into the closed section. Do not hand-edit the INDEX.")
    print("  2. Commit the ledger, README.md, the archived README, and the")
    print("     patch scripts (after moving them into documentation/).")
    print("")
    print("STILL OPEN, and it needs you:")
    print("  L-272 stays OPEN because this repo cannot see the gallery")
    print("  repo. Close it once the gallery README is pushed.")


if __name__ == "__main__":
    main()
