#!/usr/bin/env python3
"""
patch_L371_session_close_20261003.py -- ORRERY repo. Closes the session
of 2026-10-02/03: the session record, Where We Are, and the ledger's
notes on L-406, L-407 and L-371.

Built on orrery fd508f9c7794e3a51b22a4e1e3aa3a54c3e339ef
at https://github.com/tonylquintanilla/palomas_orrery
(gallery 52659e04b38dd773aa14b6e6e9e1a533bff114e7
at https://github.com/tonylquintanilla/tonyquintanilla.github.io;
not touched).

WHAT CHANGES
    documentation/HANDOFF_L406_L407_L371_session_20261003.md   NEW: the
        session record. Its section 3 carries every source read for the
        Sun's distance cards and Tony's rulings, so the next session
        builds without re-reading.
    documentation/WHERE_WE_ARE.md   rewritten for this session, marks
        reset.
    LEDGER_CONSOLIDATED.md   L-406: the phone look and the 60-degree
        cross-check; L-407: patch_L407_2 pushed; L-371: the 18 lines on
        15 cards, named, and the next build.

No code changes. Checked here: the orrery suite passes, the one
Linux-only failure aside. The maintenance run afterwards updates one
date in the ledger's index (L-371's).

HOW TO RUN IT
    Save this file in the ORRERY repo ROOT (next to palomas_orrery.py),
    open it in VS Code and click Run. The same as:
        python patch_L371_session_close_20261003.py

SUCCESS looks like: one "ok" line per edit and per file, then "patch
applied". FAILURE looks like: one ERROR: or ANCHOR FAIL: line, and
NOTHING is written. Undo is Discard Changes in GitHub Desktop.

Written October 3, 2026 with Anthropic's Claude Opus 5.5.
"""

import hashlib
import os

BASE = {'LEDGER_CONSOLIDATED.md': '11241dae2a6acfe41c732cfae8bb41ab',
 'documentation/WHERE_WE_ARE.md': '1ef031b3fe06fe07eaa178cd0636b6f2'}

EDITS = {'LEDGER_CONSOLIDATED.md': [('L-406: the phone look and the 60-degree '
                             'cross-check',
                             '  cache rebuild pushed at gallery 6ba42f02.**\n'
                             '**Gap:** Tony: reinstall interactive-exhibit '
                             '1.10, and look at the tide\n',
                             '  cache rebuild pushed at gallery 6ba42f02.**\n'
                             '- **Seen on the phone, 2026-10-03:** Tony, of '
                             "the tide's hover and\n"
                             '  panel: "The text looks right." The visual '
                             'pattern -- an X tilted\n'
                             '  about 60 degrees against the Hills torus -- '
                             'is not yet reported.\n'
                             '- **Cross-check:** Portegies Zwart et al. 2021 '
                             '(A&A 652, A144, sec.\n'
                             '  3.2) set the ecliptic at 60 degrees to the '
                             'Galactic plane; the\n'
                             "  redrawn tide's stored pole gives 60.19 "
                             'degrees.\n'
                             '**Gap:** Tony: reinstall interactive-exhibit '
                             '1.10, and look at the tide\n'),
                            ('L-407: ran and pushed',
                             '  one line by patch_L406_3 (pushed at '
                             '81e19ef), still 1.10.\n'
                             '**Gap:** Tony reinstalls interactive-exhibit, '
                             'earth-system-pipeline and\n',
                             '  one line by patch_L406_3 (pushed at '
                             '81e19ef), still 1.10.\n'
                             '- **patch_L407_2 ran and was pushed at orrery '
                             'fd508f9.**\n'
                             '**Gap:** Tony reinstalls interactive-exhibit, '
                             'earth-system-pipeline and\n'),
                            ('L-371: the distance cards, read and ruled',
                             '  time, each needing its own source hunt.\n'
                             "**Gap:** The Sun's slice, second half: the "
                             "numbers already linked -- L-386's rows stored "
                             'in another unit, and the radius lines that '
                             'print with no count. Then the fifteen '
                             'eyeballed shape numbers, one drawing at a '
                             'time.\n',
                             '  time, each needing its own source hunt.\n'
                             "- **The Sun's distance cards, 2026-10-03.** "
                             'Tony, on the phone: the\n'
                             '  km do not follow the figures rule ("= '
                             '299,195,741,400 km (2.00e+3\n'
                             '  AU)"). 18 lines on 15 cards. km at every '
                             'digit from an AU row (6):\n'
                             '  Termination Shock, Heliopause, Inner Limit '
                             'of Oort Cloud, Inner Oort\n'
                             '  Cloud, Outer Oort Cloud, Gravitational '
                             'Influence, each with its AU in\n'
                             '  scientific form. km at every digit from '
                             'solar radii (6 lines, 5\n'
                             '  cards): Streamer Belt (two), Inner Corona, '
                             'Roche Limit (Comets),\n'
                             '  Alfven Surface, Outer Corona. AU as typed '
                             'and km at three figures\n'
                             '  (6 lines, 3 cards): Hills Cloud torus, Outer '
                             'Oort clumps, Galactic\n'
                             '  Tide. Cause: the 11 rows behind them carry '
                             'no figure count, and 10\n'
                             '  have no Unit line, so they are not '
                             'exported.\n'
                             "- **Sources read and Tony's rulings, "
                             '2026-10-02/03:** recorded in full\n'
                             '  in '
                             '`documentation/HANDOFF_L406_L407_L371_session_20261003.md`,\n'
                             "  section 3 -- each row's source, what it "
                             'prints, its figure count;\n'
                             '  ruling A (draw one end of a range and say '
                             "so, built by the skill's\n"
                             '  range rule); the approved notes; '
                             'Gravitational Influence as the\n'
                             "  Sun's Hill radius, 0.65 pc (Portegies Zwart "
                             "et al. 2021), on Tony's\n"
                             '  correction that a Hill sphere is calculated, '
                             'not chosen.\n'
                             '**Gap:** Build the distance cards as the '
                             "handoff's section 3 says: the\n"
                             "orrery rows (with L-386's two re-homes, the "
                             'Heliopause to 121 AU and\n'
                             'Gravitational Influence to 0.65 pc), the '
                             'orrery hovers by count, then\n'
                             "the gallery's notes, mirror and cache. Then "
                             'the fifteen eyeballed shape\n'
                             'numbers, one drawing at a time.\n'),
                            ('L-371 date',
                             '<!-- L:371 status:OPEN upd:2026-10-02 '
                             'section:A flag: rice: -->',
                             '<!-- L:371 status:OPEN upd:2026-10-03 '
                             'section:A flag: rice: -->')],
 'documentation/WHERE_WE_ARE.md': [('rewritten for this session',
                                    '<!-- Doc-Kind: hand | Where the project '
                                    'is and where it is going, in plain '
                                    'words. One file, rewritten in place; '
                                    'read it at the end of every session. '
                                    '-->\n'
                                    '# Where We Are\n'
                                    '\n'
                                    'Last updated: October 2, 2026, end of '
                                    'session\n'
                                    '- Written at orrery bb1b1314 and '
                                    'gallery 0ffa4518.\n'
                                    '\n'
                                    '> **READ THIS FIRST**\n'
                                    '>\n'
                                    '> **Changed this session:**\n'
                                    "> - The Solar System room's drawer is "
                                    'on the website, and your phone\n'
                                    '>   check passed nearly everything.\n'
                                    '> - The room opens on the four inner '
                                    'planets, set in the editor, which\n'
                                    '>   now lists every room.\n'
                                    '> - The room frames where each body is '
                                    'now, plus 20%: your ruling.\n'
                                    '> - Two skills and the protocol are '
                                    'updated for this work.\n'
                                    '>\n'
                                    '> **Do next:**\n'
                                    "> - *The Sun's numbers get the same "
                                    "checking Earth's got.*\n"
                                    '>\n'
                                    '> **Needs you now:**\n'
                                    '> - *Nothing. At the next design talk: '
                                    'what Home should do.*\n'
                                    '\n'
                                    'How to read the marks:\n'
                                    '- *Italic* lines are the must-reads.\n'
                                    '- **>> UPDATED THIS SESSION** beside a '
                                    'heading means that section\n'
                                    '  changed in the latest session.\n'
                                    '- "<< new this session" beside a road '
                                    'stage marks a change to the road.\n'
                                    '- Sections without a mark are as they '
                                    'were.\n'
                                    '- The marks are cleared and reset at '
                                    "every session's update, so they\n"
                                    '  always mean "new since you last read '
                                    'this."\n'
                                    '\n'
                                    '## The goal\n'
                                    '\n'
                                    "- Paloma's Orrery on the web.\n"
                                    '- The website does what the desktop '
                                    'orrery does, in the browser, from\n'
                                    '  data fetched from JPL each night, so '
                                    'a visitor never waits on JPL.\n'
                                    '- Anyone can open it, with nothing to '
                                    'install.\n'
                                    '- Built from the same code and the same '
                                    'checked numbers as the desktop\n'
                                    '  orrery.\n'
                                    '- The one real limit: the browser can '
                                    'show only the dates the saved\n'
                                    '  data covers.\n'
                                    '- Within that range, a visitor will be '
                                    'able to choose a date, and\n'
                                    '  perhaps play time forward.\n'
                                    '\n'
                                    '## The road  **>> UPDATED THIS '
                                    'SESSION**\n'
                                    '\n'
                                    "  1. [done]   The Sun's room is live on "
                                    'the website.\n'
                                    "  2. [done]   Earth's room is live, "
                                    'with every number traced to its '
                                    'source.\n'
                                    '  3. [done]   The numbers come from one '
                                    'place: the orrery feeds the\n'
                                    '              website, and nothing is '
                                    'typed twice.\n'
                                    '  4. [NOW]    The Solar System room '
                                    'becomes a second way in: all the\n'
                                    '              planets, a drawer to pick '
                                    'them, and a way into each\n'
                                    "              body's own room. << new "
                                    'this session: built and on the\n'
                                    '              website; what Home does '
                                    'is still to settle.\n'
                                    "  5. [next]   *The Sun's numbers get "
                                    "the same checking Earth's got.*\n"
                                    "  6. [next]   The Solar System room's "
                                    'card becomes the top featured\n'
                                    '              card in the lobby. A bare '
                                    'interactive.html link opens\n'
                                    '              the Solar System room, '
                                    'and the Explorer gets its own\n'
                                    '              address.\n'
                                    "  7. [later]  The rest of the orrery's "
                                    'objects come to the website --\n'
                                    '              dwarf planets, asteroids, '
                                    'moons -- through the same\n'
                                    '              connection that now '
                                    "carries the room's eleven bodies,\n"
                                    '              checked against JPL '
                                    'Horizons.\n'
                                    '  8. [later]  Encounters: comets and '
                                    'spacecraft shown at the dates\n'
                                    '              that matter.\n'
                                    '  9. [later]  The planets get their '
                                    'details -- layers, rings, magnetic\n'
                                    '              fields -- Jupiter and '
                                    'Saturn first.\n'
                                    ' 10. [goal]   The website does what the '
                                    'desktop orrery does, from data\n'
                                    '              fetched from JPL each '
                                    'night, with a date to choose and\n'
                                    '              time to play within the '
                                    'range the data covers.\n'
                                    '\n'
                                    '## Right now  **>> UPDATED THIS '
                                    'SESSION**\n'
                                    '\n'
                                    '- The Solar System room opens on the '
                                    'Sun and the four inner planets,\n'
                                    '  with Earth named on the closed '
                                    'drawer.\n'
                                    "- Its drawer is live: the Sun's row is "
                                    'fixed, rows open with "Enter\n'
                                    '  the Sun room" or "Enter the Earth '
                                    'room", Apophis waits under See\n'
                                    '  more, and a tap on a body finds its '
                                    'row.\n'
                                    '- The view holds every body drawn, '
                                    "where it is now, plus 20%. Pluto's\n"
                                    '  orbit runs past the edge until you '
                                    'press -.\n'
                                    '- Home works, but falling back to an '
                                    'earlier body shows no visible\n'
                                    '  change. That is the open design '
                                    'question below.\n'
                                    "- Each body's info panel shows a "
                                    'description and a NASA link, copied\n'
                                    "  from the orrery's own object list.\n"
                                    '- The editor can set what any room '
                                    'opens on. It cannot yet change the\n'
                                    "  words on the Solar System room's "
                                    "rows, such as Pluto's sentence.\n"
                                    "- The rest of the orrery's objects are "
                                    'not connected yet.\n'
                                    '\n'
                                    '## The next three steps  **>> UPDATED '
                                    'THIS SESSION**\n'
                                    '\n'
                                    "1. *The Sun's numbers get the same "
                                    "checking Earth's got.*\n"
                                    "2. The drawer's small fixes:\n"
                                    "   - The info panel's two paragraphs "
                                    'become bullet lists, as you\n'
                                    '     asked.\n'
                                    "   - One sentence in the room's "
                                    'settings still says the view fits\n'
                                    '     1.1 times what is drawn; it is 1.2 '
                                    'now.\n'
                                    '   - You look again at an opened row on '
                                    'the phone: does the drawer\n'
                                    '     still fit and scroll, and is '
                                    '"Enter" easy to hit?\n'
                                    '3. What Home should do, settled in '
                                    'conversation, then built.\n'
                                    '\n'
                                    '## Waiting on you  **>> UPDATED THIS '
                                    'SESSION**\n'
                                    '\n'
                                    'Now:\n'
                                    '- Nothing.\n'
                                    '\n'
                                    'At the next design talk:\n'
                                    '- *Home.* My reading of your phone '
                                    'note: Home already names the last\n'
                                    '  body ticked, but it frames everything '
                                    'drawn, so falling back to an\n'
                                    '  earlier body only changes the name on '
                                    "the drawer's handle. You may\n"
                                    '  have expected Home to take the view '
                                    'to that body. Your idea: a\n'
                                    '  second Home tap returns to the '
                                    'opening view.\n'
                                    '- Moving the highlighted row to the top '
                                    'of the list. The list is now\n'
                                    '  in order outward from the Sun, so '
                                    'this changes that order.\n'
                                    "- An arrow from GO's text box to its "
                                    'body. On a phone held upright the\n'
                                    '  text box has no arrow and sits '
                                    'mid-view, by your earlier ruling, so\n'
                                    '  this would change that ruling.\n'
                                    '\n'
                                    'Not urgent, in your order:\n'
                                    "1. The full check of the orrery's "
                                    'object list against JPL Horizons.\n'
                                    '   - Its first run lists what '
                                    'disagrees; simple errors get fixed and\n'
                                    '     listed, the rest come to you.\n'
                                    '2. Whether the editor should also edit '
                                    'the words on the Solar System\n'
                                    "   room's rows, such as Pluto's "
                                    'sentence.\n'
                                    '   - Today a change to them comes as a '
                                    'patch from a session.\n'
                                    '3. Choosing a date, and animation, your '
                                    'idea of October 1.\n'
                                    '   - The range would follow only the '
                                    'bodies you tick.\n'
                                    '\n'
                                    '## Where the details are  **>> UPDATED '
                                    'THIS SESSION**\n'
                                    '\n'
                                    '- Every item, done and open: '
                                    '`LEDGER_CONSOLIDATED.md`\n'
                                    '  - This session: L-404 (done), L-405, '
                                    'and the newest notes on L-363.\n'
                                    '- The reasoning behind the order:\n'
                                    '  '
                                    '`documentation/MASTER_PLAN_INTERACTIVE_GALLERY.md`\n'
                                    '- The latest session record:\n'
                                    '  '
                                    '`documentation/HANDOFF_L363_L404_L405_session_20261002.md`\n',
                                    '<!-- Doc-Kind: hand | Where the project '
                                    'is and where it is going, in plain '
                                    'words. One file, rewritten in place; '
                                    'read it at the end of every session. '
                                    '-->\n'
                                    '# Where We Are\n'
                                    '\n'
                                    'Last updated: October 3, 2026, end of '
                                    'session\n'
                                    '- Written at orrery fd508f9c and '
                                    'gallery 52659e04.\n'
                                    '\n'
                                    '> **READ THIS FIRST**\n'
                                    '>\n'
                                    '> **Changed this session:**\n'
                                    "> - The Sun room's galactic tide is now "
                                    "drawn in the galaxy's plane,\n"
                                    '>   sparse at that plane and at its '
                                    'poles. Its words are new, and you\n'
                                    '>   saw them right on the phone.\n'
                                    "> - Every skill's header is now checked "
                                    'the way Settings reads it.\n'
                                    '>   Three were broken; one of them had '
                                    'been cutting\n'
                                    ">   provenance-discipline's description "
                                    'short.\n'
                                    "> - The sources for the Sun's distance "
                                    'cards are read, and you ruled on\n'
                                    '>   how to show the ones given as a '
                                    'range.\n'
                                    '>\n'
                                    '> **Do next:**\n'
                                    "> - *Build the Sun's distance cards so "
                                    'every number prints at its\n'
                                    ">   source's figures.*\n"
                                    '>\n'
                                    '> **Needs you now:**\n'
                                    '> - *If not done yet: reinstall the '
                                    'three skills and the v3.79\n'
                                    '>   instructions, and look for the '
                                    "tide's X on the phone.*\n"
                                    '\n'
                                    'How to read the marks:\n'
                                    '- *Italic* lines are the must-reads.\n'
                                    '- **>> UPDATED THIS SESSION** beside a '
                                    'heading means that section\n'
                                    '  changed in the latest session.\n'
                                    '- "<< new this session" beside a road '
                                    'stage marks a change to the road.\n'
                                    '- Sections without a mark are as they '
                                    'were.\n'
                                    '- The marks are cleared and reset at '
                                    "every session's update, so they\n"
                                    '  always mean "new since you last read '
                                    'this."\n'
                                    '\n'
                                    '## The goal\n'
                                    '\n'
                                    "- Paloma's Orrery on the web.\n"
                                    '- The website does what the desktop '
                                    'orrery does, in the browser, from\n'
                                    '  data fetched from JPL each night, so '
                                    'a visitor never waits on JPL.\n'
                                    '- Anyone can open it, with nothing to '
                                    'install.\n'
                                    '- Built from the same code and the same '
                                    'checked numbers as the desktop\n'
                                    '  orrery.\n'
                                    '- The one real limit: the browser can '
                                    'show only the dates the saved\n'
                                    '  data covers.\n'
                                    '- Within that range, a visitor will be '
                                    'able to choose a date, and\n'
                                    '  perhaps play time forward.\n'
                                    '\n'
                                    '## The road  **>> UPDATED THIS '
                                    'SESSION**\n'
                                    '\n'
                                    "  1. [done]   The Sun's room is live on "
                                    'the website.\n'
                                    "  2. [done]   Earth's room is live, "
                                    'with every number traced to its '
                                    'source.\n'
                                    '  3. [done]   The numbers come from one '
                                    'place: the orrery feeds the\n'
                                    '              website, and nothing is '
                                    'typed twice.\n'
                                    '  4. [NOW]    The Solar System room '
                                    'becomes a second way in: all the\n'
                                    '              planets, a drawer to pick '
                                    'them, and a way into each\n'
                                    "              body's own room. Built "
                                    'and on the website; what Home\n'
                                    '              does is still to settle.\n'
                                    "  5. [NOW]    *The Sun's numbers get "
                                    "the same checking Earth's got.*\n"
                                    '              << new this session: '
                                    'begun. The 43 drawing numbers are\n'
                                    '              sorted, the galactic tide '
                                    'is redrawn, and the distance\n'
                                    "              cards' sources are read; "
                                    'the build is next.\n'
                                    "  6. [next]   The Solar System room's "
                                    'card becomes the top featured\n'
                                    '              card in the lobby. A bare '
                                    'interactive.html link opens\n'
                                    '              the Solar System room, '
                                    'and the Explorer gets its own\n'
                                    '              address.\n'
                                    "  7. [later]  The rest of the orrery's "
                                    'objects come to the website --\n'
                                    '              dwarf planets, asteroids, '
                                    'moons -- through the same\n'
                                    '              connection that now '
                                    "carries the room's eleven bodies,\n"
                                    '              checked against JPL '
                                    'Horizons.\n'
                                    '  8. [later]  Encounters: comets and '
                                    'spacecraft shown at the dates\n'
                                    '              that matter.\n'
                                    '  9. [later]  The planets get their '
                                    'details -- layers, rings, magnetic\n'
                                    '              fields -- Jupiter and '
                                    'Saturn first.\n'
                                    ' 10. [goal]   The website does what the '
                                    'desktop orrery does, from data\n'
                                    '              fetched from JPL each '
                                    'night, with a date to choose and\n'
                                    '              time to play within the '
                                    'range the data covers.\n'
                                    '\n'
                                    '## Right now  **>> UPDATED THIS '
                                    'SESSION**\n'
                                    '\n'
                                    '- The galactic tide is live, tilted '
                                    "into the galaxy's plane. It is\n"
                                    '  drawn between 20,000 and 100,000 AU, '
                                    "the outer Oort cloud's edges.\n"
                                    '- Fourteen other Sun cards print their '
                                    'km with every digit, such as\n'
                                    '  299,195,741,400 km for 2,000 AU. The '
                                    'rows behind them do not yet say\n'
                                    '  how many figures their sources give.\n'
                                    '- The maintenance run now fails if a '
                                    "skill's header would be refused\n"
                                    '  by Settings: 20 checks where there '
                                    'were 19.\n'
                                    '- The Solar System room and its drawer '
                                    'are as they were: Home still\n'
                                    '  shows no visible change when it falls '
                                    'back to an earlier body.\n'
                                    '\n'
                                    '## The next three steps  **>> UPDATED '
                                    'THIS SESSION**\n'
                                    '\n'
                                    "1. *The Sun's distance cards, built:*\n"
                                    '   - Each distance row gets its '
                                    "source's figure count, so the km print\n"
                                    '     at that count.\n'
                                    '   - Where a source gives a range, the '
                                    'card draws one end and says so,\n'
                                    '     as you ruled: for example "Thought '
                                    'to lie between 2,000 and 5,000\n'
                                    '     AU; drawn at 2,000."\n'
                                    '   - The Heliopause moves to 121 AU, '
                                    'and Gravitational Influence to\n'
                                    "     0.65 parsecs: the Sun's Hill "
                                    'radius, calculated.\n'
                                    "2. The drawer's small fixes: the info "
                                    "panel's bullet lists, the 1.1\n"
                                    '   that should say 1.2, and your second '
                                    'look at an opened row.\n'
                                    '3. What Home should do, settled in '
                                    'conversation, then built.\n'
                                    '\n'
                                    '## Waiting on you  **>> UPDATED THIS '
                                    'SESSION**\n'
                                    '\n'
                                    'Now, if not done yet:\n'
                                    '- Reinstall three skills in Settings > '
                                    'Skills: interactive-exhibit,\n'
                                    '  earth-system-pipeline and '
                                    'provenance-discipline.\n'
                                    "- Replace the Project's instructions "
                                    'with PROJECT_INSTRUCTIONS.md\n'
                                    '  v3.79.\n'
                                    '- Look at the galactic tide on the '
                                    'phone: tick it and the Hills\n'
                                    '  torus, and turn the view until the '
                                    'tide shows an X tilted against\n'
                                    '  the torus.\n'
                                    '\n'
                                    'At the next design talk:\n'
                                    '- *Home.* Home names the last body '
                                    'ticked but frames everything drawn,\n'
                                    '  so falling back only changes the name '
                                    "on the drawer's handle. Your\n"
                                    '  idea: a second Home tap returns to '
                                    'the opening view.\n'
                                    '- Moving the highlighted row to the top '
                                    'of the list.\n'
                                    "- An arrow from GO's text box to its "
                                    'body.\n'
                                    '\n'
                                    'Not urgent, in your order:\n'
                                    "1. The full check of the orrery's "
                                    'object list against JPL Horizons.\n'
                                    '2. Whether the editor should also edit '
                                    'the words on the Solar System\n'
                                    "   room's rows.\n"
                                    '3. Choosing a date, and animation.\n'
                                    '\n'
                                    '## Where the details are  **>> UPDATED '
                                    'THIS SESSION**\n'
                                    '\n'
                                    '- Every item, done and open: '
                                    '`LEDGER_CONSOLIDATED.md`\n'
                                    '  - This session: L-406 (the tide), '
                                    'L-407 (skill headers), L-405\n'
                                    '    (done), and the newest notes on '
                                    "L-371 (the Sun's numbers).\n"
                                    '- The reasoning behind the order:\n'
                                    '  '
                                    '`documentation/MASTER_PLAN_INTERACTIVE_GALLERY.md`\n'
                                    '- The latest session record:\n'
                                    '  '
                                    '`documentation/HANDOFF_L406_L407_L371_session_20261003.md`\n')]}

NEW_FILES = {'documentation/HANDOFF_L406_L407_L371_session_20261003.md': '<!-- Doc-Kind: '
                                                             'hand | Session '
                                                             'record of '
                                                             '2026-10-02/03: '
                                                             'the galactic '
                                                             'tide redrawn, '
                                                             'skill headers '
                                                             'checked as '
                                                             'YAML, the '
                                                             "Sun's distance "
                                                             'sources read. '
                                                             'Read at the '
                                                             "next session's "
                                                             'start. -->\n'
                                                             '# Handoff -- '
                                                             '2026-10-02/03: '
                                                             'the galactic '
                                                             'tide, skill '
                                                             'headers, the '
                                                             "Sun's "
                                                             'distances\n'
                                                             '\n'
                                                             'Built on '
                                                             'orrery '
                                                             'fd508f9c7794e3a51b22a4e1e3aa3a54c3e339ef '
                                                             'at\n'
                                                             'https://github.com/tonylquintanilla/palomas_orrery '
                                                             'and gallery\n'
                                                             '52659e04b38dd773aa14b6e6e9e1a533bff114e7 '
                                                             'at\n'
                                                             'https://github.com/tonylquintanilla/tonyquintanilla.github.io '
                                                             '-- the\n'
                                                             'state after '
                                                             'every build '
                                                             'push of the '
                                                             'session. This '
                                                             'file arrives '
                                                             'with\n'
                                                             '`patch_L371_session_close_20261003.py`.\n'
                                                             '\n'
                                                             '- **Type:** '
                                                             'BUILD (L-406, '
                                                             'L-407) and '
                                                             'SOURCE READING '
                                                             'for the next '
                                                             'build\n'
                                                             '  (L-371, '
                                                             'L-386). Most '
                                                             'of it done '
                                                             "from Tony's "
                                                             'phone.\n'
                                                             '- '
                                                             '**Supersedes:** '
                                                             'nothing. '
                                                             '**Ledger '
                                                             'items:** L-406 '
                                                             '(open: the '
                                                             'Mode 5\n'
                                                             '  look), L-407 '
                                                             '(open: '
                                                             'reinstall '
                                                             'confirmed next '
                                                             'session), '
                                                             'L-405 (done),\n'
                                                             '  L-371 and '
                                                             'L-386 (open: '
                                                             'built next '
                                                             'session).\n'
                                                             '\n'
                                                             '## 1. Check '
                                                             'first, before '
                                                             'any work\n'
                                                             '\n'
                                                             '- **Your '
                                                             'loaded '
                                                             'skills.** '
                                                             'interactive-exhibit '
                                                             'must read '
                                                             '1.10,\n'
                                                             '  '
                                                             'earth-system-pipeline '
                                                             '1.2, '
                                                             'provenance-discipline '
                                                             '2.25. And\n'
                                                             '  '
                                                             "provenance-discipline's "
                                                             'description, '
                                                             'in your list '
                                                             'of skills, '
                                                             'must run\n'
                                                             '  past "adding '
                                                             'or reviewing" '
                                                             '-- until L-407 '
                                                             'YAML cut it '
                                                             'there. If any\n'
                                                             '  differs, '
                                                             'STOP and ask '
                                                             'Tony to '
                                                             'reinstall '
                                                             '(Stale Skill = '
                                                             'Stop).\n'
                                                             '- **HEAD.** '
                                                             'Orrery at '
                                                             'fd508f9c plus '
                                                             'this close '
                                                             'patch; gallery '
                                                             'at\n'
                                                             '  52659e04. '
                                                             'Anything else: '
                                                             'reconcile '
                                                             'before '
                                                             'building.\n'
                                                             '\n'
                                                             '## 2. What was '
                                                             'done\n'
                                                             '\n'
                                                             'Each line says '
                                                             'whether it was '
                                                             'VERIFIED, and '
                                                             'by what, or is '
                                                             'a CLAIM.\n'
                                                             '\n'
                                                             '- **The Sun '
                                                             "room's 43 "
                                                             'unlinked '
                                                             'numbers sorted '
                                                             '(L-371).** All '
                                                             'are in the\n'
                                                             '  four '
                                                             'hand-built '
                                                             "shapes' "
                                                             'drawing '
                                                             'blocks; none '
                                                             'is a '
                                                             'measurement. '
                                                             '22\n'
                                                             '  rendering '
                                                             'settings, 2 '
                                                             'copies of '
                                                             'linked rows, '
                                                             '19 eyeballed '
                                                             'shape\n'
                                                             '  numbers. The '
                                                             'full list is '
                                                             'on L-371.\n'
                                                             '- **The '
                                                             'galactic tide '
                                                             'drawn in the '
                                                             "galaxy's plane "
                                                             '(L-406).** '
                                                             'Three rows\n'
                                                             '  for the '
                                                             'galactic pole '
                                                             'of J2000 '
                                                             '(Murray 1989, '
                                                             'as printed by '
                                                             'Liu, Zhu\n'
                                                             '  and Hu); '
                                                             'density as '
                                                             '|sin b cos b| '
                                                             '(Delsemme '
                                                             '1987; Matese '
                                                             'and\n'
                                                             '  Whitmire); '
                                                             'drawn between '
                                                             'the outer Oort '
                                                             "cloud's edges; "
                                                             'words in\n'
                                                             "  Tony's "
                                                             'approved form. '
                                                             'VERIFIED: '
                                                             'orrery 19 of '
                                                             '19, gallery 23 '
                                                             'of 23,\n'
                                                             '  pole '
                                                             'matrices '
                                                             'unchanged for '
                                                             'eight bodies, '
                                                             'the new check '
                                                             'fails six\n'
                                                             '  ways on the '
                                                             'old drawing; '
                                                             'pushed at '
                                                             'orrery '
                                                             '94ff6c68 and '
                                                             'gallery\n'
                                                             '  6ba42f02. '
                                                             'Tony on the '
                                                             'phone: "The '
                                                             'text looks '
                                                             'right." CLAIM, '
                                                             'not yet\n'
                                                             '  reported: '
                                                             'the X pattern '
                                                             'tilted against '
                                                             'the torus '
                                                             '(Mode 5 list '
                                                             'in the\n'
                                                             '  chat; '
                                                             'repeated in '
                                                             'section 4).\n'
                                                             '- '
                                                             '**interactive-exhibit '
                                                             '1.10** writes '
                                                             'down the L-265 '
                                                             'info-link '
                                                             'rule.\n'
                                                             '  Its first '
                                                             'copy was '
                                                             'refused by '
                                                             'Settings; '
                                                             'patch_L406_3 '
                                                             'fixed the '
                                                             'header\n'
                                                             '  (pushed '
                                                             '81e19ef).\n'
                                                             '- **Skill '
                                                             'headers '
                                                             'checked as '
                                                             'YAML '
                                                             '(L-407).** '
                                                             'skills_index.py '
                                                             'reads each\n'
                                                             '  header as '
                                                             'YAML and the '
                                                             'maintenance '
                                                             'run gates on '
                                                             'it (20 '
                                                             'checkers).\n'
                                                             '  It found two '
                                                             'more: '
                                                             'earth-system-pipeline '
                                                             '(": " in its '
                                                             'description)\n'
                                                             '  and '
                                                             'provenance-discipline '
                                                             '(" #" cut its '
                                                             'description to '
                                                             '200\n'
                                                             '  characters). '
                                                             'Both quoted; '
                                                             '1.2 and 2.25. '
                                                             'Protocol '
                                                             'v3.79. '
                                                             'VERIFIED: the\n'
                                                             '  check fails '
                                                             'on the old '
                                                             'headers both '
                                                             'ways; pushed '
                                                             'at fd508f9.\n'
                                                             '\n'
                                                             '## 3. The '
                                                             "Sun's distance "
                                                             'cards: what '
                                                             'the next '
                                                             'session '
                                                             'builds\n'
                                                             '\n'
                                                             'Tony pointed '
                                                             'out that the '
                                                             "Sun's cards "
                                                             'print km at '
                                                             'every digit: '
                                                             '"=\n'
                                                             '299,195,741,400 '
                                                             'km (2.00e+3 '
                                                             'AU)". Cause: '
                                                             'the rows carry '
                                                             'no figure '
                                                             'count\n'
                                                             '(10 of 11 have '
                                                             'no Unit line '
                                                             'either, so '
                                                             'they are not '
                                                             'even '
                                                             'exported).\n'
                                                             'The 18 lines '
                                                             'on 15 cards '
                                                             'are listed on '
                                                             'L-371.\n'
                                                             '\n'
                                                             '**Sources read '
                                                             'this session '
                                                             '(Claude Opus '
                                                             '5.5, '
                                                             '2026-10-02/03):**\n'
                                                             '\n'
                                                             '- '
                                                             '`TERMINATION_SHOCK_AU`: '
                                                             'Stone et al. '
                                                             '2005, Science '
                                                             '309, 2017,\n'
                                                             '  abstract '
                                                             '(Caltech '
                                                             'authors '
                                                             'resolver) -- '
                                                             '94.01 AU. '
                                                             'Store 94.01, '
                                                             '4\n'
                                                             '  figures. The '
                                                             'orrery types '
                                                             '"94 AU" in '
                                                             'hovers and '
                                                             'comments.\n'
                                                             '- '
                                                             '`HELIOPAUSE_RADII` '
                                                             '(26,148): '
                                                             'Gurnett et al. '
                                                             '2013, Science '
                                                             '341, 1489,\n'
                                                             '  paper text '
                                                             '-- 121 AU. '
                                                             'Store a new '
                                                             '`HELIOPAUSE_AU` '
                                                             '= 121, 3 '
                                                             'figures;\n'
                                                             '  '
                                                             '`HELIOPAUSE_RADII` '
                                                             'becomes '
                                                             'derived from '
                                                             'it (about '
                                                             '26,000), '
                                                             'keeping\n'
                                                             '  its name for '
                                                             'its ~60 '
                                                             'consumers '
                                                             '(L-386).\n'
                                                             '- '
                                                             '`INNER_LIMIT_OORT_CLOUD_AU` '
                                                             '(2,000) and '
                                                             '`OUTER_OORT_CLOUD_AU`\n'
                                                             '  (100,000): '
                                                             'NASA '
                                                             'science.nasa.gov '
                                                             'Oort Cloud '
                                                             'facts -- inner '
                                                             'edge\n'
                                                             '  between '
                                                             '2,000 and '
                                                             '5,000 AU, '
                                                             'outer edge '
                                                             'between 10,000 '
                                                             'and 100,000\n'
                                                             '  AU. One '
                                                             'figure each. '
                                                             'The cited '
                                                             'Hills (1981) '
                                                             'and Oort '
                                                             '(1950) do not\n'
                                                             '  print these '
                                                             'numbers '
                                                             "(Hills' "
                                                             'abstract '
                                                             'read).\n'
                                                             '- '
                                                             '`INNER_OORT_CLOUD_AU` '
                                                             '(20,000): '
                                                             'Duncan, Quinn '
                                                             'and Tremaine '
                                                             '1987, AJ\n'
                                                             '  94, 1330 -- '
                                                             'the Hills '
                                                             'cloud a < '
                                                             '20,000 AU, the '
                                                             'outer cloud '
                                                             'beyond.\n'
                                                             '  One figure. '
                                                             'Cross-check: '
                                                             'Portegies '
                                                             'Zwart et al. '
                                                             '2021 (below), '
                                                             'sec.\n'
                                                             '  2.2, "inner '
                                                             'edge of the '
                                                             'Oort cloud '
                                                             '(<~20 000 '
                                                             'au)".\n'
                                                             '- '
                                                             '`GRAVITATIONAL_INFLUENCE_AU` '
                                                             '(150,000, no '
                                                             'source, '
                                                             '"visualization\n'
                                                             '  boundary"): '
                                                             'Portegies '
                                                             'Zwart, Torres, '
                                                             'Cai and Brown '
                                                             '2021, A&A '
                                                             '652,\n'
                                                             '  A144, sec. '
                                                             '2.3 and the '
                                                             'captions of '
                                                             'Figs. 3 and 4 '
                                                             "-- the Sun's "
                                                             'Hill\n'
                                                             '  radius in '
                                                             'the Galactic '
                                                             'potential, '
                                                             'about 0.65 pc, '
                                                             'from a full '
                                                             'Galaxy\n'
                                                             '  model; the '
                                                             'outer limit of '
                                                             'the Oort cloud '
                                                             'taken to '
                                                             'coincide with '
                                                             'it\n'
                                                             '  (Chebotarev '
                                                             '1965). Store '
                                                             '`GRAVITATIONAL_INFLUENCE_PC` '
                                                             '= 0.65, 2\n'
                                                             '  figures; '
                                                             '`_AU` derived '
                                                             '(about '
                                                             '134,000). The '
                                                             'old\n'
                                                             '  '
                                                             '`GRAVITATIONAL_INFLUENCE_RANGE_AU` '
                                                             '(100,000-200,000, '
                                                             'unsourced) '
                                                             'and\n'
                                                             '  the orrery '
                                                             'hover that '
                                                             'prints it go. '
                                                             'TRAP: Fig. 4 '
                                                             'also gives an '
                                                             'inner\n'
                                                             '  edge of 0.21 '
                                                             'pc -- a '
                                                             'different '
                                                             'definition '
                                                             '(where the '
                                                             'tide '
                                                             'dominates\n'
                                                             '  in their '
                                                             'model), not '
                                                             "NASA's inner "
                                                             'edge; do not '
                                                             'mix them.\n'
                                                             '- '
                                                             '`ALFVEN_SURFACE_RADII` '
                                                             '(19.7): Kasper '
                                                             'et al. 2021, '
                                                             'PRL 127, '
                                                             '255101,\n'
                                                             '  text -- the '
                                                             'probe moved '
                                                             'from 19.7 to '
                                                             '18.4 solar '
                                                             'radii. 3 '
                                                             'figures.\n'
                                                             '- '
                                                             '`HELMET_CUSP_RADII` '
                                                             '(4.0): the row '
                                                             'quotes Suess '
                                                             'and Nerney '
                                                             '2004 --\n'
                                                             '  helmets '
                                                             '"reach no '
                                                             'higher than '
                                                             '2-4 solar '
                                                             'radii" -- read '
                                                             'at L-224; not\n'
                                                             '  reopened '
                                                             '(not found '
                                                             'online today). '
                                                             'Top of a 2-4 '
                                                             'range: 1 '
                                                             'figure.\n'
                                                             '- '
                                                             '`INNER_CORONA_RADII` '
                                                             '(3): already a '
                                                             'declared '
                                                             'convention '
                                                             '(Lamy);\n'
                                                             '  needs a '
                                                             'print count.\n'
                                                             '- '
                                                             '`OUTER_CORONA_RADII` '
                                                             '(50): Mann et '
                                                             'al. 2004 not '
                                                             'found; the row '
                                                             'calls\n'
                                                             '  it a '
                                                             'visualization '
                                                             'boundary -- '
                                                             'declared '
                                                             'drawing '
                                                             'choice.\n'
                                                             '- '
                                                             '`ROCHE_LIMIT_RADII` '
                                                             '(3.45): '
                                                             'derived from a '
                                                             'comet density '
                                                             'of "~500",\n'
                                                             '  one figure '
                                                             '-- prints as 3 '
                                                             'solar radii.\n'
                                                             '\n'
                                                             "**Tony's "
                                                             'rulings '
                                                             '(2026-10-02/03):**\n'
                                                             '\n'
                                                             '1. Where a '
                                                             'source gives a '
                                                             'range, draw '
                                                             'one end and '
                                                             'say so (option '
                                                             'A,\n'
                                                             '   not both '
                                                             'ends). Build '
                                                             'it by '
                                                             "provenance-discipline's "
                                                             'range rule:\n'
                                                             '   the range '
                                                             'is two rows, '
                                                             'the drawn '
                                                             'value an '
                                                             'expression '
                                                             'over them, '
                                                             'the\n'
                                                             "   end's "
                                                             'reason on the '
                                                             'row, the hover '
                                                             'printing the '
                                                             'range from the '
                                                             'rows.\n'
                                                             '2. The five '
                                                             'notes under '
                                                             'the distance '
                                                             '(shown to '
                                                             'Tony, '
                                                             'approved, '
                                                             'with\n'
                                                             '   the fourth '
                                                             'replaced by '
                                                             'ruling 3):\n'
                                                             '   - Inner '
                                                             'Limit of Oort '
                                                             'Cloud: '
                                                             '"Thought to '
                                                             'lie between '
                                                             '2,000 and\n'
                                                             '     5,000 AU; '
                                                             'drawn at '
                                                             '2,000."\n'
                                                             '   - Outer '
                                                             'Oort Cloud: '
                                                             '"Thought to '
                                                             'lie between '
                                                             '10,000 and '
                                                             '100,000 AU;\n'
                                                             '     drawn at '
                                                             '100,000."\n'
                                                             '   - Streamer '
                                                             'Belt, under '
                                                             'its cusp line: '
                                                             '"Helmets reach '
                                                             'no higher '
                                                             'than\n'
                                                             '     2 to 4 '
                                                             'solar radii; '
                                                             'drawn at 4."\n'
                                                             '   - Outer '
                                                             'Corona: "A '
                                                             'boundary '
                                                             'chosen for the '
                                                             'drawing; the '
                                                             'faint outer\n'
                                                             '     corona '
                                                             'has no sharp '
                                                             'edge."\n'
                                                             '3. '
                                                             'Gravitational '
                                                             'Influence is '
                                                             "the Sun's Hill "
                                                             'radius, '
                                                             'calculated, '
                                                             'not\n'
                                                             '   arbitrary '
                                                             "(Tony's "
                                                             'correction of '
                                                             "Claude's draft "
                                                             '"chosen for '
                                                             'the\n'
                                                             '   drawing"): '
                                                             '0.65 pc, note '
                                                             '"The Sun\'s '
                                                             'Hill radius in '
                                                             'the galaxy,\n'
                                                             '   calculated '
                                                             'where the '
                                                             "galaxy's tidal "
                                                             'pull overtakes '
                                                             "the Sun's\n"
                                                             '   gravity: '
                                                             'about 0.65 '
                                                             'parsecs. '
                                                             'Calculated, '
                                                             'not '
                                                             'measured."\n'
                                                             '4. Build next '
                                                             'session, not '
                                                             'this one: '
                                                             'Claude judged '
                                                             'the session '
                                                             'too\n'
                                                             '   long for a '
                                                             'build this '
                                                             'wide (Tony: '
                                                             '"Confirmed as '
                                                             'recommended").\n'
                                                             '\n'
                                                             '**The build, '
                                                             'in order:** '
                                                             'orrery patch '
                                                             '-- the rows '
                                                             '(Unit, '
                                                             'Status,\n'
                                                             'Figures, Read, '
                                                             'Source), the '
                                                             'range rows, '
                                                             'the two '
                                                             're-homes, the '
                                                             "orrery's\n"
                                                             'hovers '
                                                             'printing by '
                                                             'count as '
                                                             "Earth's do, "
                                                             'tests that pin '
                                                             'old values;\n'
                                                             'then the '
                                                             'gallery patch '
                                                             '-- the notes '
                                                             'from the range '
                                                             'rows, the '
                                                             "shapes'\n"
                                                             '"From ... to '
                                                             '..." lines by '
                                                             'served count, '
                                                             'mirror, cache '
                                                             'rebuild. Tony\n'
                                                             'confirms the '
                                                             'words of any '
                                                             'hover not '
                                                             'listed above.\n'
                                                             '\n'
                                                             '## 4. Open, in '
                                                             'order\n'
                                                             '\n'
                                                             '1. **The build '
                                                             'in section '
                                                             '3.**\n'
                                                             "2. **Tony's "
                                                             'Mode 5 look at '
                                                             'the tide**, if '
                                                             'not done: in '
                                                             'the Sun room,\n'
                                                             '   tick the '
                                                             'tide and the '
                                                             'Hills torus, '
                                                             'turn until the '
                                                             'tide shows an '
                                                             'X;\n'
                                                             '   its centre '
                                                             'line should be '
                                                             'tilted about '
                                                             '60 degrees '
                                                             'against the '
                                                             'torus,\n'
                                                             '   and the '
                                                             'ends of its '
                                                             'axis thin.\n'
                                                             '3. The '
                                                             "drawer's small "
                                                             'fixes and the '
                                                             'Home design '
                                                             'talk, as the\n'
                                                             '   2026-10-02 '
                                                             'handoff lists '
                                                             'them.\n'
                                                             '\n'
                                                             '## 5. '
                                                             'Discrepancies '
                                                             'surfaced this '
                                                             'session\n'
                                                             '\n'
                                                             '- patch_L406_1 '
                                                             'broke '
                                                             "interactive-exhibit's "
                                                             'header: Claude '
                                                             'read the\n'
                                                             '  header cut '
                                                             'off at 80 '
                                                             'characters and '
                                                             'took it to be '
                                                             'wrapped. Fixed '
                                                             'by\n'
                                                             '  '
                                                             'patch_L406_3; '
                                                             'L-407 makes '
                                                             'the class fail '
                                                             'the run.\n'
                                                             '- patch_L406_3 '
                                                             'was replaced '
                                                             'by '
                                                             'patch_L407_1 '
                                                             'in chat, but '
                                                             'Tony had\n'
                                                             '  already run '
                                                             'it; '
                                                             'patch_L407_1 '
                                                             'then refused '
                                                             '(correctly) '
                                                             'and was '
                                                             'rebuilt\n'
                                                             '  as '
                                                             'patch_L407_2.\n'
                                                             "- Claude's "
                                                             'first draft '
                                                             'called '
                                                             'Gravitational '
                                                             'Influence "a '
                                                             'boundary\n'
                                                             '  chosen for '
                                                             'the drawing". '
                                                             'Tony: a Hill '
                                                             'sphere is '
                                                             'computed from '
                                                             'basic\n'
                                                             '  physics. '
                                                             'Corrected '
                                                             'before '
                                                             'anything was '
                                                             'built.\n'
                                                             '- Claude '
                                                             'offered option '
                                                             'A or B for the '
                                                             'Oort ranges '
                                                             'without first\n'
                                                             '  stating the '
                                                             "skill's range "
                                                             'rule (midpoint '
                                                             'unless the row '
                                                             'gives a\n'
                                                             '  reason for '
                                                             'an end). '
                                                             'Ruling A '
                                                             'stands: each '
                                                             'end has a '
                                                             'stated reason\n'
                                                             '  (the cloud '
                                                             'drawn at its '
                                                             'widest '
                                                             'possible '
                                                             'reach).\n'
                                                             '\n'
                                                             'Session/entry '
                                                             'written '
                                                             'October 2026 '
                                                             'with '
                                                             "Anthropic's "
                                                             'Claude Opus '
                                                             '5.5.\n'}


def fingerprint(raw):
    return hashlib.md5(raw.replace(b"\r\n", b"\n")).hexdigest()


def main():
    if os.path.basename(os.getcwd()) == "documentation":
        raise SystemExit("ERROR: run this from the ORRERY repo ROOT, next to "
                         "palomas_orrery.py -- not from documentation/. "
                         "NOTHING was written.")
    if not os.path.isfile("palomas_orrery.py"):
        raise SystemExit("ERROR: palomas_orrery.py is not here, so this is "
                         "not the orrery root. NOTHING was written.")
    for path in NEW_FILES:
        if os.path.exists(path):
            raise SystemExit("ERROR: %s already exists. If this patch already "
                             "ran, it has nothing left to do. NOTHING was "
                             "written." % path)
    results = []
    for path in sorted(EDITS):
        with open(path, "rb") as handle:
            raw = handle.read()
        got = fingerprint(raw)
        if got != BASE[path]:
            raise SystemExit(
                "ERROR: %s is not the file this patch was built against.\n"
                "       expected %s, found %s. It has changed since\n"
                "       fd508f9c, or this patch has already run.\n"
                "       (Line endings are excluded, so they are not the cause.)\n"
                "       NOTHING was written." % (path, BASE[path], got))
        nl = "\r\n" if b"\r\n" in raw else "\n"
        text = raw.decode("utf-8").replace("\r\n", "\n")
        done = []
        for label, old, new in EDITS[path]:
            if text.count(old) != 1:
                raise SystemExit("ANCHOR FAIL (%s): expected 1 match in %s, "
                                 "found %d. NOTHING was written."
                                 % (label, path, text.count(old)))
            text = text.replace(old, new)
            done.append(label)
        if any(ord(ch) > 127 for ch in text):
            raise SystemExit("ERROR: %s would hold non-ASCII text. NOTHING "
                             "was written." % path)
        results.append((path, text.replace("\n", nl), done))
    for path, text, done in results:
        with open(path, "wb") as handle:
            handle.write(text.encode("utf-8"))
        for label in done:
            print("ok  %-40s %s" % (path, label))
    for path, content in sorted(NEW_FILES.items()):
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        print("ok  %s created" % path)
    print("")
    print("patch applied")
    print("")
    print("NEXT:")
    print("  1. Run orrery_maintenance_run.py (VS Code, Run). It updates")
    print("     one date in the ledger's index. Expect 20 of 20.")
    print("  2. Move this script into documentation/; commit and push.")

if __name__ == "__main__":
    main()
