"""Record the 2026-09-15/16 sessions in the ledger and the master plan.

Targets, in the ORRERY repo:
  LEDGER_CONSOLIDATED.md
  documentation/MASTER_PLAN_INTERACTIVE_GALLERY.md
Built against orrery cce6a933216f2d21b8abfabbc48781faa4b5fe92, with the
gallery at 52e953a71630fe2aa616a962cbba59aad56a3fcd.
Handles: L-316, L-318, L-231, L-305, L-267 (a pointer only), and two new
items, L-331 and L-332.
2026-09-16, with Anthropic's Claude Opus 5.

WHAT IT WRITES
--------------
LEDGER (detail blocks only; the index is regenerated by ledger_index.py)
  L-316  rounds 3 and 4 of the arrow cross, with Tony's words and the
         Mode 5 results; the Gap keeps the desktop look and asks Tony
         whether to close.
  L-318  rounds 3 to 6: the drawer row, soft line breaks, the phone's
         text box without its arrow, and phone taps that reach the
         marker. Loose ends re-homed to L-331 and L-332; asks Tony
         whether to close.
  L-231  the 2026-09-15 build, from its handoff; two findings of
         2026-09-16 (Jupiter's belts now differ between the instruments;
         two renderers missed the hover-to-panel move). The Gap narrows
         to Jupiter.
  L-305  a note that items 5 and 6b shipped on 2026-09-15.
  L-267  a pointer: G2 amended in one case by L-318 round 3.
  L-331  NEW: stale visitor text, four Sun hovers, and a checker that
         never builds the Sun room.
  L-332  NEW: the interactive-exhibit skill still describes the chrome
         as it was on 2026-09-11.

MASTER PLAN
  The front page no longer says the magnetosphere is absent. The status
  line said v30 under a v31 stamp; both now say v32. The rolling stamp
  gains v32 and drops v29, keeping three. Section 5a gains the
  2026-09-15/16 subsection. Nothing else in the plan is touched; its
  other mentions of the magnetosphere are dated history.

  The plan was NOT read in full before this was written. Read: the front
  page, the rolling stamp, Section 5a from 2026-09-09 on, and the ledger
  skill's rule that the plan restamps once per design build. Every other
  mention of what these sessions changed was found by searching the
  whole file.

AFTER RUNNING
-------------
  python ledger_index.py LEDGER_CONSOLIDATED.md
    -- expect 327 L-blocks and no consistency problems (325 before).
  Then push, and read the new orrery SHA back.

UNDO: Discard Changes on the two files in GitHub Desktop.
"""

import hashlib
import os
import sys

LEDGER = "LEDGER_CONSOLIDATED.md"
PLAN = "documentation/MASTER_PLAN_INTERACTIVE_GALLERY.md"

FINGERPRINTS = {
    LEDGER: "3559022cb974e5f51d90e7286fade090",
    PLAN: "21b08004b071af7fb83558dcd8f79e5f",
}

GUARD = [(LEDGER, "#### [L-331]"), (PLAN, "### 2026-09-15/16 --")]

NEW_ITEMS = b"""#### [L-332] interactive-exhibit skill 1.3: carry the phone chrome of 2026-09-15/16 (skills)
<!-- L:332 status:OPEN upd:2026-09-16 section:A flag: rice:2/2/90/1 -->
- `skills/interactive-exhibit/SKILL.md` 1.2 (2026-09-11) describes the
  rooms' chrome as L-316 round 2 and L-318 rounds 1 and 2 left it. Since
  then [verified @ gallery `52e953a7`]:
  - the arrow cross is placed by `crossApart(on)` and the CSS rule
    `.nav-cross-apart`, called with `sunPhonePortrait()`, the phone test
    the text box also uses. The corner is top right again (L-316 rounds
    3 and 4); `crossRight` and `sunCrossRight` no longer exist;
  - a drawer row has a selection target about 65 px wide, rows are at
    least 44 px tall, and the name or GO on an unticked shell ticks it
    (L-318 round 3, amending L-267's G2 in that case);
  - line breaks inside a sentence are `GalleryFeatures.SOFT_BR`, and the
    phone's text box rejoins them (L-318 round 4);
  - on a portrait phone the text box has no arrow and sits mid-view; the
    desktop keeps the arrowed scene label (L-318 round 5);
  - on a portrait phone a tap can pick only markers that carry text,
    within 22 px, through Plotly's internals -- a second Plotly rule for
    the touch-path section (L-318 round 6);
  - the hover budget suite takes `interactive.html` and has three more
    legs;
  - Tony's standing rule of 2026-09-16: no compressed language in hover
    text (L-331). `orrery-coding-conventions` carries the orrery's hover
    conventions and may need the same line.
**Note:** RICE 2/2/90/1 -> 3.6 is Claude's proposed score. The
pre-built-session rule says to bump a skill before the next build that
relies on it; the next build touching the rooms' chrome is L-331.
**Gap:** the skill edit, then `skills_index.py`.
  **Tony-action (do):** reinstall the skill after the bump.
**Ref:** L-316, L-318, L-331, `skills/interactive-exhibit/SKILL.md`,
`skills_index.py`, `PROJECT_INSTRUCTIONS.md`.

#### [L-331] Visitor-facing text: stale info text, four Sun hovers outside the i-panel move, and hovers in plain language (exhibits)
<!-- L:331 status:OPEN upd:2026-09-16 section:A flag: rice:3/3/90/2 -->
- **Found 2026-09-15/16, reading the code for the 2026-09-15 handoff's
  change (c).** The handoff named one stale sentence. There are more, in
  `interactive.html` [verified @ gallery `52e953a7`]:
  - `EARTH_INFO_HTML` still says the magnetosphere is not drawn yet and
    describes what the desktop orrery draws instead, and its list of what
    waits in the drawer leaves out the magnetopause and the bow shock;
  - `EARTH_INFO_HTML` and `SUN_INFO_HTML` both say a shell carries its
    source in its hover text, and the Sun's says the sources are named in
    each hover. Since the 2026-09-15 hover-to-panel move (L-231) the i
    panel carries them;
  - the drawer sentence ("Tap one and it draws; the view rescales to hold
    it") should be re-read against L-318 round 3.
- **Four Sun hovers missed that move.** `renderStreamerBand` and
  `renderOortShape` in `gallery/feature_renderers.js` never call
  `withTail`. So the Streamer Belt, the Hills Cloud torus, the Outer Oort
  Cloud clumps and the Galactic Tide keep their citations in the hover
  and lack the pointer line. [verified @ gallery `52e953a7`]
- **The check that should have caught it never looks.**
  `documentation/smoke_hover_budget.js` builds the Earth scene, Earth's
  features, and Jupiter and Saturn -- never the Sun room -- so its "every
  hover points at the i panel" leg passes. [verified @ gallery `52e953a7`]
- **Tony, 2026-09-16:** "galactic tide is a built interactive and should
  be correct. But declared not measured means little to a visitor." The
  Sun room is live, so this is not a nice-to-have. The Galactic Tide's
  hover opens "DECLARED --" and closes "Not a measurement."; the caveat
  stays beside the number, but in words a visitor can use.
- **Proposed wording (Claude), for Tony's word:** "Drawn at 50,000 AU
  (7.48e+12 km): a point chosen for the picture, midway between the Hills
  cloud and the cloud's outer edge. It is not a measured distance." --
  "Drawn at" as the belts' hovers already say it, and no capitalised
  label.
- **Tony, 2026-09-16, a standing rule: "In general we should avoid
  compressed language in the hovertext."** It is the protocol's Register
  Rule, which governs how Claude writes to Tony, applied to what a
  visitor reads. A hover names the thing and says it plainly; project
  vocabulary and capitalised labels are compression. Counted in the hovers
  the gallery builds [verified @ gallery `52e953a7`]: "served" in 14
  hovers ("the served pole", "served as L = 4.5", "none is served"),
  "sourced" in 5 ("the sourced flux peak", "Sourced span"), "drawing
  choice" and "illustrative" in 5 each (the belts, Earth's and Jupiter's),
  capitalised labels in 4 ("DECLARED" on the Galactic Tide, "A DRAWING
  LIMIT" on the magnetopause and the bow shock, "FROZEN" on the
  terminator), and "L shell", "osculating" and "trusted arc" once each.
  The Moon's hover is built by the assembler (`render_orbits.py`), not the
  renderers, and the orrery's own hovers (L-321) are where the rule
  reaches next; neither was counted here.
- **Proposed (Claude) for the build.** Move the other three Sun hovers'
  citations to the panel, add the pointer line to all four, and add the
  Sun room to the hover budget suite. Then a plain-language pass over
  every hover the renderers and `earth_geometry.js` build, keeping each
  hover's facts and its caveats -- the rule changes the words, not what
  is said. Then rewrite the stale info sentences the same way. Wording
  goes to Tony before it ships.
- **Recorded, not taken.** Tony's idea of 2026-09-16, to trim every text
  box to its key data and move the rest to the i panel (see L-318).
**Note:** RICE 3/3/90/2 -> 4.05 is Claude's proposed score: Impact raised
from 2 on Tony's remark that the Sun room is a built interactive, Effort
raised from 1 by the plain-language pass.
**Gap:** the build above, then Mode 5 on the phone in both rooms.
  **Tony-action (decide):** the reworded hovers, starting with the
  Galactic Tide's.
**Ref:** L-231 (the hover-to-panel move), L-305, L-318, L-332,
`interactive.html` (`EARTH_INFO_HTML`, `SUN_INFO_HTML`),
`gallery/feature_renderers.js` (`renderStreamerBand`, `renderOortShape`,
`withTail`, `HOVER_TAIL`), `documentation/smoke_hover_budget.js`,
`documentation/HANDOFF_L231_L305_magnetosphere_and_belts_20260915.md`
(STILL OPEN, item 1c).

"""

L316_ADD = b"""- **Round 3, built 2026-09-15** by `patch_L316_3_cross_bottom_left.py`
  in the gallery. Tony, from the phone on 2026-09-15: "move the arrow
  cross to the bottom left above the drawer." A text box that could not
  fit beside its marker opened over it, and at the top right the cross was
  drawn over the magnetopause's text. The cross alone moved, and only on
  a portrait phone; + and - stayed at the top left. The 2026-09-15
  handoff had widened the ruling to "the navigation cluster"; the next
  session caught that before building. The build also found that the
  page's drawer-open rule hid the cluster but never reached the moved
  cross's own holder, and gave the holder its own rule. `crossRight`
  became `crossBottomLeft`. Sandbox: a stand-in page using the page's own
  style block -- the holder's corner and height, hidden while the drawer
  is open, back under + and - in landscape, the phone test at four screen
  sizes. The cross appears there in Tony's phone screenshots of
  2026-09-15. [verified in the sandbox @ gallery `97867f3e` + the patch]
- **Round 4, built 2026-09-16** by
  `patch_L316_4_cross_top_right_again.py` in the gallery. Once the
  phone's text box sat mid-view with no arrow (L-318 round 5), Tony:
  "let's put the arrow cross back where it was on the top right. there is
  more room for it there in terms of the figure itself, if we are not
  accommodating the text box." Round 2's corner is restored exactly. The
  drawer-open rule is kept, so all of the navigation steps aside together
  (Tony: "it's okay as-is"). The method is renamed a last time, to
  `crossApart(on)` with the class `nav-cross-apart`: names that say
  nothing about the corner, which is now set only by that class's CSS
  rule in `gallery/nav_cluster.js`. The page's `sunCrossBottomLeft()` is
  gone; `navPlaceCross()` asks `sunPhonePortrait()`, the test the text
  box also uses.
- **Round 4 passes on the phone, 2026-09-16.** Tony: "correct. this is a
  more intuitive and elegant view. and hides less." A marker tapped near
  the top right, whose Plotly box could open under the cross: "no issues
  detected". [render-confirmed Mode 5 @ gallery `082dff59`]
**Gap:** desktop, not yet looked at on its own: title and cross exactly as
before -- this also covers L-310's desktop check. The 2026-09-16 look
covered the desktop's mouse hover, not the title and the cross.
  **Tony-action (decide):** after that look, close L-316.
**Ref:** L-310, L-313 (recentering may add a control to the cluster),
L-267, L-289, L-317, L-318 (its round 5 is why round 4 happened),
`gallery/nav_cluster.js` (`crossApart`, `.nav-cross-apart`),
interactive.html (`sunPhonePortrait`, `navPlaceCross`, `EARTH_INFO_HTML`),
`documentation/patch_L316_cross_and_borders.py`,
`documentation/patch_L316_2_cross_right.py`,
`patch_L316_3_cross_bottom_left.py` and
`patch_L316_4_cross_top_right_again.py` (gallery).
"""

L318_ADD = b"""- **Round 3, built 2026-09-15: the drawer row.** Tony, from the phone:
  the selection box was hard to hit, the finger landed on the name, and a
  name tap on an unticked shell moved the camera but drew nothing -- a tap
  that read as doing nothing. Measured in the page: the box was 18 px
  square, and every pixel around it, the 16 px to its left included,
  belonged to the name; "go" was only a label, and the name did exactly
  what GO did. A first idea, a one-target row with no box, was withdrawn
  once Tony described his use: tick several shells, then go to one. His
  rulings, each "yes": (1) the row's whole left end -- its edge, the box
  and the colour dot, the full row height, about 65 px -- ticks and
  unticks; (2) rows are at least 44 px tall; (3) the name or GO on an
  unticked shell ticks it too, which AMENDS L-267's G2 in that one case,
  and GO still never hides anything; (4) ticking never closes the drawer;
  (5) GO frames on the shell, in or out, as before -- an earlier "move
  only when too big" ruling, made for the one-target row, went with it.
  And one detail: "when we tap outside the drawer or outside the text
  box, it closes the text box and the drawer if still open." The
  backdrop now closes both; a tap on the text box itself still closes it,
  as before. Built by `patch_L318_3_drawer_row_targets.py` in the
  gallery. Sandbox: a stand-in page running the page's own drawer
  functions, markup and styles, 25 checks, failing on the unpatched page.
  A leftover copy from an abandoned attempt,
  `patch_L331_drawer_row_targets.py`, missed the backdrop detail; it was
  never run or committed. Mode 5, 2026-09-15, each check: "correct".
  [render-confirmed Mode 5 @ gallery `c730a6ab`]
- **Round 4, built 2026-09-15: soft line breaks.** Tony, with phone
  screenshots: the belts' text boxes ran off the screen, full of orphan
  words, and the crust showed the same. The text was wrapped twice: at 70
  characters for the desktop box (and by hand inside sentences in places)
  and again at 34 by the phone's label. A break that only keeps a desktop
  line short is now `GalleryFeatures.SOFT_BR` (`<br soft>`). Plotly draws
  it as a line break -- its text splitter reads a tag's name up to the
  first space (plotly.js 2.35.2, `src/lib/svg_text_utils.js`) -- and the
  label turns it back into a space. Swept through `wrapHover`, the pointer
  line under every hover, the belts, the GEO ring, the magnetopause, the
  bow shock and the Earth scene's four hand-wrapped hovers. All 68 desktop
  boxes are unchanged, line for line. The hover budget suite now counts a
  soft break as a line, fails on a hard break inside a sentence, and
  measures the phone's labels with the page's own wrapper;
  `gallery_maintenance_run.py` passes it `interactive.html`. Label lines
  at 34 characters, measured: outer belt 28 -> 26, rotation axis
  28 -> 26, inner belt 25 -> 23, the Sun's galactic tide 11 -> 10; 34 of
  38 unchanged. Built by `patch_L318_4_soft_breaks.py` in the gallery.
  Tony, after: the text reads in sentences, but "some text boxes remain
  too large even after line break adjustment". [render-seen @ gallery
  `29614e5`]
- **Round 5, built 2026-09-15: on a portrait phone the text box has no
  arrow and sits mid-view.** Tony's screenshots showed a tall box cut off
  at the side (the outer belt, the Sun's gravitational influence) and at
  the bottom (both belts), and a view where Plotly drew no arrow. Beside
  its marker a box held about 16 lines (Tony). Tony: the arrow "is very
  useful but it is not indispensable"; "Why don't we start by just
  removing the arrow to the marker. And we can see how it reads."; and
  "can we leave the desktop as-is?" On a portrait phone
  (`sunPhonePortrait()`) the box is a page-level annotation centred in
  the view -- same text, same width, border in the shell's colour. The
  desktop and a phone held landscape keep the scene label with its arrow;
  the desktop label is the same object as before. Turning the phone swaps
  the two forms and empties the one not in use. Knobs:
  `SUN_LABEL_PHONE_X` and `SUN_LABEL_PHONE_Y` (0.5 each), and
  `SUN_LABEL_WRAP_CHARS` (34, which also sets the desktop label's width).
  Built by `patch_L318_5_phone_label_no_arrow.py` in the gallery; a
  stand-in ran 16 checks of the page's own label functions. Mode 5,
  2026-09-16: "all look good"; the whole box on screen -- "yes"; without
  the arrow -- "it read okay"; it can cover the arrow buttons and the
  grid chip -- "correct". [render-confirmed Mode 5 @ gallery `a4ef8cfc`]
- **Round 6, built 2026-09-16: a phone tap reaches the marker.** Without
  the arrow, Tony: tapping a marker cross is "trial and error". Read from
  plotly.js 2.35.2: a 3D tap takes the drawn point nearest the finger
  within gl-plot3d's `pickRadius` (10 px, set by
  `src/plots/gl3d/scene.js`; the pick buffer is in screen pixels) from
  every trace, and only then does scene.js drop a pick whose trace has
  hoverinfo 'skip' -- so a shell's text-less dots win the tap. On a
  portrait phone only (Tony: "leave the desktop as-is. the reason is that
  the mouse pointer is fine enough to pick out the marker"), text-less
  traces draw nothing into the pick buffer, and the search widens to
  `SUN_PICK_RADIUS_PX` = 22 px. This reaches into Plotly's internals
  (`gd._fullLayout.scene._scene`: `glplot.pickRadius`, `glplot.update`,
  each WebGL object's `drawPick`); it is re-applied after every plot and
  does nothing if those are not where 2.35.2 keeps them. Built by
  `patch_L318_6_phone_tap_picking.py` in the gallery; a stand-in with a
  tap search copied from Plotly's rule ran 22 checks. Mode 5, 2026-09-16:
  "always opens on first tap. much improved."; a tap on empty space still
  closes a box -- "correct"; landscape and the desktop's mouse hover --
  "correct". [render-confirmed Mode 5 @ gallery `52e953a7`]
- **What this leaves.** The "still open" line above, a marker tap's own
  Plotly box losing its pointer, is overtaken: the phone's taps now land,
  and Tony saw no problem with that box. Two loose ends go to open items:
  the four Sun hovers and the stale visitor text (L-331), and the
  interactive-exhibit skill, which still describes rounds 1 and 2
  (L-332). An idea Tony raised and did not take is recorded in L-331:
  trim each text box to its key data and move the rest to the i panel.
  Tony: "16 lines is the limit with an arrow to its marker. Without that
  constraint it could be longer."
**Gap:** none left here once L-331 and L-332 carry the two loose ends.
  **Tony-action (decide):** close L-318.
**Ref:** L-267 (the drawer and focus; G2 amended by round 3), L-278,
L-316, L-317, L-319, L-320, L-331, L-332, `interactive.html`
(`sunFocusOn`, `sunLabelShow`, `sunLabelWrap`, `sunLabelRefresh`,
`sunLabelRelayout`, `sunPhonePortrait`, `sunTapPicking`,
`buildSunDrawer`), `gallery/feature_renderers.js` (`wrapHover`,
`HOVER_WIDTH`, `SOFT_BR`), `gallery/earth_geometry.js`,
`documentation/smoke_hover_budget.js`; plotly.js v2.35.2
`src/components/fx/hover.js`, `src/plots/gl3d/scene.js`,
`src/components/annotations3d/attributes.js`,
`src/lib/svg_text_utils.js` and `stackgl_modules/index.js` (the pick
pass); `documentation/patch_L318_drawer_label.py` and
`patch_L318_2_arrow_colour.py` through
`patch_L318_6_phone_tap_picking.py` (gallery).
"""

L231_NEW = b"""- **Built 2026-09-15**
  [per `documentation/HANDOFF_L231_L305_magnetosphere_and_belts_20260915.md`].
  Earth's belts are drawn about the spin axis in both instruments; the
  dipole tilt is a store row (IGRF-13), quoted with its epoch in the belt
  hover; a flat unit ring through `orient_to_planet_pole` measured 23.439
  degrees from the ecliptic pole. The same session moved every citation,
  model equation and served caveat from the hover to the i panel, with
  one pointer line under each hover (`patch_L231_hover_to_panel.py`), and
  added the hover budget suite, the line-width rule's missing twin
  (`patch_L231_hover_budget_checker.py`; ceiling 17, a ratchet that only
  comes down); `patch_L231_dashboard_hover_budget.py` is its orrery
  companion. Tony's phone screenshots of 2026-09-15 and 2026-09-16 show
  the belts' text boxes quoting 9.6 degrees with IGRF-13 and its epoch.
- **Found 2026-09-16: the two instruments now disagree about JUPITER's
  belts.** The gallery's `renderBelts` serves every planet, so the pass
  flattened Jupiter's belts too and put them in Jupiter's equatorial
  plane. The orrery's `create_jupiter_radiation_belts` was not touched:
  it still adds `0.2 * r * sin(2 * angle)` of warp and applies no pole
  rotation. No visitor sees it yet -- Jupiter has no room -- but this
  item's own record says a change to the belts' orientation must reach
  both instruments in the same pass. [verified @ orrery `cce6a933`,
  gallery `52e953a7`]
- **Found 2026-09-16: the hover-to-panel move missed two renderers.**
  `renderStreamerBand` and `renderOortShape` never call `withTail`, so
  four Sun hovers keep their citations and lack the pointer line, and
  the hover budget suite never builds the Sun room, which is why it
  passed. Carried by L-331. [verified @ gallery `52e953a7`]
**Note:** RICE 2/2/90/2 -> 1.8 is Claude's proposed score.
**Gap:** Earth is built. What remains is Jupiter's orrery belt builder --
spin axis, warp removed, hover reworded -- to match the gallery. Tony,
2026-09-16: "Jupiter can wait." It waits for Jupiter's room, and that
room's build must do it before the room ships. (The build Gap this
replaced: spin-axis basis in both instruments, warp removed, hover
reworded, both code comments corrected, one pass, then Mode 5 -- done for
Earth.)
"""

L305_ADD = b"""**Note (2026-09-16) -- items 5 and 6b shipped on 2026-09-15**
[per `documentation/HANDOFF_L231_L305_magnetosphere_and_belts_20260915.md`].
The renderer draws Shue's magnetopause and Jelinek's bow shock from
eleven served rows, with no number typed into it; the magnetopause stops
at 120 degrees from the nose, the furthest the authors plot their own
model, declared rather than measured. That session measured each nose on
its served standoff within a fifth of a percent, each cut within half a
degree, and each surface a true surface of revolution about the Sun line.
Since then the Earth scene checker passes with the magnetosphere drawn
and 20 drawer groups [verified @ gallery `97867f3e`, and on every patched
tree through `52e953a7`], and Tony opened the magnetopause's text box on
the phone on 2026-09-16: "all look good". What else item 6b owes was not
re-derived here; read that handoff's STILL OPEN list before working this
item.
"""

L267_ADD = b"""- **Note (2026-09-16):** G2 is amended in one case by L-318 round 3
  (Tony, 2026-09-15): a tap on the name or GO of an UNTICKED shell now
  ticks it before going there. GO still never hides anything, and
  `sunFocusOn` itself still switches nothing on; the drawer does it.
"""

EDITS = [
    (LEDGER, [
        (b"""## A. ACTIVE SEPARATE TRACKS (not orrery-refactor backlog; cross-referenced)

#### [L-330]""",
         b"""## A. ACTIVE SEPARATE TRACKS (not orrery-refactor backlog; cross-referenced)

""" + NEW_ITEMS + b"""#### [L-330]"""),
        (b"""<!-- L:231 status:OPEN upd:2026-09-15 section:A flag: rice:2/2/90/2 -->""",
         b"""<!-- L:231 status:OPEN upd:2026-09-16 section:A flag: rice:2/2/90/2 -->"""),
        (b"""**Note:** RICE 2/2/90/2 -> 1.8 is Claude's proposed score.
**Gap:** not a sourcing round and no longer a question. BUILD: spin-axis
basis in both instruments, warp removed, hover reworded (the false L
sentence, the typed width named as a drawing choice beside the sourced
span, the 9.6 degrees as a sentence), both code comments corrected. One
pass, then Mode 5.
""", L231_NEW),
        (b"""<!-- L:305 status:OPEN upd:2026-09-12 section:A flag: rice:4/4/60/4 -->""",
         b"""<!-- L:305 status:OPEN upd:2026-09-16 section:A flag: rice:4/4/60/4 -->"""),
        (b"""**Ref:** L-291, L-292, L-298 (the orrery-vs-exhibit gap, made concrete),
""",
         L305_ADD + b"""**Ref:** L-291, L-292, L-298 (the orrery-vs-exhibit gap, made concrete),
"""),
        (b"""<!-- L:316 status:OPEN upd:2026-09-10 section:A flag: rice:3/2/80/1 -->""",
         b"""<!-- L:316 status:OPEN upd:2026-09-16 section:A flag: rice:3/2/80/1 -->"""),
        (b"""**Gap:** desktop, not yet looked at: title and cross exactly as before --
this also covers L-310's desktop check.
**Ref:** L-310, L-313 (recentering may add a control to the cluster),
L-267, L-289, L-317, `gallery/nav_cluster.js` (`crossRight`),
interactive.html (`sunCrossRight`, `navPlaceCross`, `EARTH_INFO_HTML`),
`documentation/patch_L316_cross_and_borders.py` and
`documentation/patch_L316_2_cross_right.py` (gallery).
""", L316_ADD),
        (b"""<!-- L:318 status:OPEN upd:2026-09-10 section:A flag: rice:3/2/70/2 -->""",
         b"""<!-- L:318 status:OPEN upd:2026-09-16 section:A flag: rice:3/2/70/2 -->"""),
        (b"""**Gap:** the marker-tap pointer question above.
**Ref:** L-267 (the drawer and focus), L-278, L-316, L-317, L-319, L-320,
`interactive.html` (`sunFocusOn`, `sunLabelShow`, `sunLabelInstall`),
`gallery/feature_renderers.js` (`wrapHover`, `HOVER_WIDTH`), plotly.js
v2.35.2 `src/components/fx/hover.js`, `src/plots/gl3d/scene.js` and
`src/components/annotations3d/attributes.js`,
`documentation/patch_L318_drawer_label.py` (gallery).
""", L318_ADD),
        (b"""<!-- L:267 status:DONE upd:2026-09-04 section:C flag: rice:4/3/85/3 -->""",
         b"""<!-- L:267 status:DONE upd:2026-09-16 section:C flag: rice:4/3/85/3 -->"""),
        (b"""- **Note:** RICE 4/3/85/3 -> 3.4 proposed, not confirmed.
""",
         L267_ADD + b"""- **Note:** RICE 4/3/85/3 -> 3.4 proposed, not confirmed.
"""),
    ]),
    (PLAN, [
        (b"""**Status:** v30 -- Phase 2""",
         b"""**Status:** v32 -- Phase 2"""),
        (b"""`57fd93c6`). The magnetosphere is absent and named until its rebuild
on a cited model (L-305). Earth made""",
         b"""`57fd93c6`). Its magnetosphere, absent and named at launch, has been
drawn from the store since 2026-09-15 -- Shue's magnetopause and
Jelinek's bow shock (L-305). Earth made"""),
        (b"""**Last updated:** September 11, 2026 (v31: a DESIGN SESSION, zero code.
""",
         b"""**Last updated:** September 16, 2026 (v32: two BUILD sessions and the
record that closes them. Earth's magnetosphere is drawn from the store --
Shue's magnetopause and Jelinek's bow shock, eleven served rows, no
number typed into the renderer (L-305 items 5 and 6b, 2026-09-15) -- and
Earth's belts moved into its equatorial plane (L-231). Citations left the
hover for the i panel, and a hover budget suite joined the maintenance
run. Then the phone chrome settled on Tony's Mode 5 (2026-09-15/16): the
drawer row became easy to hit, text boxes stopped breaking mid-sentence,
the phone's text box lost its arrow and moved mid-view, the arrow cross
went back to the top right, and a phone tap now reaches a shell's marker
instead of its dots (L-316 rounds 3 and 4, L-318 rounds 3 to 6). The
front page no longer says the magnetosphere is absent, and the status
line, which said v30 under a v31 stamp, now matches. The 2026-09-12
subsection went in without a stamp; the 2026-09-13/14 sessions (L-305
item 7) are recorded in the ledger and in
`HANDOFF_L305_item7_built_20260914.md`, not in Section 5a. Section 5a
gains the 2026-09-15/16 subsection; with Anthropic's Claude Opus 5.
v31, September 11, 2026: a DESIGN SESSION, zero code.
"""),
        (b"""Anthropic's Claude Opus 5. v29, September 10, 2026: the Earth BUILD closes.
Step 3 built and through three Mode 5 rounds; L-168 fixed at source
on the first moon it could affect; the card made in Studio after a
copied card hid from the desktop lobby; L-291 and L-303 closed on
Tony's Mode 5; loose ends re-homed to L-311, L-312, L-237 and L-288;
next track the L-310 camera-step design round; two handoff locations
corrected; Section 5a gains the 2026-09-09/10 subsection; with
Anthropic's Claude Opus 5.)
""",
         b"""Anthropic's Claude Opus 5.)
"""),
        (b"""### What this section deliberately does not carry
""",
         b"""### 2026-09-15/16 -- the magnetosphere is drawn, and the phone chrome settles

**Earth's magnetosphere reached the exhibit on 2026-09-15** (L-305 items
5 and 6b; `HANDOFF_L231_L305_magnetosphere_and_belts_20260915.md`). The
research had been done on the tenth and eleventh; nobody had served the
coefficients or written the code that turns them into a shape. Both
surfaces are now drawn from eleven served rows with no number typed into
the renderer, and the magnetopause stops at 120 degrees from the nose --
the furthest the authors plot their own model, declared, not measured.
The same session put Earth's belts in its equatorial plane (L-231): the
geostationary ring is drawn there at 6.6 Earth radii, inside an outer
belt served as spanning 3 to 7, and the ecliptic had put the two 23.4
degrees apart in one picture. Earth's dipole tilt became a store row,
quoted in the belt hover with its epoch. And the hover became the
glance: every citation, equation and served caveat moved to the i panel,
with one pointer line under each hover.

**That session's lesson: a checker exists for the failure you already
had.** Three checks passed while the thing they guarded was broken -- a
line-width rule on a hover that ran off the phone, a scene checker on a
month-old fixture, a "Source:" leg true only because the fixture had no
sources. It showed again on 2026-09-16: the new hover budget suite never
builds the Sun room, and four Sun hovers had missed the move to the panel
(L-331).

**The phone chrome settled on 2026-09-15/16, on Tony's Mode 5 each
round.** The drawer row got a finger-sized selection target, and a name
tap on an unticked shell now ticks it (L-318 round 3, amending L-267's
G2). Text boxes stopped breaking mid-sentence: a break that only keeps a
desktop line short is now soft, and the phone rejoins it (round 4). On a
portrait phone the text box lost its arrow and moved to the middle of the
view, where a tall box fits (round 5). With the box mid-view, the arrow
cross went back to the top right (L-316 round 4). And a phone tap now
reaches a shell's marker instead of its dots, which Plotly had let win
the tap (round 6) -- Tony: "always opens on first tap." Rounds 5 and 6
apply to a portrait phone only, on Tony's word; the desktop is as it was.

**The two instruments now disagree about Jupiter's belts** (L-231): the
gallery's shared belt renderer moved Jupiter's too, and the orrery's
Jupiter builder was not touched. No room shows Jupiter yet, and Tony
ruled that it can wait for Jupiter's room.

**Tony's standing rule of 2026-09-16: no compressed language in hover
text.** What the protocol asks of Claude's replies to Tony, the hovers now
owe the visitor (L-331).

**Next.** L-332 (the interactive-exhibit skill), then L-331 (the visitor
text, the four Sun hovers, and a plain-language pass over the hovers --
the Sun room is live, so it should be correct), Tony's calls on closing
L-316 and L-318, then L-330 (the belts' shape) and L-322. Handoff:
`documentation/HANDOFF_L316_L318_phone_chrome_20260916.md`.

### What this section deliberately does not carry
"""),
    ]),
]


def content_md5(data):
    return hashlib.md5(data.replace(b"\r\n", b"\n")).hexdigest()


def main():
    files = {}
    for path in FINGERPRINTS:
        if not os.path.isfile(path):
            print("FAILURE: %s not found. Run this from the orrery repo root."
                  % path)
            print("NOTHING was written.")
            return 1
        with open(path, "rb") as handle:
            files[path] = handle.read()

    for path, needle in GUARD:
        if needle.encode("ascii") in files[path]:
            print("FAILURE: this patch is already applied (%s in %s)."
                  % (needle, path))
            print("NOTHING was written.")
            return 1

    for path, expected in FINGERPRINTS.items():
        actual = content_md5(files[path])
        if actual != expected:
            print("FAILURE: BASE MOVED for %s." % path)
            print("  expected content md5 %s" % expected)
            print("  found                %s" % actual)
            print("  This patch is built against orrery cce6a933.")
            print("NOTHING was written.")
            return 1

    crlf = {p: files[p].count(b"\r\n") > 0 for p in files}

    def fit(path, block):
        return block.replace(b"\n", b"\r\n") if crlf[path] else block

    for path, edits in EDITS:
        staged = files[path]
        for n, (old, new) in enumerate(edits):
            count = staged.count(fit(path, old))
            if count != 1:
                print("FAILURE: in %s, hunk %d matched %d times, expected 1."
                      % (path, n + 1, count))
                print("NOTHING was written.")
                return 1
            staged = staged.replace(fit(path, old), fit(path, new))
        if any(b > 127 for b in staged):
            print("FAILURE: %s would contain non-ASCII bytes." % path)
            print("NOTHING was written.")
            return 1
        files[path] = staged

    for path in sorted(files):
        with open(path, "wb") as handle:
            handle.write(files[path])

    print("OK: %d file(s) written." % len(files))
    for path in sorted(files):
        print("    %-50s (%s)" % (path, "CRLF" if crlf[path] else "LF"))
    print()
    print("Next: python ledger_index.py LEDGER_CONSOLIDATED.md")
    print("  expect 327 L-blocks and no consistency problems.")
    print("Then push, and read the new orrery SHA back.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
