"""patch_L274_2_ledger_sibling_sweep.py -- L-274. Open the ledger block.

RUN COMMAND
-----------
Save this file into the ORRERY repo root (the folder holding
PROJECT_INSTRUCTIONS.md), open it in VS Code, and click Run.

    python patch_L274_2_ledger_sibling_sweep.py

    *** This is the ORRERY repository. The code fix it records lives in
        the GALLERY repo, applied by patch_L274_1_sibling_sweep.py. ***

WHAT IT DOES
------------
One insertion into LEDGER_CONSOLIDATED.md: the L-274 detail block, placed
immediately before L-272 in section A.

Only the DETAIL block is written. The INDEX at the top is regenerated by
ledger_index.py, which orrery_maintenance_run.py runs as a generator.

WHAT IT CANNOT CHECK
--------------------
The code fix is in the other repository, and nothing here can see it. So
this block records the fix as delivered-and-tested rather than as
confirmed-in-the-wild: the failure is a OneDrive mtime refresh on
Windows, which no Linux sandbox can reproduce. The proof is the next
builder run on Tony's machine showing the reap line. That is written into
the block as the open condition, not glossed.

WHAT IS PERMANENT
-----------------
The ledger block. This script is one-shot; archive it into
documentation/ once it has run.

NO BACKUP FILE
--------------
Per safe-file-editing 1.10.

Role: patch
Domain: dev_tools

Module created: September 1, 2026 with Anthropic's Claude Opus 5.
"""

import hashlib
import os
import sys

LEDGER = "LEDGER_CONSOLIDATED.md"
LEDGER_MD5 = "20dc89d826b98a11eb37ad2855e9cbd9"

ANCHOR = """#### [L-272] The gallery repo had no README"""

BLOCK = '''#### [L-274] The cache sweep aged by mtime, which is wrong in both directions
<!-- L:274 status:OPEN upd:2026-09-01 section:A flag: rice:3/3/95/2 -->
- **Tony found it by looking in the folder, 2026-09-01.** Fifteen
  `solar-system.quarantine_*` directories in the gallery's `data/`,
  oldest named 20260823. His words: "they are indeed accumulating. i was
  not even tracking this issue."
- **The removal already existed and had never been able to work.**
  `_sweep_siblings()` runs at every build start, immediately after
  `recover_incomplete_swap`, and reaps siblings older than
  `keep_days=3`. It aged them by `st_mtime`.
- **`st_mtime` is not a measure of anything here, and it fails in BOTH
  directions.** A rename PRESERVES mtime, so a quarantine minted today
  inherits `solar-system.prev`'s timestamp from days earlier --
  measured: `quarantine_20260901T180026Z`, created that afternoon, read
  Date modified 2026-08-30 21:13, two days before it existed. And
  OneDrive REFRESHES mtime on sync, so four quarantines named 20260829
  through 20260831 all read 2026-09-01 13:00 in the same listing. One
  failure reaps an autopsy immediately; the other never reaps at all.
  Tony's folder is the second kind. The rename half was confirmed by
  test rather than assumed.
- **Nobody noticed because the sweep printed NOTHING.** `shutil.rmtree`
  with `ignore_errors=True` inside `except OSError: pass`. Reaping
  thirty directories and reaping none produced identical output, which
  is none. That is A Check That Cannot Fail Is Not Passing in its
  purest form: the passing output could not prove the path was live,
  and it was not live for about six weeks.
- **The timestamp was in the name the whole time.**
  `quarantine_20260823T144310Z` carries its own run id, and neither a
  rename nor a sync can alter it. The fix parses the name and falls back
  to mtime only when there is no run id -- reporting every such fallback
  rather than taking it silently.
- **Two name shapes the parser has to accept, both found by reading the
  code rather than assuming one.** The quarantine call site formats
  `%Y%m%dT%H%M%S` WITHOUT the trailing Z when `run_id` is None, while
  the normal path passes a run id WITH it. And a single-object dry-run
  stages as `.staging_solar-system_<slug>_<runid>` (L-148), so the id is
  the trailing token, not the one after the prefix. The match is
  anchored at the end of the name for exactly that reason.
- **Where the fix went, and it is deliberately split.** The DELETION
  stays in `tools/gallery_cache_builder.py`, which already owned it --
  fixing the producer rather than adding a second consumer that would
  have inherited the same bug if it reached for mtime too. The NOTICING
  is new: `documentation/check_cache_siblings.py`, wired into
  `gallery_maintenance_run.py` as a report-only row. Siblings piling up
  is not a reason to refuse a commit; it is a reason to look. If the
  sweep goes quiet again, that row says so in a day instead of in six
  weeks.
- **Eight pins added to `test_gallery_cache_builder_offline.py`**, which
  gates the gallery runner: 149 checks -> 158. They cover both name
  shapes, the interposed slug, an unparseable name, a well-shaped but
  impossible date, and -- the case that started this -- a twelve-day-old
  quarantine whose mtime says it was touched seconds ago. One of them
  failed on first run, on Claude's arithmetic rather than on the code,
  which is the only evidence that any of them can fail.
- **The one-time bulk reap is expected and is a one-way action.** About
  fifteen directories go on the first builder run after this lands.
  They are gitignored, so git is NOT the backup, unlike the `.bak` case
  in L-271. They are crash remnants the gallery-cache-builder skill
  classifies as harmless and throwaway, and the new output names every
  one as it goes, so the reap is a record rather than a silence.
  `data/solar-system.prev` is untouched -- different name, different
  rule, and never hand-deleted.
- **OPEN CONDITION, and this is why it is not closed on delivery.** The
  failure is a OneDrive mtime refresh on Windows. It cannot be
  reproduced in a Linux container, so the sandbox proves the parser and
  the age decision but not the thing that actually broke. A simulation
  rebuilt Tony's exact fifteen names with mtimes forced to now, and the
  fixed sweep reaped twelve and kept three; that is a strong result and
  it is still a simulation. Close this when a real builder run on Tony's
  machine prints the reap line and the folder drops to three or four
  siblings.
- **Gap:** `data/objects_config.json.bak` was still on disk on
  2026-09-01. L-271 widened the ignore rule, so git now hides it
  permanently, which is precisely the hazard that item was about --
  a stale copy a later session can grep and read as current. Needs a
  hand delete. (do)
- **Claude:** RICE 3/3/95/2 -> 4.3 proposed, not confirmed. Confidence
  95 because the diagnosis is measured on both halves rather than
  inferred; Effort 2 for four files across two repos.
- **Ref:** L-216 (the same quarantine mechanism, diagnosed as harmless
  and correctly so -- what went unexamined was whether anything ever
  removed them); L-271 (the `.bak` finding, the same shape: a cleanup
  everyone believed existed); A Check That Cannot Fail Is Not Passing
  and A Report Names Its Items, resident protocol Part 3;
  gallery-cache-builder skill 1.4, Sibling directory semantics.

'''


def fail(msg):
    print("")
    print("FAILURE: " + msg)
    print("NOTHING was written.")
    print("Undo is Discard Changes in GitHub Desktop.")
    sys.exit(1)


def read_norm(path):
    with open(path, "rb") as fh:
        raw = fh.read()
    return raw.replace(b"\r\n", b"\n"), b"\r\n" in raw


def main():
    if not os.path.isfile("PROJECT_INSTRUCTIONS.md"):
        fail("run this from the ORRERY repo root (the folder holding "
             "PROJECT_INSTRUCTIONS.md). Current folder: " + os.getcwd())

    if not os.path.isfile(LEDGER):
        fail(LEDGER + " not found in " + os.getcwd())

    content, was_crlf = read_norm(LEDGER)
    actual = hashlib.md5(content).hexdigest()
    if actual != LEDGER_MD5:
        fail("BASE MOVED. " + LEDGER + " fingerprints " + actual +
             ", expected " + LEDGER_MD5 + ".\n"
             "  Establish WHAT differs before assuming an edit was made: a\n"
             "  size delta of about one byte per line means line endings,\n"
             "  not content.")
    print("ok  base fingerprint matches" +
          (" [CRLF working copy, matched after normalising]" if was_crlf else ""))

    text = content.decode("ascii", "strict")

    if "L-274" in text:
        fail("the ledger already mentions L-274. This patch has already run, "
             "or that handle is taken.")

    n = text.count(ANCHOR)
    if n != 1:
        fail("anchor appears %d times, expected exactly 1." % n)
    print("ok  anchor found exactly once, and L-274 is free")

    new_text = text.replace(ANCHOR, BLOCK + ANCHOR, 1)

    out = new_text.encode("ascii")
    if was_crlf:
        out = out.replace(b"\n", b"\r\n")
    with open(LEDGER, "wb") as fh:
        fh.write(out)
    print("ok  wrote %s (%d bytes)" % (LEDGER, len(out)))

    # ---- verification: read back from disk ----
    back, _ = read_norm(LEDGER)
    got = back.decode("ascii", "replace")
    problems = []
    if got.count("#### [L-274] The cache sweep aged by mtime") != 1:
        problems.append("L-274 header not present exactly once")
    if got.count("<!-- L:274 status:OPEN") != 1:
        problems.append("L-274 metadata line not present exactly once")
    if got.count(ANCHOR) != 1:
        problems.append("L-272's header was duplicated or lost")
    if got.count("#### [L-273]") != 1:
        problems.append("L-273's block was disturbed")

    if problems:
        print("")
        print("VERIFICATION FAILED after writing:")
        for p in problems:
            print("  - " + p)
        print("Undo is Discard Changes in GitHub Desktop.")
        sys.exit(1)

    print("ok  verified: L-274 present once, L-272 and L-273 intact")
    print("")
    print("patch applied. One block added:")
    print("  L-274  new, OPEN      sibling sweep aged by mtime")
    print("")
    print("NEXT STEPS")
    print("  1. Run: python orrery_maintenance_run.py")
    print("     ledger_index.py regenerates the INDEX. Do not hand-edit it.")
    print("  2. Commit the ledger and this script (after moving it into")
    print("     documentation/) together.")
    print("")
    print("L-274 STAYS OPEN until a real builder run on your machine")
    print("prints the reap line. The Windows/OneDrive half cannot be")
    print("proven from a Linux sandbox, so the block says so rather than")
    print("claiming a fix nobody has watched work.")


if __name__ == "__main__":
    main()
