# -*- coding: ascii -*-
"""patch_mars_dead_copies.py -- L-156 geometry corrections + <br> fix for mars_visualization_shells.py

Built on 06a16df768a010205b7078630ac31bf0cd17f846
at https://github.com/tonylquintanilla/palomas_orrery (branch main).

HOW TO RUN
    Save this file into the SAME FOLDER as mars_visualization_shells.py, open it in
    VS Code, and click Run. No arguments, no flags, nothing to type.

    Success prints one "ok" line per edit then "patch applied".
    Failure prints one ANCHOR FAIL:/ERROR: line and writes NOTHING --
    the file on disk stays untouched, so it is always safe to re-run.

Transactional: every anchor must match exactly once before any byte is
written. Binary mode throughout; LF endings and ASCII preserved.

11 edits, applied bottom-up by line number.
"""

import os
import sys

TARGET = 'mars_visualization_shells.py'

# (edit_id, label, old_bytes, new_bytes) -- bottom-up by line number
EDITS = [
    ('MARS-RF2', 'dead legacy builder radius_fraction 320 -> 324.5',
     b"    radius_fraction = 320  # Mars's Hill sphere is about 320 Mars radii",
     b"    radius_fraction = 324.5  # Mars's Hill sphere is about 324.5 Mars radii"),
    ('MARS-TXT2', 'dead description text 320 -> 324.5 Mars radii',
     b'                "Mars\'s Hill Sphere (extends to ~320 Mars radii or about 1.1 million km), which defines the region of its <br>" ',
     b'                "Mars\'s Hill Sphere (extends to ~324.5 Mars radii or about 1.1 million km), which defines the region of its <br>" '),
    ('MARS-RF1', 'dead legacy dict radius_fraction 320 -> 324.5',
     b"        'radius_fraction': 320,  ",
     b"        'radius_fraction': 324.5,  "),
    ('BR-mars_hill_sphere_info', 'mars_hill_sphere_info: 3 <br> -> \\n',
     b'mars_hill_sphere_info = (\n            "SET MANUAL SCALE TO AT LEAST 0.01 AU TO VISUALIZE.<br><br>" \n            "Mars\'s Hill Sphere (extends to ~320 Mars radii or about 1.1 million km), which defines the region of its <br>" \n            "gravitational influence and encompasses its two moons."\n)\n',
     b'mars_hill_sphere_info = (\n            "SET MANUAL SCALE TO AT LEAST 0.01 AU TO VISUALIZE.\\n\\n" \n            "Mars\'s Hill Sphere (extends to ~324.5 Mars radii or about 1.1 million km), which defines the region of its \\n" \n            "gravitational influence and encompasses its two moons."\n)\n'),
    ('BR-mars_magnetosphere_info', 'mars_magnetosphere_info: 8 <br> -> \\n',
     b'mars_magnetosphere_info = (\n    "SET MANUAL SCALE TO AT LEAST 0.005 AU TO VISUALIZE.<br><br>"\n    "Unlike Earth, Mars lacks a global magnetic field generated by its core. Instead, it has:<br><br>"\n    "1. Induced Magnetosphere: Created by the interaction between the solar wind and Mars\' ionosphere. "\n    "It\'s much weaker and closer to the planet than Earth\'s magnetosphere, extending only about 1-2 Mars radii "\n    "on the Sun-facing side.<br><br>"\n    "2. Bow Shock: Still forms where the solar wind first encounters Mars\' atmosphere and ionosphere, "\n    "but it\'s much closer to the planet (around 1.6 Mars radii).<br><br>"\n    "3. Crustal Magnetic Fields: Localized \'mini-magnetospheres\' created by magnetized regions in Mars\' crust, "\n    "particularly in the southern hemisphere. These are remnants of Mars\' ancient global magnetic field "\n    "that existed billions of years ago."\n)\n',
     b'mars_magnetosphere_info = (\n    "SET MANUAL SCALE TO AT LEAST 0.005 AU TO VISUALIZE.\\n\\n"\n    "Unlike Earth, Mars lacks a global magnetic field generated by its core. Instead, it has:\\n\\n"\n    "1. Induced Magnetosphere: Created by the interaction between the solar wind and Mars\' ionosphere. "\n    "It\'s much weaker and closer to the planet than Earth\'s magnetosphere, extending only about 1-2 Mars radii "\n    "on the Sun-facing side.\\n\\n"\n    "2. Bow Shock: Still forms where the solar wind first encounters Mars\' atmosphere and ionosphere, "\n    "but it\'s much closer to the planet (around 1.6 Mars radii).\\n\\n"\n    "3. Crustal Magnetic Fields: Localized \'mini-magnetospheres\' created by magnetized regions in Mars\' crust, "\n    "particularly in the southern hemisphere. These are remnants of Mars\' ancient global magnetic field "\n    "that existed billions of years ago."\n)\n'),
    ('BR-mars_upper_atmosphere_info', 'mars_upper_atmosphere_info: 9 <br> -> \\n',
     b'mars_upper_atmosphere_info = (\n            "Upper Atmosphere: Like Earth, Mars has upper atmospheric layers, including an ionosphere and exosphere, where <br>" \n            "the atmosphere becomes very thin and interacts with solar radiation and the solar wind.<br><br>" \n            "Exosphere: This is the outermost layer, starting above the thermosphere (around 200 km/124 miles) and gradually <br>" \n            "thinning out into space. Atoms and molecules here are so far apart that they can escape the planet\'s gravity.<br><br>" \n            "Interaction with Solar Wind: Without a global magnetosphere, the Martian atmosphere is directly exposed to the <br>" \n            "solar wind, a stream of charged particles from the Sun. This interaction is believed to have played a significant <br>" \n            "role in stripping away much of Mars\' early, potentially thicker atmosphere and contributing to the loss of liquid <br>" \n            "water on the surface."\n)\n',
     b'mars_upper_atmosphere_info = (\n            "Upper Atmosphere: Like Earth, Mars has upper atmospheric layers, including an ionosphere and exosphere, where \\n" \n            "the atmosphere becomes very thin and interacts with solar radiation and the solar wind.\\n\\n" \n            "Exosphere: This is the outermost layer, starting above the thermosphere (around 200 km/124 miles) and gradually \\n" \n            "thinning out into space. Atoms and molecules here are so far apart that they can escape the planet\'s gravity.\\n\\n" \n            "Interaction with Solar Wind: Without a global magnetosphere, the Martian atmosphere is directly exposed to the \\n" \n            "solar wind, a stream of charged particles from the Sun. This interaction is believed to have played a significant \\n" \n            "role in stripping away much of Mars\' early, potentially thicker atmosphere and contributing to the loss of liquid \\n" \n            "water on the surface."\n)\n'),
    ('BR-mars_atmosphere_info', 'mars_atmosphere_info: 1 <br> -> \\n',
     b'mars_atmosphere_info = (\n            "Atmosphere: Mars has a thin atmosphere, much less dense than Earth\'s. It\'s primarily composed of carbon dioxide <br>" \n            "(about 95%), with small amounts of nitrogen, argon, and other gases."\n)\n',
     b'mars_atmosphere_info = (\n            "Atmosphere: Mars has a thin atmosphere, much less dense than Earth\'s. It\'s primarily composed of carbon dioxide \\n" \n            "(about 95%), with small amounts of nitrogen, argon, and other gases."\n)\n'),
    ('BR-mars_crust_info', 'mars_crust_info: 2 <br> -> \\n',
     b'mars_crust_info = (\n            "Mars\'s crust: Mars has a crust, which is the outermost solid shell. Interestingly, recent findings from marsquakes <br>" \n            "suggest that the Martian crust is significantly thicker than Earth\'s, perhaps averaging around 70 kilometers <br>" \n            "(43 miles) or even thicker in some areas."\n)\n',
     b'mars_crust_info = (\n            "Mars\'s crust: Mars has a crust, which is the outermost solid shell. Interestingly, recent findings from marsquakes \\n" \n            "suggest that the Martian crust is significantly thicker than Earth\'s, perhaps averaging around 70 kilometers \\n" \n            "(43 miles) or even thicker in some areas."\n)\n'),
    ('BR-mars_mantle_info', 'mars_mantle_info: 1 <br> -> \\n',
     b'mars_mantle_info = (\n            "Mantle: Surrounding the core is a silicate mantle, similar to Earth\'s. It\'s composed of dense rocks rich in <br>" \n            "elements like silicon, oxygen, iron, and magnesium."\n)\n',
     b'mars_mantle_info = (\n            "Mantle: Surrounding the core is a silicate mantle, similar to Earth\'s. It\'s composed of dense rocks rich in \\n" \n            "elements like silicon, oxygen, iron, and magnesium."\n)\n'),
    ('BR-mars_outer_core_info', 'mars_outer_core_info: 3 <br> -> \\n',
     b'mars_outer_core_info = (\n            "A Liquid Outer Core: Surrounding the solid inner core is believed to be a liquid outer core, also primarily <br>" \n            "made of iron and nickel, but likely containing a significant amount of lighter elements like sulfur, oxygen, <br>" \n            "or even hydrogen. The presence of these lighter elements would lower the melting point of the iron-nickel alloy, <br>" \n            "allowing it to remain liquid despite the pressure."\n)\n',
     b'mars_outer_core_info = (\n            "A Liquid Outer Core: Surrounding the solid inner core is believed to be a liquid outer core, also primarily \\n" \n            "made of iron and nickel, but likely containing a significant amount of lighter elements like sulfur, oxygen, \\n" \n            "or even hydrogen. The presence of these lighter elements would lower the melting point of the iron-nickel alloy, \\n" \n            "allowing it to remain liquid despite the pressure."\n)\n'),
    ('BR-mars_inner_core_info', 'mars_inner_core_info: 1 <br> -> \\n',
     b'mars_inner_core_info = (\n            "A Solid Inner Core: Based on seismic data from the InSight lander, scientists have strong evidence that Mars <br>" \n            "possesses a solid inner core. This inner core is primarily composed of iron and nickel, similar to Earth\'s."\n)\n',
     b'mars_inner_core_info = (\n            "A Solid Inner Core: Based on seismic data from the InSight lander, scientists have strong evidence that Mars \\n" \n            "possesses a solid inner core. This inner core is primarily composed of iron and nickel, similar to Earth\'s."\n)\n'),
]


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, TARGET)

    if not os.path.exists(path):
        print("ERROR: %s not found next to this script." % TARGET)
        return 1

    with open(path, 'rb') as f:
        content = f.read()
    original_len = len(content)

    if b'\r\n' in content:
        print("ERROR: %s contains CRLF line endings; expected LF only." % TARGET)
        return 1

    for edit_id, label, old, new in EDITS:
        n = content.count(old)
        if n != 1:
            print("ANCHOR FAIL: %s (%s) matched %d times, expected 1." % (edit_id, label, n))
            print("             Nothing was written. The file is unchanged.")
            print("             Anchor began: %r" % old.split(b'\n')[0][:90])
            return 1

    for edit_id, label, old, new in EDITS:
        content = content.replace(old, new, 1)
        print("ok  %-22s %s" % (edit_id, label))

    try:
        content.decode('ascii')
    except UnicodeDecodeError as exc:
        print("ERROR: patched result has non-ASCII bytes (%s). Nothing written." % exc)
        return 1
    if b'\r\n' in content:
        print("ERROR: patched result contains CRLF. Nothing written.")
        return 1

    with open(path, 'wb') as f:
        f.write(content)

    print("")
    print("patch applied (%d bytes, was %d)" % (len(content), original_len))
    return 0


if __name__ == '__main__':
    sys.exit(main())
